### ISSUE TITLE
Speeh recognition TF lite

### ISSUE THREAD

**Issue by singh728om** [tensorflow/tensorboard#2921] opened 2019-11-12 16:00 UTC
After debugging when I press start button the app couldn't recognise any speech help..me

**Comment by rmothukuru** [comment] 2019-11-13 02:13
@singh728om,
Can you please confirm if this issue is related to Tensorboard. 

If so, can you please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. 

If the issue is not related to Tensorboard, but if it is related to Tensorflow Lite, request you to raise an issue in this [Github Repository](https://github.com/tensorflow/tensorflow/issues). Thanks!

**Comment by singh728om** [comment] 2019-11-13 06:06
@rmothukuru Thanks for suggestion  issue is related to Tensorflow Lite.

**Comment by rmothukuru** [comment] 2019-11-13 08:04
Closing the issue as it is related to TF Lite. As mentioned above, please raise the issue in this [Github Repository](https://github.com/tensorflow/tensorflow/issues). Thanks!

**Closed** 2019-11-13 08:04 UTC
Labels: plugin:audio, stat:awaiting response, type:support
