### ISSUE TITLE
Increase the number of points displayed on Embeddings Projector

### ISSUE THREAD

**Issue by saikot-paul** [tensorflow/tensorboard#6635] opened 2023-10-13 18:05 UTC
Currently the data is down sampled to 10000 points to project, it would be nice to have an option that allows you to display all the data in a local or colab environment.

**Comment by arcra** [comment] 2023-10-24 21:50
Hello @saikot-paul, I see you also commented on #773. Is this a duplicate of that issue? I will close this assuming it is a duplicate, and I'll comment on there as well. Feel free to re-open if there's something different about this request.

**Closed by arcra** 2023-10-24 21:50 UTC
