### ISSUE TITLE
Uncaught (in promise) TypeError: _.contains is not a function

### ISSUE THREAD

**Issue by dejanbatanjac** [tensorflow/tensorboard#1684] opened 2018-12-11 08:53 UTC
TensorBoard running under Ubuntu Chromium Web Browser.
Switch to Show Code mode, select a python file and the error like this one occurs:
```
(index):12064 Uncaught (in promise) TypeError: _.contains is not a function
    at (index):12064
    at Array.filter (<anonymous>)
    at HTMLElement._filterFileTracebacksByDebugWatches ((index):12064)
    at (index):12058
```

**Comment by stephanwlee** [comment] 2018-12-11 15:59
Hi @dejanbatanjac can you please fill out the issue template? Which version of TensorBoard are you using?
Thanks!

**Comment by dejanbatanjac** [comment] 2018-12-11 16:54
TensorBoard VERSION = '1.12.0'
Python 2.7.15rc1
@stephanwlee can you link to the issue template? I would be glad to fill it out.

**Comment by stephanwlee** [comment] 2018-12-11 17:18
Issue template looks something like this when you create one:
![image](https://user-images.githubusercontent.com/2547313/49817566-6ed6fa80-fd25-11e8-86e8-a36da6442300.png)

It looks like the issue is fixed in #1550. The fix should be part of next release. Thanks!

**Closed by stephanwlee** 2018-12-11 17:18 UTC

**Comment by dejanbatanjac** [comment] 2018-12-11 20:07
@stephanwlee You may check out the previous post. I updated the issue.

**Comment by wchargin** [comment] 2018-12-11 21:10
@dejanbatanjac: Thanks. The stack trace that you provided refers to the
function that was patched in #1550, the PR that @stephanwlee linked
earlier. There are currently no references to `_.contains` in our code.

As Stephan said, this fix will be included in the next release.
