### ISSUE TITLE
[error] empty graph tab

### ISSUE THREAD

**Issue by bb2103** [tensorflow/tensorboard#772] opened 2017-11-25 03:32 UTC
tensorboard fails to draw graph with error.
training and log is okay, im pretty sure this is tensorboard's bug.
web logs:
```
[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
iron-shadow-flex-layout.html:12 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
(anonymous) @ iron-shadow-flex-layout.html:12
iron-flex-layout.html:14 This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead
(anonymous) @ iron-flex-layout.html:14
[Deprecation] /deep/ combinator in CSS is deprecated and will be removed in M63, around December 2017. See https://www.chromestatus.com/features/4964279606312960 for more details.
tb20171125031258vnsfzfdtuxxlepjcrbzfjuqg.tensorboard.pai.odps.aliyun-inc.com/:1 Blink deferred a task in order to make scrolling smoother. Your timer and network tasks should take less than 50ms to run to avoid this. Please see https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/rail and https://crbug.com/574343#c40 for more information.
tf-tensorboard.html:12432 Reading graph pbtxt : 1 ms
tf-tensorboard.html:12432 Reading graph pbtxt : 1 ms
tf-tensorboard.html:12432 Parsing graph.pbtxt : 4 ms
tf-tensorboard.html:12432 Normalizing names : 111 ms
tf-tensorboard.html:12432 Building the data structure : 43 ms
tf-tensorboard.html:12432 Adding nodes : 72 ms
tf-tensorboard.html:12432 Detect series : 84 ms
tf-tensorboard.html:12432 Adding edges : 98 ms
tf-tensorboard.html:12432 Finding similar subgraphs : 123 ms
tf-tensorboard.html:12432 tf-graph-scene (layout): : 72 ms
tf-tensorboard.html:12432 tf-graph-scene (build scene): : 94 ms
tf-tensorboard.html:12432 new tf.graph.render.Hierarchy : 177 ms
tf-tensorboard.html:10555 Uncaught TypeError: pathNode.getPathSegAtLength is not a function
    at adjustPathPointsForMarker (tf-tensorboard.html:10555)
    at SVGPathElement.getEdgePathInterpolator (tf-tensorboard.html:10648)
    at SVGPathElement.attrTween (d3.js:8772)
    at d3_Map.<anonymous> (d3.js:8945)
    at d3_Map.forEach (d3.js:341)
    at start (d3.js:8944)
    at Object.schedule (d3.js:8912)
    at d3_timer_mark (d3.js:2165)
    at d3_timer_step (d3.js:2146)
    at web-animations-next-lite.min.js:16
adjustPathPointsForMarker @ tf-tensorboard.html:10555
getEdgePathInterpolator @ tf-tensorboard.html:10648
attrTween @ d3.js:8772
(anonymous) @ d3.js:8945
forEach @ d3.js:341
start @ d3.js:8944
schedule @ d3.js:8912
d3_timer_mark @ d3.js:2165
d3_timer_step @ d3.js:2146
(anonymous) @ web-animations-next-lite.min.js:16
tf-tensorboard.html:12432 Parsing graph.pbtxt : 5 ms
tf-tensorboard.html:12432 Normalizing names : 101 ms
tf-tensorboard.html:12432 Building the data structure : 39 ms
tf-tensorboard.html:12432 Adding nodes : 34 ms
tf-tensorboard.html:12432 Detect series : 45 ms
tf-tensorboard.html:12432 Adding edges : 74 ms
tf-tensorboard.html:12432 Finding similar subgraphs : 103 ms
tf-tensorboard.html:12432 tf-graph-scene (layout): : 53 ms
tf-tensorboard.html:12432 tf-graph-scene (build scene): : 70 ms
tf-tensorboard.html:12432 new tf.graph.render.Hierarchy : 141 ms
tf-tensorboard.html:12926 Uncaught TypeError: Cannot read property '0' of undefined
    at Minimap.zoom (tf-tensorboard.html:12926)
    at HTMLElement.<anonymous> (tf-tensorboard.html:13782)
    at d3.js:1119

```

**Comment by nfelt** [comment] 2017-12-06 01:33
Thanks for the report.  Could you provide your version of TensorBoard/TensorFlow and your system information (platform, OS version)?

To debug this we'll probably need to have a way to reproduce it.  Is there a way you could either provide an events file that causes this error, or some tensorflow code that creates such an event file?

**Comment by Erickrus** [comment] 2017-12-06 04:52
Actually I have a quick hot-fix here to by-pass the exception and then it works and shows the result diagram. The file is stored in /usr/local/lib/python2.7/dist-packages/tensorboard/tensorboard.runfiles/org_tensorflow/tensorflow/tensorboard/dist/tf-tensorboard.html .

Line 10555: 
segIndex = pathNode.getPathSegAtLength(length_1);

REPLACE AS (by giving a default value segIndex = 1):
var segIndex = 1;
try {
    segIndex = pathNode.getPathSegAtLength(length_1);
} catch(e) {}

Finally, make sure you clean up the browser cache files, then restart tensorboard and go to Graph again. For my case it works

**Comment by nfelt** [comment] 2017-12-06 19:54
@bb2103 I just was made aware of https://github.com/tensorflow/tensorboard/pull/434 which should have addressed the getPathSegAtLength() error at least, by re-implementing it in JS since it was removed from Chrome as of Chrome 62.  That change should be in 0.4.0+, can you upgrade your TensorBoard and try again?

@Erickrus the pip package "tensorboard" is actually misleadingly not ours, it corresponds to https://github.com/dmlc/tensorboard which is an unrelated derivative.  To install TensorBoard please use `pip install tensorflow-tensorboard` or it should also be installed with `pip install tensorflow`.

**Comment by Erickrus** [comment] 2017-12-07 04:00
@nfelt  ok. anyway, you could check the uploaded event.file.zip

**Comment by nfelt** [comment] 2017-12-08 03:20
@Erickrus Sure, I checked your events file and it loads just fine in `0.4.0rc3`.  To be clear, I appreciate you providing it and the fix; I just meant to clarify that I'd discovered that this particular error actually was already fixed in our repo, and that while dmlc tensorboard might still have the error, they're a different repo and you'd have to take it up with them to get the issue fixed there.

@bb2103 closing but feel free to re-open if a newer version of TensorBoard doesn't fix your issue.

**Closed by nfelt** 2017-12-08 03:20 UTC
Labels: plugin:graph, stat:awaiting response, type:bug/performance
