### ISSUE TITLE
Option to highlight min/max point on curve

### ISSUE THREAD

**Issue by ismael-elatifi** [tensorflow/tensorboard#3668] opened 2020-05-23 10:03 UTC
We often zoom into the curves to find the highest/lowest value of our metric/loss.
It would be great if we add an option to automatically highlight the best point on a curve.
We could have 2 checkboxes below each curve : one to highlight the minimum point and the other to highlight the maximum point.
"Highlighting" could be simply to show a bigger point with a dedicated color.

**Comment by bmd3k** [comment] 2020-05-28 13:52
Thanks Ismael for your suggestions,
This is an interesting idea. We discussed briefly as a team and decided to put it on our backlog.

**Comment by nfelt** [comment] 2020-10-24 00:51
Duplicate of #1030

**Comment by nfelt** [comment] 2020-10-24 00:51
Closing in favor of #1030 which predates this request by a bit - please follow that issue.

**Closed by nfelt** 2020-10-24 00:51 UTC
Labels: plugin:scalars, type:feature
