### ISSUE TITLE
Download PNG is totally blank using tensorboard 1.5.0

### ISSUE THREAD

**Issue by ShangjinTang** [tensorflow/tensorboard#924] opened 2018-01-31 06:58 UTC
## Issue description

Image generated on "Download PNG" is totally blank with tensorboard 1.5.0.

Image generated on "Download PNG" is fine after replaced tensorboard 1.5.0 with tensorboard 0.4.0.

## Environment

- PC 1 (GPU version): Windows 10 + Python 3.6.3 + TensorFlow-GPU 1.5.0 + Tensorboard 1.5.0 + CUDA 9.0 + cuDNN 7.0.5 
- PC 2 (CPU version): Windows 7 + Python 3.6.3 + TensorFlow 1.5.0 + Tensorboard 1.5.0
- PC 3 (CPU version): Windows 7 + Python 3.6.3 + TensorFlow 1.5.0 + Tensorboard 1.5.0

> Not tested on Linux yet.

## Issue Steps

1. Install python 3.6.3, tensorflow 1.5.0 (GPU version or CPU version).

> Dependency package tensorboard 1.5.0 will be installed with tensorflow 1.5.0.

2. Generate a log, such as the code below:

```
import tensorflow as tf

sess = tf.InteractiveSession()

with tf.name_scope('a'):
  a = tf.Variable(4, dtype=tf.int32)
with tf.name_scope('b'):
  b = tf.Variable(3, dtype=tf.int32)
with tf.name_scope('c'):
  c = tf.multiply(a, b)
tf.summary.scalar('output', c)

merged = tf.summary.merge_all()
summary, c_val = sess.run([merged, c], feed_dict={a: 4, b: 5})
writer = tf.summary.FileWriter(r"C:\tmp", graph=sess.graph)
writer.add_summary(summary)
writer.close()
```

3. Run `tensorboard --logdir=C:\tmp`, then open tensorboard (port 6006) in Chrome browser.

4. Click `Download PNG` on the left sidebar of `TensorBoard` - `GRAPHS`.

- File name: `graph_large_attrs_key=_too_large_attrs&limit_attr_size=1024&run=.png`
- File size: `3.06 KB`
- File pixel: 495 * 286

5. Open the image, but the image shows nothing invalid. The image is totally blank.

## Recovery Steps

1. Download "tensorflow_tensorboard-0.4.0-py3-none-any.whl" on [PYPI](https://testpypi.python.org/pypi/tensorflow-tensorboard/0.4.0)

2. `pip3 install tensorflow_tensorboard-0.4.0-py3-none-any.whl`. After installation tensorboard 0.4.0, the tensorflow version is still 1.5.0.

3. **Use the same log in Issue Step 2**. Run `tensorboard --logdir=C:\tmp`, then open tensorboard (port 6006) in Chrome browser.

4. Click `Download PNG` on the left sidebar of `TensorBoard` - `GRAPHS`.

- File name: `graph_large_attrs_key=_too_large_attrs&limit_attr_size=1024&run=D%5C.png`
- File size: `11.9 KB`
- File pixel: `495 * 286`

5. Open the image, the image shows graph successfully.

**Comment by ShangjinTang** [comment] 2018-01-31 11:38
The Graphs URLs are also different and related to image file names, which might help this issue:
- tensorboard 1.5.0 GRAPHS URL : `localhost:6006/#graphs&run=.`
- tensorboard 0.4.0 GRAPHS URL : `localhost:6006/#graphs&run=D%5C.`

**Comment by nfelt** [comment] 2018-02-01 05:54
Thanks for the report.  I wonder if the URL issue might be a red herring - PR #265 which added support for passing windows drive names as logdirs without having the drive interpreted as a run name.  So in 1.5.0 `--logdir=C:\tmp` will result in a run using the directory `C:\tmp` with the default run name `.`, while in 0.4.0 `--logdir=C:\tmp` would result in a run using the directory `\tmp` on the current drive, with the run renamed to `C`.  The 0.4.0 filename's `run=D%5C.png` would correspond to a run named `D\` which looks a lot like a drive name, maybe - were you running TensorBoard from `D` drive?

I'll see if I can repro this on non-windows.

**Comment by nfelt** [comment] 2018-02-01 05:58
Yep, I can definitely reproduce this!  We will investigate.

**Comment by nfelt** [comment] 2018-02-01 06:05
Actually, this has the same root cause as the minimap breakage fixed by #899, so #899 should also have fixed this issue.  If you install `tb-nightly` with the latest nightly build of TensorBoard it should have the fix already.  We'll be patching some fixes into a 1.5.1 bugfix release soon and I'll make sure this fix makes it in.

**Comment by ShangjinTang** [comment] 2018-02-01 08:36
@nfelt Thanks for your feedback.  I'll update to tensorboard 1.5.1 after it's released.

**Comment by nfelt** [comment] 2018-02-08 06:55
Closing this out since TensorBoard 1.5.1 has now been released and should fix this issue.

**Closed by nfelt** 2018-02-08 06:55 UTC
Labels: plugin:graph, type:bug/performance

**Comment by zkl99999** [comment] 2018-11-27 05:44
ubtuntu16.04, i use docker tensorflow-gpu 1.12.0, in docker use tensorboard ,  open chrome https://local:6006,  show  graph, but i push bottom  download png, graph_run=.png  also is blank, how it why

**Comment by MrChenFeng** [comment] 2020-04-07 12:38
Everything is okay with my Tensorboard, but when I try to download PNG, the downloaded file seems to be broken?

**Comment by udithhaputhanthri** [comment] 2020-05-29 17:46
In the tensorboard on collab, download PNG gives "Failed- Forbidden" message. Is there any way to download the .png image.
