### ISSUE TITLE
--host does not work anymore

### ISSUE THREAD

**Issue by Daniel-01** [tensorflow/tensorboard#5648] opened 2022-04-04 07:58 UTC
## Issue description
Using Tensorboard 2.8.0:

tensorboard --logdir my_dir --host 0.0.0.0
TensorFlow installation not found - running with reduced feature set.
Error: Must not specify both --host and --bind_all.

Note that I did NOT specify --bind_all. Yet it complains that I have done so.
The above command works fins in tensorboard 2.5.0 and was the most convinent way to make the board accessible from a remote computer.

**Comment by bileschi** [comment] 2022-04-05 14:43
Sorry for the trouble: 
Tried to reproduce locally and the command appears to work for me. Both in clean venv with 2.8.0 and at HEAD

```
$ tensorboard --logdir ~/tensorboard-logdirs/scalars_demo --host 0.0.0.0
```
```
...
NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

TensorBoard 2.8.0 at http://0.0.0.0:6006/ (Press CTRL+C to quit)
```

Is it possible that your shell is somehow adding the `--bind_all` arg?  

Can you try the following in a clean virtual env 

make a clean virtual env:
```
$ deactivate
$ python3 -m venv /tmp/tb-venv
$ pip3 install tensorboard
```
Test the fresh TensorBoard install
```
$ tensorboard --version
$ tensorboard --logdir my_dir --host 0.0.0.0
```

**Comment by Daniel-01** [comment] 2022-04-05 15:11
Yes, that works. 
Must be something weird in the docker l am using: nvcr.io/nvidia/pytorch:22.01-py3
Maybe Nvidia adds --bind_all automatically somehow?
Sorry for the false alarm.

**Comment by bileschi** [comment] 2022-04-05 15:15
No worries!  Glad you're back into a working state.  Closing the issue for now, please reopen if this is not actually complete.

**Closed by bileschi** 2022-04-05 15:15 UTC

**Comment by huxuan** [comment] 2022-06-10 09:04
For folks using the nvidia NGC Pytorch docker image, the source code of the built-in tensorboard seems to be changed by some reason. The following `sed` command will revert the inconsistent behavior.

```
sed -i "s/\"--bind_all\", default=True,/\"--bind_all\",/g" /opt/conda/lib/python3.8/site-packages/tensorboard/plugins/core/core_plugin.py
```

**Comment by GuunerAndGooner** [comment] 2023-06-05 08:30
* I followed @huxuan  suggestion and modified the default parameters of bind_all to solve this problem

```shell
root@localhost:~$ pip show tensorboard
Name: tensorboard
Version: 2.9.0
Summary: TensorBoard lets you watch Tensors Flow
Home-page: https://github.com/tensorflow/tensorboard
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: absl-py, google-auth, google-auth-oauthlib, grpcio, markdown, numpy, protobuf, requests, setuptools, tensorboard-data-server, tensorboard-plugin-wit, werkzeug, wheel
Required-by: tensorflow

root@localhost:~$ tensorboard --version
2.9.0

root@localhost:~$ grep bind_all /usr/local/lib/python3.8/dist-packages/tensorboard/plugins/core/core_plugin.py
            default=None,  # like localhost, but prints a note about `--bind_all`
network on both IPv4 and IPv6, see `--bind_all`, with which this option is
            "--bind_all", default=False,
        elif flags.host is not None and flags.bind_all:
            raise FlagsError("Must not specify both --host and --bind_all.")
```

**Comment by aisensiy** [comment] 2023-08-04 04:12
No one is trying to fix this? I have to sed it myself??

**Comment by bileschi** [comment] 2023-08-08 16:36
Is this an actual issue with TensorBoard, or is it an issue with some vended version of TensorBoard?

**Comment by HoseinHashemi** [comment] 2024-09-02 07:30
Having the same issue with NGC Tensorflow docker image.

**Comment by HoseinHashemi** [comment] 2024-09-04 09:11
> For folks using the nvidia NGC Pytorch docker image, the source code of the built-in tensorboard seems to be changed by some reason. The following `sed` command will revert the inconsistent behavior.
> 
> ```
> sed -i "s/\"--bind_all\", default=True,/\"--bind_all\",/g" /opt/conda/lib/python3.8/site-packages/tensorboard/plugins/core/core_plugin.py
> ```

This solves the issue. However, when running something like Tensorboard that needs a port to be mapped and accessed you probably need to pars ```--bind_all``` again and you get into the same issue. I might be missing something though.
