### ISSUE TITLE
histogram plot for Preactivation/activation layer

### ISSUE THREAD

**Issue by neerajtiwari360** [tensorflow/tensorboard#3148] opened 2020-01-17 06:32 UTC
Well after going through tensorboard with tensorflow2.0, I am unable to plot the activation histogram for any layer, I can only see the tab for Conv and batch normalization.
can you please support me for activation visualization, in tensorflow2.0.

**Comment by rmothukuru** [comment] 2020-01-20 08:55
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment] 2020-02-03 05:53
@neerajtiwari360,
Can you please provide the information asked in the above comment. Thanks!

**Comment by rmothukuru** [comment] 2020-02-07 02:29
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed** 2020-02-07 02:29 UTC
Labels: core:frontend, plugin:histogram, stat:awaiting response
