### ISSUE TITLE
ImportError: cannot import name '_message' from 'google.protobuf.pyext' (c:\programdata\anaconda3\lib\site-packages\google\protobuf\pyext\__init__.py)

### ISSUE THREAD

**Issue by bestazad** [tensorflow/tensorboard#1863] opened 2019-02-17 18:13 UTC
I am trying this command(That I don't know what it does! I only following a tutorial):

    tensorboard --logdir=/tmp/tensorflow/rnn_words
And get this result:

    Traceback (most recent call last):
      File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "C:\ProgramData\Anaconda3\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
      File "c:\programdata\anaconda3\lib\site-packages\tensorboard\main.py", line 45, in <module>
        from tensorboard import default
      File "c:\programdata\anaconda3\lib\site-packages\tensorboard\default.py", line 34, in <module>
        import tensorflow as tf
      File "c:\programdata\anaconda3\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
        from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
      File "c:\programdata\anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
        from tensorflow.core.framework.graph_pb2 import *
      File "c:\programdata\anaconda3\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
        from google.protobuf import descriptor as _descriptor
      File "c:\programdata\anaconda3\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
        from google.protobuf.pyext import _message
    ImportError: cannot import name '_message' from 'google.protobuf.pyext' (c:\programdata\anaconda3\lib\site-packages\google\protobuf\pyext\__init__.py)

What does the above command do? Why do I get this error message?

    C:\Windows\system32>python --version
    Python 3.7.1
    
    C:\Windows\system32>pip install protobuf
    Requirement already satisfied: protobuf in c:\programdata\anaconda3\lib\site-packages (3.6.1)
    Requirement already satisfied: six>=1.9 in c:\programdata\anaconda3\lib\site-packages (from protobuf) (1.12.0)
    Requirement already satisfied: setuptools in c:\programdata\anaconda3\lib\site-packages (from protobuf) (40.6.3)

**Comment by nfelt** [comment] 2019-02-21 22:27
Duplicate of #1566 

Please see #1566 for context.

**Closed by nfelt** 2019-02-21 22:27 UTC

**Comment by golfgedamu** [comment] 2019-04-15 07:24
python -mpip install protobuf --upgrade

**Comment by SushanthDC** [comment] 2019-04-22 10:52
When using tensorflow, the ImportError: DLL load failed error, there are many reasons, up from the google.protobuf.pyext import _message error, it should be the protobuf version of the problem,

When tensorflow is automatically installed, protobuf installs the latest version 3.7.1, and there is an incompatibility problem.

Replace with protobuf 3.6.1 (pip install protobuf==3.6.1)
