### ISSUE TITLE
Not show lines in Safari on MacOS 13.3

### ISSUE THREAD

**Issue by leftthomas** [tensorflow/tensorboard#6280] opened 2023-03-30 11:29 UTC
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/9991443/228822304-1bd15afc-b7e4-4de6-92e3-cb1294cca45d.png">

**Comment by arcra** [comment] 2023-03-31 01:06
Hello leftthomas@, it looks like there are only a few data points logged by your experiment. The first step would be to verify that you are indeed logging more data that should be shown in TB.

To further troubleshoot, please run inspection command ([more details](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/backend/event_processing/event_file_inspector.py#L18)):

```
tensorboard --inspect --logdir {your_logdir}
```

and paste the output in this issue. Thanks!

**Comment by arcra** [comment] 2023-03-31 02:23
Ok, thanks for flagging this.

Would you mind sharing:
- Your specific OS and browser versions?
- Do you see any relevant errors in the terminal?
- Any relevant errors in the browser console?

Unfortunately, Safari is supported only on a best-effort basis, so we may not prioritize a fix for this if it's something that requires digging deep or generally a considerable amount of effort, but having any details could help understand what the issue is (and how hard it is to fix).

**Comment by leftthomas** [comment] 2023-03-31 05:09
@arcra My MacOS is 13.3 (22E252), the Safari Version is 16.4 (18615.1.26.11.22), and there are no any error messages in the terminal, and the error messages in the browser console is shown as below:
<img width="968" alt="image" src="https://user-images.githubusercontent.com/9991443/229028398-297387be-2ec7-4165-8f53-63ab1c7c362e.png">

**Comment by bmd3k** [comment] 2023-03-31 11:16
Hi @leftthomas , if you're comfortable doing it, would you mind giving us a stack trace of one of those errors in the console and telling us what value THREE.WEbGLRenderer thinks we are trying to pass as contextType?

Could you also confirm that the problem persists with the latest version of TensorBoard?

It might also be helpful to run diagnose_tensorboard.py as described in our Bug report template and provide the results.

**Comment by leftthomas** [comment] 2023-03-31 11:44
@bmd3k The installed TensorBoard is 2.11.0 by running `conda install tensorboard`, my server can not update the  tensorboard now, so I can not test with the latest version of TensorBoard
I don't know how to obtain the stack trace of one of those errors in the console and the value THREE.WEbGLRenderer thinks we are trying to pass as contextType.
The results by running `diagnose_tensorboard.py` is shown as below:

### Diagnostics

<details>
<summary>Diagnostics output</summary>


--- check: autoidentify
INFO: diagnose_tensorboard.py version 516a2f9433ba4f9c3a4fdb0f89735870eda054a1

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=10, micro=10, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='titan-server', release='5.13.0-30-generic', version='#33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
WARNING: no installation among: ['tb-nightly', 'tensorboard', 'tensorflow-tensorboard']
WARNING: no installation among: ['tensorflow', 'tensorflow-gpu', 'tf-nightly', 'tf-nightly-2.0-preview', 'tf-nightly-gpu', 'tf-nightly-gpu-2.0-preview']
WARNING: no installation among: ['tensorflow-estimator', 'tensorflow-estimator-2.0-preview', 'tf-estimator-nightly']

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.11.0'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "/home/rh/Downloads/a.py", line 528, in main
    suggestions.extend(check())
  File "/home/rh/Downloads/a.py", line 81, in wrapper
    result = fn()
  File "/home/rh/Downloads/a.py", line 284, in tensorflow_python_version
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

--- check: tensorboard_data_server_version
INFO: data server binary: '/software/anaconda3/envs/rh/lib/python3.10/site-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.6.1'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/software/anaconda3/envs/rh/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'titan-server'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=44828969, st_dev=66307, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1679400285, st_mtime=1680227922, st_ctime=1680227922)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/software/anaconda3/envs/rh/lib/python3.10/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py @ file:///croot/absl-py_1666362940888/work
addict==2.4.0
aiohttp @ file:///croot/aiohttp_1670009560265/work
aiosignal @ file:///tmp/build/80754af9/aiosignal_1637843061372/work
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout @ file:///opt/conda/conda-bld/async-timeout_1664876359750/work
attrs @ file:///croot/attrs_1668696182826/work
black==23.1.0
blinker==1.4
Bottleneck @ file:///opt/conda/conda-bld/bottleneck_1657175564434/work
brotlipy==0.7.0
cachetools @ file:///tmp/build/80754af9/cachetools_1619597386817/work
certifi @ file:///croot/certifi_1671487769961/work/certifi
cffi @ file:///croot/cffi_1670423208954/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click @ file:///tmp/build/80754af9/click_1646056706450/work
clip @ git+https://github.com/openai/CLIP.git@a9b1bf5920416aaeaec965c25dd9e8f98c864f16
cloudpickle==2.2.1
colorama==0.4.6
contourpy @ file:///opt/conda/conda-bld/contourpy_1663827406301/work
cryptography @ file:///croot/cryptography_1677533068310/work
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
Cython @ file:///croot/cython_1676568029361/work
detectron2 @ git+https://github.com/facebookresearch/detectron2.git@072713649a9b0069c10aad1aaab819112e8f1e2e
filelock @ file:///croot/filelock_1672387128942/work
flit_core @ file:///croot/flit-core_1679397103445/work/source/flit_core
fonttools==4.25.0
frozenlist @ file:///croot/frozenlist_1670004507010/work
ftfy==6.1.1
fvcore==0.1.5.post20221221
gmpy2 @ file:///tmp/build/80754af9/gmpy2_1645455533097/work
google-auth @ file:///opt/conda/conda-bld/google-auth_1646735974934/work
google-auth-oauthlib @ file:///tmp/build/80754af9/google-auth-oauthlib_1617120569401/work
grpcio @ file:///opt/conda/conda-bld/grpcio_1655801038495/work
huggingface-hub @ file:///croot/huggingface_hub_1667490244076/work
hydra-core==1.3.2
idna @ file:///croot/idna_1666125576474/work
iopath==0.1.9
Jinja2 @ file:///croot/jinja2_1666908132255/work
joblib @ file:///croot/joblib_1666298844297/work
kiwisolver @ file:///croot/kiwisolver_1672387140495/work
Markdown @ file:///croot/markdown_1671541909495/work
markdown-it-py==2.2.0
MarkupSafe @ file:///opt/conda/conda-bld/markupsafe_1654597864307/work
matplotlib @ file:///croot/matplotlib-suite_1679593461707/work
mdurl==0.1.2
mkl-fft==1.3.1
mkl-random @ file:///home/builder/ci_310/mkl_random_1641843545607/work
mkl-service==2.4.0
mmcv-full==1.7.1
mmdet==2.28.2
model-index==0.1.11
mpmath==1.2.1
multidict @ file:///croot/multidict_1665674239670/work
munkres==1.1.4
mypy-extensions==1.0.0
networkx @ file:///croot/networkx_1678964333703/work
numexpr @ file:///croot/numexpr_1668713893690/work
numpy @ file:///croot/numpy_and_numpy_base_1672336185480/work
oauthlib @ file:///croot/oauthlib_1679489621486/work
omegaconf==2.3.0
opencv-python==4.7.0.72
openmim==0.3.7
ordered-set==4.1.0
packaging @ file:///croot/packaging_1678965309396/work
pandas==1.5.3
pathspec==0.11.1
Pillow==9.4.0
pip==23.0.1
platformdirs==3.1.1
pooch @ file:///tmp/build/80754af9/pooch_1623324770023/work
portalocker==2.7.0
protobuf==3.20.3
pyasn1 @ file:///Users/ktietz/demo/mc3/conda-bld/pyasn1_1629708007385/work
pyasn1-modules==0.2.8
pycocotools @ file:///home/conda/feedstock_root/build_artifacts/pycocotools_1667626621281/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
Pygments==2.14.0
PyJWT @ file:///opt/conda/conda-bld/pyjwt_1657544592787/work
pyOpenSSL @ file:///croot/pyopenssl_1677607685877/work
pyparsing @ file:///opt/conda/conda-bld/pyparsing_1661452539315/work
PySocks @ file:///home/builder/ci_310/pysocks_1640793678128/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pytorch-metric-learning @ file:///home/conda/feedstock_root/build_artifacts/pytorch-metric-learning_1677014227549/work
pytz @ file:///croot/pytz_1671697431263/work
PyYAML @ file:///croot/pyyaml_1670514731622/work
regex==2022.10.31
requests @ file:///croot/requests_1678709721434/work
requests-oauthlib==1.3.0
rich==13.3.2
rsa @ file:///tmp/build/80754af9/rsa_1614366226499/work
scikit-learn @ file:///croot/scikit-learn_1676911643119/work
scipy==1.10.0
seaborn @ file:///croot/seaborn_1673479180098/work
setuptools==65.6.3
six @ file:///tmp/build/80754af9/six_1644875935023/work
sympy @ file:///croot/sympy_1668202399572/work
tabulate==0.9.0
tensorboard @ file:///home/builder/mesters/opt/envs/tensorflow/conda-bld/tensorboard_1678126660189/work/tensorboard-2.11.0-py3-none-any.whl
tensorboard-data-server @ file:///croot/tensorboard-data-server_1670853588388/work/tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl
tensorboard-plugin-wit @ file:///home/builder/tkoch/workspace/tensorflow/tensorboard-plugin-wit_1658918494740/work/tensorboard_plugin_wit-1.8.1-py3-none-any.whl
termcolor==2.2.0
terminaltables==3.1.10
threadpoolctl @ file:///Users/ktietz/demo/mc3/conda-bld/threadpoolctl_1629802263681/work
timm @ file:///home/conda/feedstock_root/build_artifacts/timm_1669307383798/work
tomli==2.0.1
torch==2.0.0
torchaudio==2.0.0
torchvision==0.15.0
tqdm @ file:///croot/tqdm_1679561862951/work
triton==2.0.0
typing_extensions @ file:///croot/typing_extensions_1669924550328/work
urllib3 @ file:///croot/urllib3_1673575502006/work
wcwidth==0.2.6
Werkzeug @ file:///croot/werkzeug_1679489717957/work
wheel==0.38.4
yacs==0.1.8
yapf==0.32.0
yarl @ file:///opt/conda/conda-bld/yarl_1661437085904/work



</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

**Comment by Zichen-Wu** [comment] 2023-03-31 16:36
Met the same issue. I think it's Safari's problem because lines are displayed normally when using Edge.

**Comment by arcra** [comment] 2023-03-31 22:41
@leftthomas I think if you just expand the error shown in the browser console by clicking on the small triangle on the left, a more detailed stack trace would show up.

Based on that error message, it seems like there are some issues with WebGL in safari, which is necessary to properly render some visualizations.

I found a few resources where they mention some ways to enable webGL if it's disabled, you can take a look and see if this gets solved:

- http://get.webgl.org/ This one should have a link to troubleshoot for your specific browser.
- https://support.biodigital.com/hc/en-us/articles/218322977-How-to-turn-on-WebGL-in-my-browser This is a website from a totally unrelated product, but they mention how to check if webgl is enabled for a specific site.
- https://github.com/mrdoob/three.js/issues/22582 Similar issue mentioned in another GH repo.

Since this seems to be an issue with safari, there's probably not much we could do even if we cared to prioritize a fix here. I hope these resources help.

**Comment by leftthomas** [comment] 2023-04-01 00:47
@arcra , the stack trace is shown as below:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/9991443/229257290-5ea612b2-2720-47d0-9739-00f2511bc358.png">
and I have tried the solution which you mentioned, but it's not work.

**Comment by Zichen-Wu** [comment] 2023-04-01 12:32
@leftthomas I have solved the issue by disabling WebGL 2.0 in safari->Develop->Experimental Features, maybe it will work for you.

**Comment by leftthomas** [comment] 2023-04-01 15:20
@Zichen-Wu yes, thank you, it's work

**Comment by bmd3k** [comment] 2023-04-04 13:02
Reopening. I upgraded my MacOS and Safari and was able to reproduce.

**Comment by bmd3k** [comment] 2023-04-04 20:27
Something changed in Safari 16.4 that has broken our webgl detection logic [here]( https://cs.opensource.google/tensorflow/tensorboard/+/master:tensorboard/webapp/widgets/line_chart_v2/lib/utils.ts;l=28;drc=f340a5d78afe7b95676fc2f6b4e903640729abe3).

I had assumed that Safari WebGL support for OffscreenCanvas had somehow regressed but thanks to @alicialics comment I'm now realizing that this is possibly due to Safari rolling out limited, incomplete support for webgl.

Whatever the reason, this is what's happening now:
canvas.getContext('webgl2') returns non-null. (This is part of our webgl detection logic)
But new OffscreenCanvas(0, 0).getContext('webgl2') returns null. (this is not part of our webgl detection logic)

The error message that @leftthomas  and others have seen is slightly misleading. three.js is, in fact, at some point, sending the correct context value "webgl2" but because that returns null, ThreeJs tries again with"experimental-webgl2" as a context value and that gives the observed error message (see [here](https://github.com/mrdoob/three.js/blob/88ade6a7726399f363b64117ec143eb4a4756cb0/src/renderers/WebGLRenderer.js#L247)).

**Comment by bmd3k** [comment] 2023-05-02 15:44
I forgot to update here: This was fixed with the TensorFlow 2.12.2 release.

**Closed by bmd3k** 2023-05-02 15:44 UTC
Labels: type:bug, core:frontend, type:browser
