### ISSUE TITLE
Scalars dashboard should hide tags with no selected runs

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#55] opened 2017-06-16 19:21 UTC
MIgrated from https://github.com/tensorflow/tensorflow/issues/7720.

@cancan101 says:

> The list of metrics for for plotting on the scalars tab is cluttered with a number of metrics that don't exist for the selected runs. Why not [hide] these rather than taking up real estate?

**Comment by phisad** [comment] 2018-09-13 12:05
This would be a really helpful feature! In the meantime, is there a workaround regex to have this done?

**Comment by nfelt** [comment] 2018-09-13 17:54
Duplicate of #170

**Comment by nfelt** [comment] 2018-09-13 17:55
I don't believe there's any regex-based workaround, but this issue is something we're actively investigating.

Also, I'm closing this as a duplicate of #170 since they are the same issue, and while this one was filed first, #170 has more overall discussion and context at this point.

**Closed by nfelt** 2018-09-13 17:55 UTC
Labels: plugin:scalars, type:feature
