### ISSUE TITLE
tb-nightly profiler not working with tf-nightly-2.0-preview

### ISSUE THREAD

**Issue by mjlbach** [tensorflow/tensorboard#2541] opened 2019-08-13 03:04 UTC
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 393931f9685bd7e0f3898d7dcdf28819fef54c43

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='node08-ccncluster', release='4.4.0-116-generic', version='#140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '/home/mjlbach/.virtualenvs/physics'

--- check: installed_packages
INFO: installed: tb-nightly==1.15.0a20190806
INFO: installed: tf-nightly-gpu-2.0-preview==2.0.0.dev20190812
INFO: installed: tensorflow-estimator-2.0-preview==1.14.0.dev2019081200

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '1.15.0a20190806'

--- check: tensorflow_python_version
INFO: tensorflow.__version__: '2.0.0-dev20190812'
INFO: tensorflow.__git_version__: 'v1.12.1-8566-g207bd43'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/mjlbach/.virtualenvs/physics/bin/tensorboard\n'

--- check: readable_fqdn
INFO: socket.getfqdn(): 'node08-ccncluster.stanford.edu'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=21763228, st_dev=2049, st_nlink=2, st_uid=1060, st_gid=1060, st_size=4096, st_atime=1565664626, st_mtime=1565664875, st_ctime=1565664875)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/mjlbach/.virtualenvs/physics/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.7.1
astor==0.8.0
backcall==0.1.0
decorator==4.4.0
gast==0.2.2
google-pasta==0.1.7
grpcio==1.22.0
h5py==2.9.0
ipdb==0.12.2
ipython==7.7.0
ipython-genutils==0.2.0
jedi==0.15.1
joblib==0.13.2
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.1.1
numpy==1.17.0
opt-einsum==2.3.2
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
pip==19.2.2
prompt-toolkit==2.0.9
protobuf==3.9.1
psutil==5.6.3
ptyprocess==0.6.0
Pygments==2.4.2
pymongo==3.8.0
pyzmq==18.1.0
scikit-learn==0.21.3
scipy==1.3.1
setuptools==41.0.1
six==1.12.0
sklearn==0.0
tb-nightly==1.15.0a20190806
tensorflow-estimator-2.0-preview==1.14.0.dev2019081200
termcolor==1.1.0
tf-nightly-gpu-2.0-preview==2.0.0.dev20190812
tqdm==4.33.0
traitlets==4.3.2
wcwidth==0.1.7
Werkzeug==0.15.5
wheel==0.33.4
wrapt==1.11.2

``````

</details>

Chrome Version 76.0.3809.100 

## Issue description

Using tf.summary.trace_on(graph=True, profiler=True) and tf.summary.trace_export("Profiling", step=1, profiler_outdir="/home/mjlbach/logs") surrounding any tf.function decorated or eager model yields a blank profile page. The same log works with tensorboard 1.14. 
<img width="1201" alt="Screen Shot 2019-08-12 at 8 01 48 PM" src="https://user-images.githubusercontent.com/13316262/62912255-3ff1a800-bd3c-11e9-938d-0e3858e7945c.png">
<img width="1204" alt="Screen Shot 2019-08-12 at 8 01 57 PM" src="https://user-images.githubusercontent.com/13316262/62912257-3ff1a800-bd3c-11e9-900e-2a6e9cf7e112.png">

**Comment by wchargin** [comment] 2019-08-13 03:49
Hi @mjlbach! Thanks for the clear report. This was previously reported
in #2491 and fixed in #2509, but we haven’t had any nightly releases
since then due to unrelated build failures. We think that we’ve fixed
these (#2539) so tomorrow’s nightly should have the fix, but here’s an
advance copy for you, built from current HEAD (bb17d5f3):

[tensorboard_wheels_20190812_bb17d5f3.tar.gz](https://github.com/tensorflow/tensorboard/files/3495252/tensorboard_wheels_20190812_bb17d5f3.tar.gz)

SHA-256 6b4e3e3c5c626e6f7c88f05653934dafdef8ae08021b987629d2ab10b936aceb

I can repro the bug on `tb-nightly`, and confirm that it’s fixed in the
above build.

Note that this is a package for `tensorboard==1.15.0a0`, so you will
need to first **uninstall** any copies of `tb-nightly` to prevent Pip
from corrupting your installation.

**Comment by wchargin** [comment] 2019-08-13 03:49
Duplicate of #2491

**Closed by wchargin** 2019-08-13 03:49 UTC

**Comment by mjlbach** [comment] 2019-08-13 03:58
@wchargin Thanks! The build you just sent me is working.

**Comment by wchargin** [comment] 2019-08-13 04:36
Great! Glad to hear it.
