### ISSUE TITLE
protbuf upgrade

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorboard#5817] opened 2022-07-22 07:32 UTC
```
tensorboard/compat/proto/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/Users/ljin/miniforge3/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

Everyone else now using protobuf 4.10+, tensorboard have to using 3.19, please upgrade this dependenices....

**Comment by bileschi** [comment] 2022-07-22 15:08
Tracking Issue https://github.com/tensorflow/tensorboard/issues/5708

**Comment by bileschi** [comment] 2022-07-22 15:17
duplicate of #5708

**Comment by nfelt** [comment] 2023-02-09 00:43
See duplicate issue, now closed.

**Closed by nfelt** 2023-02-09 00:43 UTC
