### ISSUE TITLE
Error when running tensorboard 1.3.0

### ISSUE THREAD

**Issue by davidbrai** [tensorflow/tensorboard#231] opened 2017-07-17 05:58 UTC
Hi,
I get this error when I run tensorboard version 1.3.0. I have to downgrade to version 0.1.2 to avoid it.
I have existing summary data that was written using tensorflow 1.1.0

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 316, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 290, in reload_multiplexer
    multiplexer.Reload()
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/event_multiplexer.py", line 189, in Reload
    accumulator.Reload()
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/event_accumulator.py", line 239, in Reload
    self._ProcessEvent(event)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/event_accumulator.py", line 371, in _ProcessEvent
    if value.HasField('metadata'):
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 811, in HasField
    raise ValueError(error_msg % field_name)
ValueError: Protocol message has no non-repeated submessage field "metadata"
```

**Comment by dandelionmane** [comment] 2017-07-17 22:00
This is because tensorboard 1.3.0 depends on TensorFlow 1.3, which isn't released yet. It's an awkward growing pain from switching TensorBoard out into its own repo. For now please keep on using 0.1.2; this should be fixed soon, when TensorFlow 1.3 is released.

**Comment by davidbrai** [comment] 2017-07-18 06:18
OK, thanks for answering!

**Comment by jart** [comment] 2017-07-19 06:34
I've also encountered similar pains with `HasField`. I don't understand why it was designed this way and I'm pretty sure that's not the internal behavior. I was pondering earlier whether or not I should write some type of wrapper function that also calls `hasattr`. That would probably make the behavior more in line with expectations.

**Comment by dandelionmane** [comment] 2017-07-19 23:41
I deleted the tensorflow-tensorboard 1.3 release, pending fixing this issue.

**Closed by dandelionmane** 2017-07-19 23:41 UTC

**Comment by Atlas7** [comment] 2017-10-09 11:24
This is how I have tensorboard working in tensorflow 1.3 (within a conda environment):

Step 1: Create a conda environment (via conda-forge channel), containing Python 3.6 and Tensorflow 1.3

```
conda create --name py36-tf13 python=3.6 tensorflow=1.3
```

Step 2: (at this stage tensorboard doesn't work so) activate the conda environment, and do a `pip install tensorflow-tensorboad`:

```
$ source activate 
$ source activate py36-tf13
$ pip install tensorflow-tensorboad
```
Step 3: Now as if by magic, command like this now work:

```
$ tensorboard --logdir=/tmp/tensorflow/mnist
TensorBoard 0.1.8 at http://xxxxx.local:6006 (Press CTRL+C to quit)
```
