### ISSUE TITLE
Installing tensorboard does not install tensorflow

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorboard#1166] opened 2018-05-02 20:46 UTC
```
$ pip install tensorboard
```
Does not install tensorflow
I am on `tensorboard==1.8.0`.

```
$ tensorboard
Traceback (most recent call last):
  File "/Users/alex/.virtualenvs/tb/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/Users/alex/.virtualenvs/tb/lib/python3.6/site-packages/tensorboard/main.py", line 28, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by nfelt** [comment] 2018-05-02 21:27
Closing since this is by design.  TensorBoard expects you to have a tensorflow installation in the python environment in which you install TensorBoard, but it intentionally doesn't depend on TensorFlow's pip package directly because people install TensorFlow in many different ways (`tensorflow`, `tensorflow-gpu`, from source, etc.).  Note that `tensorflow`/`tensorflow-gpu` also already depend on `tensorboard`, and that's how most users obtain `tensorboard`.

See e.g. https://www.tensorflow.org/programmers_guide/summaries_and_tensorboard#setup

**Closed by nfelt** 2018-05-02 21:27 UTC
