### ISSUE TITLE
Constant scalar curve goes up and down with smoothing

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorboard#918] opened 2018-01-28 17:20 UTC
With a smoothing value of `0.8` (all values are actually 200):

![img](https://user-images.githubusercontent.com/2111293/35484918-71aad440-044f-11e8-9222-682986549581.png)

**Comment by nfelt** [comment] 2018-02-01 06:13
Duplicate of #786 (but thanks for the report).

**Comment by nfelt** [comment] 2018-02-01 06:14
Duplicate of #786 

Re-commenting to trigger the duplicate issue logic

**Comment by nfelt** [comment] 2018-02-01 06:15
Duplicate of #786

**Closed** 2018-02-01 06:15 UTC
Labels: plugin:scalars, type:bug/performance
