### ISSUE TITLE
Tensorboard does not display connections in graph

### ISSUE THREAD

**Issue by nanoix9** [tensorflow/tensorboard#876] opened 2018-01-14 09:12 UTC
I run the example `https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py` and then open tensorboard with `tensorboard --logdir /tmp/tensorflow/mnist/logs/mnist_with_summaries/`. However, the connections are not displayed, only the nodes are shown. I cannot paste image here so please refer to <https://stackoverflow.com/questions/48248143/tensorboard-does-not-display-connections-in-graph>

**Comment by jart** [comment] 2018-01-16 11:46
Probably a duplicate of https://github.com/tensorflow/tensorboard/issues/425. Try `pip install tb-nightly`.

**Closed by jart** 2018-01-16 11:46 UTC

**Comment by nanoix9** [comment] 2018-01-20 03:11
@jart It works, thanks!
