### ISSUE TITLE
Smoothing depends on sequence length

### ISSUE THREAD

**Issue by DmitryUlyanov** [tensorflow/tensorboard#1518] opened 2018-10-16 08:18 UTC
Hi, 

It seems that the smoothing function somehow either peeks into the future or the visualization depends on the number of points in the sequence. Here is an example: 

```python
from tensorboardX import SummaryWriter
import numpy as np 

data = - np.log1p(np.arange(100000)) + np.random.randn(100000)

# First experiment, 100k points
writer = SummaryWriter(log_dir = 'exp1')
for i in range(100000):
    writer.add_scalar(f'test_run/loss', data[i],  i)
    
writer.close()

# Second experiment, first 10k points
writer = SummaryWriter(log_dir = 'exp2')
for i in range(10000):
    writer.add_scalar(f'test_run/loss', data[i],  i)

writer.close()
```

Here is the result with smoothing (0.96 or 0.996 as I recall) : 
![screenshot from 2018-10-16 10-18-57](https://user-images.githubusercontent.com/6727524/46999137-787d2100-d12d-11e8-9f0f-693d8f436029.png)

I guess It is natural to expect plots to be very similar before 10k tick but it does not happen.

I tried to find what is wrong with smoothing, but the smoothing itself does not look wrong. I also noticed that the description at https://github.com/tensorflow/tensorboard/blob/master/tensorboard/components/vz_line_chart/vz-line-chart.ts#L64 is outdated. 

My best guess here is that the discrepancy is there because of subsampling, which is done (presumably) before smoothing.

I used tensorboardX wrapper, but I do not think it causes the problem as it is just a wrapper. 

 - TensorBoard version 1.11.0
 - OS Platform and version Ubuntu 16.04
 - Python version 3.6

**Comment by stephanwlee** [comment] 2018-10-27 01:49
Hi Dmitry, thank you for opening the issue and sorry for taking long to respond.

I looked at it carefully and it looks like smoothing does _not_ differ depending on length of the time series. However, I did identify an issue with current smoothing algo.

Say we have series `x = [1, 2, 3, 4, 5]` and smoothing constant is `w = 0.5`. Like you said, we do subsample the series not only because it is computationally expensive but also there simply isn't enough pixels to show all those data. Anyways, that magic number is currently [1000](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/backend/application.py#L61) but for sake of this example, let's say it is 3.

The major mistake with current algo is that the `t` in `x'_t = (1 - w)x_t + wx'_(t-1)` is index of the series as opposed to the `step`, the unit of x-axis. Let me illustrate with an example.

Using above notations and constants, let's say x is subsampled like this: `x_sub_1 = [1, 2, 5]`. When applying current algorithm:
```latex
x'_0 = (0.5 * 0 + 0.5 * 1) / (1 - 0.5 ^1) = 1
x'_1 = (0.5 * 1 + 0.5 * 2) / (1 - 0.5 ^2) = 2
x'_2 = (0.5 * 2 + 0.5 * 5) / (1 - 0.5 ^3) = 4
```

Instead, if `x_sub_2 = [1, 4, 5]`:
```latex
x'_0 = (0.5 * 0 + 0.5 * 1) / (1 - 0.5 ^1) = 1
x'_1 = (0.5 * 1 + 0.5 * 4) / (1 - 0.5 ^2) = 3.333
x'_2 = (0.5 * 3.33 + 0.5 * 5) / (1 - 0.5 ^3) = ~4.762
```

Do note that although the second element in `x'` is written as `x'_1`, for the first example, it will be plotted for step=2 whereas the second example will be positioned on `step=4`. Between these points, there will be a linear interpolation. It roughly looks like this (blue = `x_sub_1` and green = `x_sub_2`):
![image](https://user-images.githubusercontent.com/2547313/47598270-9c6f0c80-d94e-11e8-90bb-f0711987bb66.png)

In your case, the problem is quite exacerbated due to magnitude of the noise with respect to the true negative log. Of course, if you change number of data to <= 1000, you will notice that exp1 and exp2 display exactly on top of each other.

Now, this is not saying our smoothing is correct or visually pleasing. We have yet to find the perfect smoothing algo and we will have to spend some time pondering about it. Sorry about this :(

**Comment by spitis** [comment] 2019-05-16 15:40
Just use a simple moving average? Or offer multiple smoothing functions. This is a serious bug.

**Comment by wchargin** [comment] 2019-05-16 17:36
Thanks for the report, and thanks @stephanwlee for the explanation. It
looks like this is indeed an artifact of the reservoir sampling (which
_does_ sample uniformly, but does not sample linearly). I can reproduce
it with the following code:

```python
import tensorflow as tf
import numpy as np

data = -np.log1p(np.arange(10000)) + np.random.randn(10000)

with tf.summary.create_file_writer("exp1").as_default():
  for i in range(10000):
    tf.summary.scalar("loss", data[i], step=i)

with tf.summary.create_file_writer("exp2").as_default():
  for i in range(1000):
    tf.summary.scalar("loss", data[i], step=i)
```

When passing `--samples_per_plugin=scalars=10000`, the divergence
disappears.

Our [general policy with issues about the smoothing algorithm][1] is the
following:

> It seems that every change in the smoothing algorithm results in new
> tradeoffs and biases, and new requests to change the algorithm. At
> this point it's not a priority for the team, so just filing an issue
> probably won't directly result in changes. However, the smoothing
> algorithm is actually a very simple piece of code to change. If you
> come up with a new algorithm, and demonstrate persuasively why it is
> an improvement over the current one (taking into account new biases
> and edge cases that it introduces), I'll happily merge it.

[1]: https://github.com/tensorflow/tensorboard/issues/610#issuecomment-334380578

(And yes, we’ve tried simple moving averages before.)

I’m going to close this issue accordingly. If you’d like to take a stab
at improving the current smoothing algorithm, please see #639 for a good
example of how to compare behavior and discuss trade-offs. Thanks!

**Closed by wchargin** 2019-05-16 17:36 UTC
