### ISSUE TITLE
Compute Time incorrectly summed up

### ISSUE THREAD

**Issue by nikita68** [tensorflow/tensorboard#1776] opened 2019-01-22 12:12 UTC
Hey,

I've noticed that the compute time for some operators is (much) larger than the sum of the individual operators. [ I posted the same issues a few days ago on stackoverflow but got no response.](https://stackoverflow.com/questions/54278295/tensorboard-compute-time-incorrectly-summed-up)/

Group time is 10 seconds.
![Group Time](https://i.imgur.com/E3kF34m.png)

Individual operations ~50 microseconds each (6 operations together).
![Individual](https://i.imgur.com/riOCAWi.png)

As you can see, the individual ops summed together are much less that the group time shown.

Some background info:
- Tensorflow 1.12
- Tensorboard 1.12.2
- Ubuntu 18.04
- Python 3.6

Thanks!

**Comment by nfelt** [comment] 2019-01-24 00:53
I suspect that rather than a bug in TensorBoard (in displaying the compute time) this is instead an artifact of how the compute time is being recorded by whatever you're using to generate the profiling stats.  E.g. it may that the profiling logic is buggy, or just that there's some overhead that isn't being represented in the collected stats.

If you think this is a TensorBoard bug, could you provide simple instructions and/or data files that reproduce the issue?

**Comment by nikita68** [comment] 2019-01-25 14:58
Could be, though it is quite important for us to know the exact position where the performance performs dips. [Here is a zip of all the data that I used for tensorboard.](https://www.dropbox.com/s/0n4407hcjr5pp6u/train-2019-01-20-15-25-05.zip?dl=0) It just needs to be opened as usual with tensorboard (and any trace selected. The issues can be seen in the "output" layer which is under the "Auxillary" part. I'll gladly provide any other info which is needed.

**Comment by jameswex** [comment] 2019-01-25 18:01
For these rolled-up metanodes in the graph, we could change the label to be something like "start to end compute time" or something similar. By design for metanodes the time shown is from first event start to last event end.

**Comment by hgadig** [comment] 2019-03-25 17:34
Closing as this is in "awaiting response" state for more than a week. Feel free to add your comments(if any), we will reopen. Thanks!

**Closed by hgadig** 2019-03-25 17:34 UTC
Labels: plugin:graph, plugin:graph:profile, stat:awaiting response
