### ISSUE TITLE
Option to have TensorBoard be able to run on AI Platform notebook or other notebook services

### ISSUE THREAD

**Issue by tarrade** [tensorflow/tensorboard#3408] opened 2020-03-21 09:45 UTC
Today we cannot run TensorBoard on a AI Platform notebook on a native way (it may already exist few tricks to fix the issue).
![image](https://user-images.githubusercontent.com/12021701/77222862-7eafd200-6b57-11ea-95bd-3a60880bd358.png)

I was told by the GCP AI Platform notebook team that this scenario is not supported because TensorBoard widget is trying to do port forwarding under the hood and the AI Platform notebook proxy prevents it from connecting to non-HTTPS ports.

It will be great to be use TensorBoard on AI Platform notebook or any kind of other services in a native way and secure way (something that could also work with corporate proxy). I don't have the know to build such solution but I can help in the testing phase both on AI Platform notebook (GCP) and with corporate proxy (TLS interception).

**Comment by rmothukuru** [comment] 2020-03-23 06:49
@tarrade,
Can you please confirm if this issue can be considered duplicate of the issue, #3152. Thanks!

**Comment by tarrade** [comment] 2020-03-23 06:55
@rmothukuru this ticket is suppose to be a feature request to solve the issue #3152. You can close this feature request if you think the issue is good enough.

**Comment by rmothukuru** [comment] 2020-03-26 09:29
Closing this issue as it is already being tracked in #3152. Thanks!

**Closed** 2020-03-26 09:30 UTC
Labels: core:backend, core:frontend, stat:awaiting response, type:bug
