### ISSUE TITLE
Scalar plot hover popover is shown outside of the browser window

### ISSUE THREAD

**Issue by darthdeus** [tensorflow/tensorboard#1770] opened 2019-01-18 14:47 UTC
- **TensorBoard version (from pip package, also printed out when running `tensorboard`)**: tensorboard==1.12.2
 - **TensorFlow version if different from TensorBoard**: 1.12.0
 - **OS Platform and version (e.g., Linux Ubuntu 16.04)**: macOS 10.13.6
 - **Python version (e.g. 2.7, 3.5)**: 3.6.7
 - For browser-related issues:
   - **Browser type and version (e.g. Chrome 64.0.3282.140):** Chrome 71.0.3578.98 (Official Build) (64-bit)
   - Screenshot if it's a visual issue
 
Hover on scalar plots sometimes shows the popover outside the visible window in the browser, with no way to view it. The page does not scroll further down any more than shown in the screenshot.

Zooming on the plot sometimes causes the results to show above the plot. This seems to happen when the number of traces goes below 25-26.

<img width="1011" alt="screen shot 2019-01-18 at 15 39 54" src="https://user-images.githubusercontent.com/123374/51393361-ca23b600-1b37-11e9-8852-026ef56f88a0.png">

**Comment by nfelt** [comment] 2019-01-24 00:48
Duplicate of #1019

**Comment by nfelt** [comment] 2019-01-24 00:49
This is best resolved by #1019 to make it possible to interact with the tooltip table, so that you can scroll over if in cases when it's not fully visible.

**Closed by nfelt** 2019-01-24 00:49 UTC
Labels: core:frontend, plugin:scalars
