### ISSUE TITLE
Tensorboar + “TypeError: GetNext() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by lahmeri** [tensorflow/tensorboard#1346] opened 2018-08-09 10:30 UTC
- TensorBoard version (from pip package, also printed out when running `tensorboard`) **1.5.1**
 - TensorFlow version if different from TensorBoard **1.9.1**
 - OS Platform and version (e.g., Linux Ubuntu 16.04)**Linux 18.04**
 - Python version (e.g. 2.7, 3.5)**python 3**

 **I am training a model using ssd_mobilenet_v1_pets config  file (i have a duplication in the log)** 

INFO:tensorflow:global step 4035: loss = 3.9596 (1.164 sec/step)
INFO:tensorflow:global step 4041: loss = 7.2948 (1.149 sec/step)
INFO:tensorflow:global step 4042: loss = 3.6689 (1.203 sec/step)
INFO:tensorflow:global step 4042: loss = 3.6689 (1.203 sec/step)
INFO:tensorflow:global step 4043: loss = 4.6037 (1.191 sec/step)
INFO:tensorflow:global step 4043: loss = 4.6037 (1.191 sec/step)
INFO:tensorflow:global step 4044: loss = 6.1542 (1.205 sec/step)
INFO:tensorflow:global step 4044: loss = 6.1542 (1.205 sec/step)
INFO:tensorflow:global step 4045: loss = 2.7412 (1.224 sec/step)
INFO:tensorflow:global step 4045: loss = 2.7412 (1.224 sec/step)
INFO:tensorflow:global step 4046: loss = 4.6169 (1.200 sec/step)
INFO:tensorflow:global step 4046: loss = 4.6169 (1.200 sec/step)
INFO:tensorflow:global step 4047: loss = 4.3726 (1.192 sec/step)
INFO:tensorflow:global step 4047: loss = 4.3726 (1.192 sec/step)

**when I run the command :~/models/research/object_detection$ tensorboard --logdir='training'**

i get 
![stack_overflow](https://user-images.githubusercontent.com/36934662/43891444-3543e848-9bc1-11e8-87fd-8852d4bfd6aa.png)
**And the log is showing** 
/home/amine/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Exception in thread Reloader:
Traceback (most recent call last):
  File "/home/amine/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/amine/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/application.py", line 361, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/application.py", line 335, in reload_multiplexer
    multiplexer.Reload()
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 195, in Reload
    accumulator.Reload()
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 185, in Reload
    for event in self._generator.Load():
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 88, in Load
    for event in self._LoadInternal():
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 112, in _LoadInternal
    for event in self._loader.Load():
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 53, in Load
    self._reader.GetNext(status)
TypeError: GetNext() takes 1 positional argument but 2 were given

**Here 's some details find 'training' | grep tfevents**

training/events.out.tfevents.1533746027.amine-Inspiron-3537
training/events.out.tfevents.1533804666.amine-Inspiron-3537
training/events.out.tfevents.1533803319.amine-Inspiron-3537
training/events.out.tfevents.1533731370.amine-Inspiron-3537
training/events.out.tfevents.1533739117.amine-Inspiron-3537
training/events.out.tfevents.1533804542.amine-Inspiron-3537
training/events.out.tfevents.1533732199.amine-Inspiron-3537
training/events.out.tfevents.1533738206.amine-Inspiron-3537
training/events.out.tfevents.1533803963.amine-Inspiron-3537

**tensorboard --inspect --logdir 'training'**/home/amine/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Exception in thread Reloader:
Traceback (most recent call last):
  File "/home/amine/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/amine/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/application.py", line 361, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/application.py", line 335, in reload_multiplexer
    multiplexer.Reload()
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 195, in Reload
    accumulator.Reload()
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 185, in Reload
    for event in self._generator.Load():
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 88, in Load
    for event in self._LoadInternal():
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/event_processing/directory_watcher.py", line 112, in _LoadInternal
    for event in self._loader.Load():
  File "/home/amine/anaconda3/lib/python3.6/site-packages/tensorboard/backend/event_processing/event_file_loader.py", line 53, in Load
    self._reader.GetNext(status)
TypeError: GetNext() takes 1 positional argument but 2 were given

TensorBoard 1.5.1 at http://amine-Inspiron-3537:6006 (Press CTRL+C to quit)

**Comment by nfelt** [comment] 2018-08-09 19:10
Duplicate of #1111

**Comment by nfelt** [comment] 2018-08-09 19:12
Please install TensorBoard 1.8 or higher.  In general, it's best to keep TensorBoard and TensorFlow on the same minor version (e.g. version 1.x for both with x being the same) to avoid compatibility issues.

**Closed by nfelt** 2018-08-09 19:12 UTC
