### ISSUE TITLE
How to run already exist “events” from “logs” for Tensorboard in Google Colaboratory?

### ISSUE THREAD

**Issue by alla15747** [tensorflow/tensorboard#2167] opened 2019-04-28 22:20 UTC
I have run a code for a Deep Generative model. And the code generates logs, checkpoints, and events files for Tensorboard:

Example of what shown in the files " Google Colab:

folder: content

.............experiments

.................mnist-experiment

........................checkpoints

........................logs

............................events.out.tfevents.15454....

I want to run the event file "events.out.tfevents.15454...." on Tensorboard in Colab and see the results their.

I tried this code:

 # You can change the directory name
 LOG_DIR = 'tb_logs'

 !wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
 !unzip ngrok-stable-linux-amd64.zip

 import os
 if not os.path.exists(LOG_DIR):
 os.makedirs(LOG_DIR)

 get_ipython().system_raw(
 'tensorboard --logdir {} --host 0.0.0.0 --port 6006 &'
 .format(LOG_DIR))

 get_ipython().system_raw('./ngrok http 6006 &')

 !curl -s http://localhost:4040/api/tunnels | python3 -c \
 "import sys, json; print(json.load(sys.stdin)['tunnels'][0] 
 ['public_url'])"
The code opens : inflating: ngrok
https://0f1795c4.ngrok.io

However, it's empty. Nothing is shown in the Tensorboard What's missing to run the event file shown in the directory?

**Comment by rmothukuru** [comment] 2019-04-29 11:47
@alla15747 ,
Can you please provide the information of the Browser you are using?

**Comment by alla15747** [comment] 2019-04-29 12:57
@rmothukuru 
Thanks for your responding. my browser is Google chrome.

**Comment by wchargin** [comment] 2019-04-29 16:50
Hi @alla15747! You can run TensorBoard directly within Colab without
needing to configure ngrok or set up any tunnels at all. We have a
tutorial on how to do that here:

<https://www.tensorflow.org/tensorboard/r2/tensorboard_in_notebooks>

For a quick summary:

 1. Make sure that you’re on the latest version of TensorFlow, either
    the stable branch or the TF 2.0 preview:

    ```
    # Either:
    !pip install -qU tf-nightly  # for stable branch
    # Or:
    !pip install -qU tf-nightly-2.0-preview  # for TF 2.0 preview
    ```

 2. Load the TensorBoard notebook extensions:
 
    ```
    %load_ext tensorboard
    ```

 3. Invoke TensorBoard starting with a `%`-sign:

    ```
    %tensorboard --logdir {LOG_DIR}
    ```

    You don’t need to specify port or host; this will be determined
    automatically.

Please let us know whether this works for you.

**Comment by alla15747** [comment] 2019-04-30 07:05
Hi William, 
Thanks for your time and answer.

Unfortunately, it is not working. 

**To rephrase my question:**
First, I'm using Tensorflow and keras. 
The event file already created in the content **colab** after I trained my neural network.
Now, simply, I just want to read the event file has been created in tensorboard. 

Thank you!

**Comment by wchargin** [comment] 2019-05-02 00:50
The workflow that I described works with TensorFlow and Keras, and works
just fine with event files that have already been created in Colab. Your
use case is basically exactly what this functionality is for.

You say, “Unfortunately, it is not working”. What’s not working? How?

**Comment by IIIBlueberry** [comment] 2019-05-02 09:18
> 
> 
> The workflow that I described works with TensorFlow and Keras, and works
> just fine with event files that have already been created in Colab. Your
> use case is basically exactly what this functionality is for.
> 
> You say, “Unfortunately, it is not working”. What’s not working? How?


I tried the demo link
https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/r2/tensorboard_in_notebooks.ipynb
but then i executing '%tensorboard --logdir logs' tensorboard does not show up

**Comment by wchargin** [comment] 2019-05-02 17:22
In Firefox, you may need to [explicitly enable service workers][1]:

> **Firefox Nightly:** Go to `about:config` and set
> `dom.serviceWorkers.enabled` to true; restart browser.

In my testing, this also works in Firefox 60.6.1esr (no nightly needed).

We’ll add this to the documentation. Thanks for bringing it to our
attention.

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Setting_up_to_play_with_service_workers

**Comment by IIIBlueberry** [comment] 2019-05-02 22:46
> 
> 
> In Firefox, you may need to [explicitly enable service workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Setting_up_to_play_with_service_workers):
> 
> > **Firefox Nightly:** Go to `about:config` and set
> > `dom.serviceWorkers.enabled` to true; restart browser.
> 
> In my testing, this also works in Firefox 60.6.1esr (no nightly needed).
> 
> We’ll add this to the documentation. Thanks for bringing it to our
> attention.


But, 'dom.serviceWorkers.enabled' is already default to true on my firefox 66.0.3

**Comment by JesminNipu** [comment] 2020-02-01 19:45
> Hi @alla15747! You can run TensorBoard directly within Colab without
> needing to configure ngrok or set up any tunnels at all. We have a
> tutorial on how to do that here:
> 
> https://www.tensorflow.org/tensorboard/r2/tensorboard_in_notebooks
> 
> For a quick summary:
> 
> 1. Make sure that you’re on the latest version of TensorFlow, either
>    the stable branch or the TF 2.0 preview:
>    ```
>    # Either:
>    !pip install -qU tf-nightly  # for stable branch
>    # Or:
>    !pip install -qU tf-nightly-2.0-preview  # for TF 2.0 preview
>    ```
> 2. Load the TensorBoard notebook extensions:
>    ```
>    %load_ext tensorboard
>    ```
> 3. Invoke TensorBoard starting with a `%`-sign:
>    ```
>    %tensorboard --logdir {LOG_DIR}
>    ```
>    
>    
>    You don’t need to specify port or host; this will be determined
>    automatically.
> 
> Please let us know whether this works for you.

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 59, in run_main
    default.get_plugins() + default.get_dynamic_plugins(),
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/default.py", line 115, in get_dynamic_plugins
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/default.py", line 115, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points('tensorboard_plugins')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (grpcio 1.15.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('grpcio>=1.24.3'))

**Comment by wchargin** [comment] 2020-02-02 06:46
@JesminNipu: What you have posted seems unrelated to this issue. It’s a
Python package version conflict, which I can’t reproduce on current
Colab, and which is not related to service workers. If you continue to
experience this issue, please open a new issue and follow the
instructions in the issue template:
<https://github.com/tensorflow/tensorboard/issues/new/choose>

**Comment by sanatmpa1** [comment] 2021-12-30 07:04
@alla15747,

We are checking to see if this is still an issue. Can you try using `tensorboard --inspect --event_file=myevents.out` and let us know if that's what you're looking for?. Also you can refer this [link](https://stackoverflow.com/a/37306050/11530462) for a detailed answer. Thanks!

**Comment by sanatmpa1** [comment] 2022-01-13 18:19
@alla15747,

Closing this issue due to recent activity. Please reopen the issue if it still persists. Thanks!

**Closed by sanatmpa1** 2022-01-13 18:19 UTC
Labels: type:support, stat:awaiting response
