### ISSUE TITLE
Tensorboard doesn't show data when logs on different drive

### ISSUE THREAD

**Issue by jabacrack** [tensorflow/tensorboard#128] opened 2017-06-22 16:16 UTC
I have tensorflow 1.2.0 installed in windows 10 miniconda in separated env (with name tensorflow). Miniconda installed to folder C:\Miniconda2.

Steps to reproduce

1. You have two disks  C: and D:
2. Run some tensorflow example that store logs to D:\train1
3. Run anaconda promt
4. Activate env tensorflow
5. Run tensorboard
`tensorboard --logdir=d:\train1`
6. It run from folder "c:\Miniconda2\envs\tensorflow\"
7. Go to 127.0.0.1:6006 in browser - tensorboard loaded but doesn't contain any data
8. Stop tensorboard
9. Change active disk in console to D:
10. Run tensorboard
`tensorboard --logdir=d:\train1`
11. Go to 127.0.0.1:6006 in browser - you see your data

I think this bug connected with https://github.com/tensorflow/tensorflow/issues/9701

**Comment by dandelionmane** [comment] 2017-06-22 18:11
Duplicate of https://github.com/tensorflow/tensorboard/issues/52

**Closed by dandelionmane** 2017-06-22 18:11 UTC
