### ISSUE TITLE
[Feature Request] Add time series summary.

### ISSUE THREAD

**Issue by ElPiloto** [tensorflow/tensorboard#1866] opened 2019-02-19 12:06 UTC
Would it be possible to co-opt some of the internal functionality from `tf.summary.histogram` to display time series information under a different summary type (maybe `tf.summary.timeseries`?  The x-axis would index time and the y-axis would contain the corresponding value to plot at that time.  This is essentially similar to this [request](https://github.com/tensorflow/tensorboard/issues/900), except it wouldn't overload the existing `tf.summary.histogram` function and instead would have its own entry point a.k.a. `tf.summary.timeseries`.

**Comment by nfelt** [comment] 2019-02-21 22:13
Duplicate of #900

I think this is similar enough to https://github.com/tensorflow/tensorboard/issues/900 (as you mentioned) that it makes sense to just track it there - I'll broaden the scope of that issue accordingly.

**Closed** 2019-02-21 22:14 UTC
Labels: core:summaries, plugin:histogram, type:feature
