### ISSUE TITLE
tensorboard support multiple users at one time 

### ISSUE THREAD

**Issue by TK-blost** [tensorflow/tensorboard#243] opened 2017-07-20 06:43 UTC
does tensorboard support multiple users for different dirs at one time? 
i have this demand,  is it vary difficult to achieve?

**Comment by weberxie** [comment] 2017-07-20 07:35
I also have this need.Is there any plan in this area?

**Comment by weberxie** [comment] 2017-07-20 08:11
sorry, https://github.com/tensorflow/tensorboard/issues/92 seems to be solving the problem.

**Comment by dandelionmane** [comment] 2017-07-21 00:24
Closing as a duplicate of #92. You can make specific feature requests there :)

**Closed by dandelionmane** 2017-07-21 00:24 UTC

**Comment by kd303** [comment] 2022-08-12 06:52
and 92 is closed, so is this issue :) 

Funny how things work. An actual design document from some aspects of #92 to open things up for community would be great! I wish someone takes up this project, where all interested parties can contribute.
