### ISSUE TITLE
create_summary_metadata TypeError: Value must be iterable

### ISSUE THREAD

**Issue by sizhky** [tensorflow/tensorboard#1209] opened 2018-05-24 05:29 UTC
Hello,

I've been getting this problem when I run tensorboard. I tried reinstalling and it is of no use...

Details:
Version: 1.8.0
TF Version: 1.3.0-rc0
CPE OS Name: cpe:/o:centos:centos:7            
Kernel: Linux 3.10.0-327.el7.x86_64      
Architecture: x86-64
Python: 2.7

```tensorboard --logdir runs --port 6008
2018-05-24 10:55:57.322194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties:
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:82:00.0
Total memory: 10.91GiB
Free memory: 80.38MiB
2018-05-24 10:55:57.322291: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 02018-05-24 10:55:57.322306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y2018-05-24 10:55:57.322322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:82:00.0)Exception in thread Reloader:Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yeshwanth/.local/lib/python2.7/site-packages/tensorboard/backend/application.py", line 362, in _reload_forever
    reload_multiplexer(multiplexer, path_to_run)
  File "/home/yeshwanth/.local/lib/python2.7/site-packages/tensorboard/backend/application.py", line 336, in reload_multiplexer
    multiplexer.Reload()
  File "/home/yeshwanth/.local/lib/python2.7/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 195, in Reload
    accumulator.Reload()
  File "/home/yeshwanth/.local/lib/python2.7/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 186, in Reload
    self._ProcessEvent(event)
  File "/home/yeshwanth/.local/lib/python2.7/site-packages/tensorboard/backend/event_processing/plugin_event_accumulator.py", line 332, in _ProcessEvent
    value = data_compat.migrate_value(value)
  File "/home/yeshwanth/.local/lib/python2.7/site-packages/tensorboard/data_compat.py", line 57, in migrate_value
    return handler(value) if handler else value
  File "/home/yeshwanth/.local/lib/python2.7/site-packages/tensorboard/data_compat.py", line 109, in _migrate_scalar_value
    description=value.metadata.summary_description)
  File "/home/yeshwanth/.local/lib/python2.7/site-packages/tensorboard/plugins/scalar/metadata.py", line 45, in create_summary_metadata
    content=content.SerializeToString()))
TypeError: Value must be iterable```

**Comment by sizhky** [comment] 2018-05-24 05:31
Above error occurs when I run `tensorboard --logdir runs` in linux

**Comment by nfelt** [comment] 2018-05-24 06:01
Please fill out the issue template that is shown at https://github.com/tensorflow/tensorboard/issues/new.

**Comment by sizhky** [comment] 2018-05-24 14:13
@nfelt I've edited my question so as to have the version details.

**Comment by nfelt** [comment] 2018-05-24 21:43
Duplicate of #635

@sizhky this appears to be a known issue if your TF version is sufficiently old.  Perhaps you can update it to TF 1.4.0 or greater.

**Closed by nfelt** 2018-05-24 21:43 UTC
Labels: stat:awaiting response

**Comment by sizhky** [comment] 2018-05-25 12:04
@nfelt - I have updated it but still I get nothing in the web-page. My logdir has tfevents file but I get a blank screen in localhost:6006

**Comment by nfelt** [comment] 2018-05-25 22:15
That's not enough information to be able to assist you.  At a minimum I would need to know what you mean by "blank screen" - i.e. a screenshot, plus the output of the developer tools network and JS console panels, and what browser version you're using.

It would also be useful if you could provide the exact command line you're running, any output from the command, and the tfevents file that you're attempting to read.

**Comment by nfelt** [comment] 2018-05-26 08:35
The attached eventlog is only 160 bytes and is corrupted - it's not in valid TensorFlow records format, and seems to contain a raw error message from matplotlib:

```
$ hd events.out.tfevents.1527247129.gpu2
00000000  09 00 00 00 00 00 00 00  37 f9 71 39 09 bd 56 4d  |........7.q9..VM|
00000010  46 fc c1 d6 41 7c 36 97  1f 57 41 52 4e 49 4e 47  |F...A|6..WARNING|
00000020  3a 6d 61 74 70 6c 6f 74  6c 69 62 2e 69 6d 61 67  |:matplotlib.imag|
00000030  65 3a 43 6c 69 70 70 69  6e 67 20 69 6e 70 75 74  |e:Clipping input|
00000040  20 64 61 74 61 20 74 6f  20 74 68 65 20 76 61 6c  | data to the val|
00000050  69 64 20 72 61 6e 67 65  20 66 6f 72 20 69 6d 73  |id range for ims|
00000060  68 6f 77 20 77 69 74 68  20 52 47 42 20 64 61 74  |how with RGB dat|
00000070  61 20 28 5b 30 2e 2e 31  5d 20 66 6f 72 20 66 6c  |a ([0..1] for fl|
00000080  6f 61 74 73 20 6f 72 20  5b 30 2e 2e 32 35 35 5d  |oats or [0..255]|
00000090  20 66 6f 72 20 69 6e 74  65 67 65 72 73 29 2e 0a  | for integers)..|
000000a0
```

I expect that's why TensorBoard isn't loading.
