### ISSUE TITLE
Support glob or regex patterns for the --logdir flag

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorboard#1365] opened 2018-08-19 12:27 UTC
Currently, it can be difficult to use TensorBoard with many experiments:

- Ideally, I would just point TensorBoard to my root log directory. Then I could filter different sets of experiments by regex via the UI. However, TensorBoard becomes unusably slow for more than about a hundred runs. While this would be great to solve in the long term, I assume there is no easy fix here.
- One workaround is to manually select the sub directories that match a certain regex and pass them as a list to TensorBoard. The problem is that every time I start a new experiment that matches the pattern, I need to restart TensorBoard to include the new experiment.
- Grouping each set of experiments I want to compare into a separate sub directory is not possible, because the sets of experiments we need to compare overlap. Copying the log directory into multiple places is not tractable while experiments are running and symlinks are not available for CNS.

It would be extremely useful if TensorBoard supported glob or regex patterns for the `--logdir` argument on the command line. This way, one could start TensorBoard instances for a certain subset of experiments and later experiments matching the pattern would be included.

I think this is a relatively small change, that would make TensorBoard a lot more useful for analyzing many experiments.

**Comment by stephanwlee** [comment] 2018-08-20 16:11
Hi Danijar, thanks for opening the issue. About the last bullet point: `Grouping each set of experiments...`, would symlink work? That sounds a lot cleaner and is a quick work around.

**Comment by danijar** [comment] 2018-08-20 18:54
> [...] and symlinks are not available for CNS.

**Comment by nfelt** [comment] 2018-08-21 17:26
Duplicate of #1221

**Comment by nfelt** [comment] 2018-08-21 17:31
I'll close this since we already have #1221 open for this, but I've copied your comment over and will respond there to keep the discussion in one place.

**Closed by nfelt** 2018-08-21 17:31 UTC
Labels: core:backend
