### ISSUE TITLE
Removing name scope bug

### ISSUE THREAD

**Issue by ShoufaChen** [tensorflow/tensorboard#1295] opened 2018-07-18 08:54 UTC
just take this [mnist](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py#L92) for example:

in fact, under the `name_scope` context, the explicitly specify the summary name will still equipped with the `name_scope` prefix, i.e,  the so called `Remove 'tower_[0-9]/' from the name` doesn't work actually.

Also pointed at  [tf summary name not work](https://stackoverflow.com/questions/51382616/tf-summary-name-not-work)  and [removeing name scope](https://stackoverflow.com/questions/43814466/tensorflow-removing-name-scope-when-plotting-summary)

**Comment by nfelt** [comment] 2018-07-20 21:52
Yes, I don't think that logic works - it's possible that it worked pre-TF-1.0, but since TF 1.0 the name scoping is baked into the summary tag name.

We do have an open issue requesting that we allow a way to manually override the tag name in TensorBoard: #59.  Since that feature would resolve your issue, I'm going to go ahead and mark this issue as a duplicate of that one.

**Comment by nfelt** [comment] 2018-07-20 21:52
Duplicate of #59

**Closed by nfelt** 2018-07-20 21:52 UTC
