### ISSUE TITLE
Invalid format string in tensorboard 1.13.0

### ISSUE THREAD

**Issue by BelieveOP5** [tensorflow/tensorboard#1917] opened 2019-02-28 03:06 UTC
![image](https://user-images.githubusercontent.com/16416594/53538502-e0fef480-3b48-11e9-8436-9622fc6bfe80.png)

- TensorBoard version 1.13.0
 - TensorFlow version 1.13.1
 - OS Platform and version Windows 10 v1809
 - Python version 3.6.6

**Comment by nfelt** [comment] 2019-02-28 03:12
Duplicate of #1895

**Comment by nfelt** [comment] 2019-02-28 03:13
Please see #1895; this will be fixed in the next release.

**Closed by nfelt** 2019-02-28 03:12 UTC

**Comment by BelieveOP5** [comment] 2019-02-28 10:45
> 
> 
> Please see #1895; this will be fixed in the next release.

thanks, i find it.
