### ISSUE TITLE
tensorboard does not load new data from events file which was synced from another server via rsync

### ISSUE THREAD

**Issue by tt-leader** [tensorflow/tensorboard#1344] opened 2018-08-09 06:20 UTC
- TensorBoard version: 1.8.0
 - TensorFlow version if different from TensorBoard: 1.8.0
 - OS Platform and version: Linux Ubuntu 14.04
 - Python version: 3.5
 - Browser type and version: Chrome 68.0.3440.84

I use [lsyncd](https://github.com/axkibe/lsyncd) (similar to rsync+inotify) to sync `events` files from one server (which is running model evaluation) to another server (which is running tensorboard). I'm sure the `events` files was synced normally, however, tensorboard cannot refresh the front end when new `events` files arrived. 

It seems that tensorboard does not noticed my `events` file has been replaced with the new one. What can I do except for restarting tensorboard?

**Comment by nfelt** [comment] 2018-08-09 19:29
This sounds like the same underlying issue as #349.  The user there was able to work around this by using rsync's `--inplace` option.  It looks like lsyncd may support that as well:
https://github.com/axkibe/lsyncd/blob/a26eb6f94a95ded4120957cf8bfb0743c31ec5bf/ChangeLog#L73

Could you give that a try?  At some point we may add the ability for TensorBoard to detect when the file it's reading from has been replaced but it's a little tricky to get that right and also adds overhead to the use case where the file isn't moved, so we aren't sure this is something we're going to support.

**Comment by tt-leader** [comment] 2018-08-10 01:33
@nfelt Thanks for your advice. `rsync`'s `--inplace` option work well in this situation.

**Comment by nfelt** [comment] 2018-08-22 17:38
Duplicate of #349

**Comment by nfelt** [comment] 2018-08-22 17:38
I've re-opened #349 so I'm closing this as a duplicate of that one - please follow along there.

**Closed by nfelt** 2018-08-22 17:38 UTC
Labels: core:backend
