### ISSUE TITLE
Cannot see 'hello world' dynamic plugin in TB

### ISSUE THREAD

**Issue by ceevee830** [tensorflow/tensorboard#2533] opened 2019-08-09 21:17 UTC
Used as reference:
https://github.com/tensorflow/tensorboard/tree/master/tensorboard/examples/plugins/example_basic

**Problem**: I cannot get the hello world plugin to display in TB.

**Corrective Action**: TBD.  Please help.

Here are the steps and sub-steps performed to display the new 'hello world dynamic plugin'.

1. Remove our TB
* Launch our internal TF docker
* pip uninstall tensorboard   (<--- this uninstalls our TB)

2. Install nightly TB
* Download 'tb_nightly-1.15.0a20190806-py3-none-any.whl' from https://pypi.org/project/tb-nightly/#files
* pip install tb_nightly-1.15.0a20190806-py3-none-any.whl
* pip list  (I see 'tb-nightly                 1.15.0a20190806')

3. Get plugin source
* (from https://github.com/tensorflow/tensorboard/tree/master/tensorboard/examples/plugins/example_basic
* git clone https://github.com/tensorflow/tensorboard.git
* mkdir -p /dynamic_plugin
* cp -r tensorboard/tensorboard/examples/plugins/example_basic/ /dynamic_plugin
* cd /dynamic_plugin/example_basic
		
* python setup.py develop
		Console Output
```
running develop
running egg_info
creating tensorboard_plugin_example.egg-info
writing tensorboard_plugin_example.egg-info/PKG-INFO
writing dependency_links to tensorboard_plugin_example.egg-info/dependency_links.txt
writing entry points to tensorboard_plugin_example.egg-info/entry_points.txt
writing top-level names to tensorboard_plugin_example.egg-info/top_level.txt
writing manifest file 'tensorboard_plugin_example.egg-info/SOURCES.txt'
reading manifest file 'tensorboard_plugin_example.egg-info/SOURCES.txt'
writing manifest file 'tensorboard_plugin_example.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.6/dist-packages/tensorboard-plugin-example.egg-link (link to .)
Adding tensorboard-plugin-example 0.1.0 to easy-install.pth file

Installed /dynamic_plugin/example_basic
Processing dependencies for tensorboard-plugin-example==0.1.0
Finished processing dependencies for tensorboard-plugin-example==0.1.0
```
* pip list  (I see 'tensorboard-plugin-example 0.1.0           /dynamic_plugin/example_basic')
* tensorboard --logdir /tmp/whatever  (<--- to launch server)

4. Launch TensorBoard
![image](https://user-images.githubusercontent.com/5108675/62809548-1886ab00-bab0-11e9-9edc-f5c8f4bca79b.png)

**Comment by wchargin** [comment] 2019-08-09 21:27
Thanks for the clear instructions. I followed them and can reproduce
this output. But I think that it’s working as intended. On my end, the
example plugin is loaded but inactive. It appears under the “inactive
plugins” drop-down menu, and when you select it it loads properly:

![Screenshot of example plugin][1]

[1]: https://user-images.githubusercontent.com/4317806/62810020-7e276700-bab1-11e9-911d-7ef3d530e0da.png

If I additionally install `tf-nightly-2.0-preview`, I can run the demo
script in `./tensorboard_plugin_example/demo.py` to generate data, and
this is correctly rendered when launching `tensorboard --logdir .`.

Does this resolve the confusion?

**Comment by ceevee830** [comment] 2019-08-09 23:54
Hi William, 

1) Yes I do see `example_basic` in the drop list.  When I select it, I don't see the data in the panel.  Here is what I see in the browser console:

![image](https://user-images.githubusercontent.com/5108675/62814326-0400dd80-bac5-11e9-8b94-a4cbf885b0ee.png)

2) Within `/dynamic_plugin/example_basic/tensorboard_plugin_example`, I ran `python demo.py`.  Saw some good output without any error messages.  Then I ran `tensorboard --logdir /tmp/whatever`.  Same error in browser console: `TypeError: error loading dynamically imported module`.  

- Do I need to install `tf-nightly-2.0-preview`?  

- Does logdir have to point to a specific directory?

3) Once I get this working, what is the likelihood that this will work inside TB 1.14?

**Comment by wchargin** [comment] 2019-08-10 01:01
Interesting. Thank you for the report. It looks like the dynamic plugin
loading mechanism is not working in Firefox. I’ve filed #2536 for this.
We aim to fully support latest Firefox as well as latest Chrome, and
this is a core mechanism, so I’ve triaged this as high-priority
internally. I can’t guess as to the cause: the actual network request is
succeeding with 200 and the right response, and there’s not much
information about the error code on the Internet. I’m looking into the
Firefox source to see if I can get any clues that way.

In the meantime, is using a Chromium-based browser an option for you?

**Comment by ceevee830** [comment] 2019-08-10 06:47
Yes I can see it with Chrome.  Will this work inside TB 1.14?

**Comment by wchargin** [comment] 2019-08-13 00:33
We’ve found a workaround to fix dynamic plugins in Firefox (#2540),
which should be released in today’s nightly.

> what is the likelihood that this will work inside TB 1.14?

Hard to say. We hadn’t officially finalized or released the dynamic
plugin infrastructure at the time of the 1.14.0 release; it’s just that
a lot of the pieces were already there, so many things will happen to
work. But, as you’re seeing from this Firefox bug, it’s certainly not
battle-tested.

**Comment by ceevee830** [comment] 2019-08-13 15:00
Thanks for escalating and fixing the Firefox bug.
Is there a way you could package and send me the files that enable dynamic plugins so that I could include/merge them into our custom TB v1.14?  If I could get this functionality inside our TB, our customers would be extremely happy.

**Comment by wchargin** [comment] 2019-08-13 17:39
> Is there a way you could package and send me the files that enable
> dynamic plugins so that I could include/merge them into our custom TB
> v1.14?

All the files related to dynamic plugins are in this public Git
repository. You’re more than welcome to clone, copy, modify, and merge
those files however you like (subject to the license conditions, of
course).

The changes are fairly cross-cutting across core parts of TensorBoard—
the plugin base `BasePlugin` and `TBContext`, the backend core routing
and serving logic, the frontend `tf-tensorboard` shell, etc.—so I can’t
just send you a file or two to add wholesale to your tree. As far as
packaging, our nightly builds follow the same packaging process as our
full releases, so pulling the latest nightly should be sufficient. (I’ve
verified that the Firefox fix made it into today’s nightly correctly.)

I believe that everything’s working as expected now, so I’m going to
close this—please feel free to comment if something’s still unresolved,
or open a new issue if you run into any more problems. Thanks!

**Closed by wchargin** 2019-08-13 17:39 UTC
Labels: stat:awaiting response, type:support
