### ISSUE TITLE
Protobuf breaks bazel fetch

### ISSUE THREAD

**Issue by abbradar** [tensorflow/tensorboard#719] opened 2017-11-10 17:27 UTC
OS: NixOS 18.03pre119292.cfafd6f5a8
TensorBoard version: 0.1.8
Bazel: 0.4.5

```
$ bazel fetch tensorboard:tensorboard
ERROR: /run/user/1000/.cache/bazel/_bazel_abbradar/84fb9207e5a69b2add72d42fc5eb546e/external/protobuf/BUILD:623:1: no such target '//external:python_headers': target 'python_headers' not declared in package 'external' defined by /home/abbradar/nixpkgs/tensorboard/WORKSPACE and referenced by '@protobuf//:python/google/protobuf/pyext/_message.so'.
ERROR: /run/user/1000/.cache/bazel/_bazel_abbradar/84fb9207e5a69b2add72d42fc5eb546e/external/protobuf/BUILD:609:1: no such target '//external:python_headers': target 'python_headers' not declared in package 'external' defined by /home/abbradar/nixpkgs/tensorboard/WORKSPACE and referenced by '@protobuf//:python/google/protobuf/internal/_api_implementation.so'.
ERROR: Evaluation of query "deps(tensorboard:tensorboard)" failed: errors were encountered while computing transitive closure.
```

**Comment by jart** [comment] 2017-11-10 18:31
Does installing the Python headers package work?

**Comment by abbradar** [comment] 2017-11-10 18:46
No, I have Python headers installed (but they are installed in an unconventional place, should still be picked up). How does Bazel detect is there are needed headers installed?

**Comment by jart** [comment] 2017-11-10 18:59
Protobuf might want us to have something like this in our `third_party/workspace.bzl`:

```py
  native.bind(
      name = "python_headers",
      actual = str(Label("//util/python:python_headers")),
  )
```

Which is most likely super painful to set up. So I would ask:

1. Do all the `bazel build` commands you want to run, work? Please note that building fetches automatically.
2. Is copying the headers to the standard path a viable workaround?

**Comment by abbradar** [comment] 2017-11-10 19:54
Unfortunately, (1) is not an option because we do our builds in a hermetized environment without a network connection. We do this in two stages -- first `fetch` with checksumming and then `build`.

(2) is not an option -- builds are done in a standartized environment (Nix build manager).

**Comment by jart** [comment] 2017-11-10 20:56
That's a legitimate use case.

The only solution I can think of is to adopt TensorFlow's `python_configure` rule. In order to do that, I want to fix this problem where it needs to be manually configured, i.e. the `Python Configuration Error: 'PYTHON_BIN_PATH' environment variable is not set` errors I thought I removed earlier.

One thing I'll bring to your attention is a script similar to [proxy.py](https://gist.github.com/jart/b64b609819f605b24bed0c2d362ca648) can always be used to create this type of hermetic environment.

**Comment by jart** [comment] 2017-11-10 21:47
@abbradar I've confirmed a solution. Once https://github.com/tensorflow/tensorflow/pull/14467 is merged I can mail out a PR fixing this issue.

**Comment by globin** [comment] 2017-12-08 00:53
Since the blocking PR has been merged is there any further progress on this?

**Comment by wchargin** [comment] 2019-08-30 01:14
This should be fixed now. We depend on TensorFlow’s workspace
definition, which defines `python_headers`:

<https://github.com/tensorflow/tensorflow/blob/ea5477fe59b761605c7f1d29fdedf6b1360fc3a9/tensorflow/workspace.bzl#L1004-L1008>

We also run `bazel fetch //tensorboard/...` on every CI run, so
regressions should be caught quickly enough.

**Closed by wchargin** 2019-08-30 01:14 UTC
Labels: type:build/install
