### ISSUE TITLE
--path_prefix broken in 2.4.0+

### ISSUE THREAD

**Issue by qrtt1** [tensorflow/tensorboard#4421] opened 2020-12-03 04:28 UTC
**Describe the current behavior**

Some tensorboards installed with tensorflow couldn't access the right URLs.

Reproducible steps

1. install a tf 2.3.1
2. start tensorboard with prefix

```
tensorboard --logdir logs --port 5001 --bind_all  --path_prefix /abc/def
```

We got `failed to fetch runs`

![image](https://user-images.githubusercontent.com/193223/100859743-93a47980-34ca-11eb-9fe8-74ac99ca12f6.png)

Because some requests did not add `abc/def` prefix to the base URL:

![image](https://user-images.githubusercontent.com/193223/100860177-22b19180-34cb-11eb-9150-97855bf88f5e.png)

 
**Describe the expected behavior**

All tensorboard requests should add prefix to the base URL if `--path_prefix` has given.

**Standalone code to reproduce the issue**

I created a regression tests project to investigate the problem

https://github.com/qrtt1/tensorboard-regression/runs/1487646153

It got worse after tf 2.3.0 (they use tensorboard `2.4.0`):

![image](https://user-images.githubusercontent.com/193223/100905996-a1c2bc00-3503-11eb-9f60-27407e10d947.png)

**Comment by stephanwlee** [comment] 2020-12-03 06:50
Thanks for the report. I was able to reproduce it and it is a serious regression. It is quite interesting to see a puppeteer based tests that catches regression for TensorBoard :) 

For TensorBoarder:

This change is related to the router in the 2.4.0. In the release, we introduced a handrolled router which is unaware of notion of path prefix and eagerly redirects "/foo/bar/index.html" to "/" which breaks all the subsequent requests. Few ways to move forward:
- make the request to "/environments" before bootstrapping components to fetch the path_prefix
  - this is a bit nasty because environment has an experiment specific data_location. I think we should disentangle global setting vs. per-exp settings
  - period of blank page until the request is successful
- invest in the dehydration/rehydration scheme to populate some state when flushing down the HTML

**Comment by MrBago** [comment] 2021-01-13 23:01
@stephanwlee I just ran into this and it's nice to see that you just merged #4423, thank you! Any chance we might be able to get a patch release of 2.4 with this fix backported?

**Comment by wchargin** [comment] 2021-01-13 23:46
We do plan to publish a patch release. I’ve filed #4547 to track it.

**Comment by wchargin** [comment] 2021-01-19 17:52
[TensorBoard 2.4.1][tb] shipped with this patch.

[tb]: https://pypi.org/project/tensorboard/2.4.1/

**Closed by wchargin** 2021-01-19 17:52 UTC
Labels: core:frontend, type:bug
