### ISSUE TITLE
CSS crisp-edges leads to bad image quality

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorboard#2247] opened 2019-05-19 17:48 UTC
TB version: 1.14.0a20190513

How the image looks with `image-rendering: -moz-crisp-edges;`:
![grafik](https://user-images.githubusercontent.com/9438971/57985901-ff50fe00-7a6e-11e9-8d3a-a62c6d5d86f2.png)

How the image actually looks like (without the css property):
![grafik](https://user-images.githubusercontent.com/9438971/57985892-e3e5f300-7a6e-11e9-8d25-59d2a92be792.png)

**Comment by stephanwlee** [comment] 2019-05-22 15:07
Hi there, thanks for raising an issue.

Before discussing the CSS changes, may I ask how you have obtained this image (a minimal code to reproduce would be awesome)? Is this showing the "actual image size"? I did try to reproduce but was without success: when showing the actual size, there was no interpolation/sub-sampling done by the browser that it did not create any weird artifacts. 

```py
import io
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf


# Data for plotting
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

buf = io.BytesIO()
plt.savefig(buf, format='png')
buf.seek(0)

# Convert PNG buffer to TF image
image = tf.image.decode_png(buf.getvalue(), channels=4)

# Add the batch dimension
image = tf.expand_dims(image, 0)

writer = tf.summary.create_file_writer('foo')
with writer.as_default():
  tf.summary.image('foo', image, step=1)

writer.flush()
```

**Comment by sleighsoft** [comment] 2019-05-22 17:11
Here is the image itself. Cannot really share the stuff around it to generate it.

![individualImage](https://user-images.githubusercontent.com/9438971/58194285-69fb7700-7cc5-11e9-9ea8-acc78c1858c5.png)

**Comment by stephanwlee** [comment] 2019-05-22 17:34
So, is the above plot showing the "actual image size"?

**Comment by sleighsoft** [comment] 2019-05-23 12:11
My first comment shows two screenshots of the images with and without the property.
I obtained these by clicking on the smaller version of the image within tb to display the image in its actual size. The blurry effect happens in both the smaller "preview" version as well as the "actual size" case.

The last image I uploaded is the image as I can download it from tb.

I hope that clarifies it.

**Comment by stephanwlee** [comment] 2019-05-23 17:06
> The blurry effect happens in both the smaller "preview" version as well as the "actual size" case

Thanks for confirming this. Of course, I was able to reproduce this with Firefox by just loading the image on a tab (of course without any scaling). Now, I am a bit conflicted here because the original intention of the rule was for people who writes _data_ (like Tensor values) out as an image where very pixel signify meaningful data. In that case, we would not want any interpolation. @nfelt any thoughts on this?

**Comment by nfelt** [comment] 2019-05-23 17:18
I think ultimately we should factor out what is essentially tensor data representation (pixelated images, etc.) from data that is more fundamentally visual (like an actual photographic input image, or this case of using a chart as an image) and that would resolve the issue.

For now I'm inclined to keep the pixelation, since I think bad image quality for visual data is more of a nuisance than an accuracy issue per se (and you can always download the image to view it with normal interpolation), whereas normal interpolation on an image meant to be viewed as pixelated could make it hard to interpret accurately, and the workaround is less straightforward.

**Comment by rmothukuru** [comment] 2019-09-20 00:08
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-09-20 00:08 UTC
Labels: plugin:images, stat:awaiting tensorflower, type:support
