### ISSUE TITLE
Layer tooltip box runs behind sidebar with long names

### ISSUE THREAD

**Issue by themightyoarfish** [tensorflow/tensorboard#1400] opened 2018-09-03 07:29 UTC
- TensorBoard version (from pip package, also printed out when running `tensorboard`): 1.5.1
 - OS Platform and version: Linux Ubuntu 16.04
 - Python version: 3.6
 - For browser-related issues:
   - Browser type and version: Firefox 61.0.2 (64-bit)
   - Screenshot if it's a visual issue:

![screen shot 2018-09-03 at 09 27 31](https://user-images.githubusercontent.com/11613312/44973084-aaf70400-af5b-11e8-8368-d79a82a35731.png)

When using long names for layers, the tooltip box popping up when hovering over a plot is cut off at the left since it moves behind the sidebar. It is thus impossible to see which layer corresponds to the line the cursor is on.

**Comment by themightyoarfish** [comment] 2018-09-03 07:36
It would be better if the box was drawn over everything else  and maybe an ellipsis used to abbreviate the middle part of the plot name, if the box is too large.

**Comment by nfelt** [comment] 2018-09-03 22:29
Duplicate of #1170

**Comment by nfelt** [comment] 2018-09-03 22:30
Thanks for reporting.  I believe #1170 is already tracking this issue - please follow along there.

**Closed by nfelt** 2018-09-03 22:30 UTC
