### ISSUE TITLE
tensorborad/components/tf_backend/RequestManager tests are falsely reported as passing with Bazel

### ISSUE THREAD

**Issue by erzel** [tensorflow/tensorboard#1990] opened 2019-03-08 23:12 UTC
If I add the line:
chai.assert.equal(1,2); 
as the first line of the test  "it('requestManager only sends maxRequests requests at a time', ...")
and then do:
$ bazel test //tensorboard/components/tf_backend/test:all, the test falsely pass.

Note that if I do
$ baze run //tensorboard/components/tf_backend/test:test_web_library, and execute the tests in the browser, I do get a test failure.

**Comment by nfelt** [comment] 2019-03-08 23:40
Duplicate of #1960 I believe

**Closed** 2019-03-08 23:41 UTC
Labels: type:bug/performance
