### ISSUE TITLE
Tensorboard has wrong logdir on Windows

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#54] opened 2017-06-16 19:21 UTC
This issue had been migrated from tensorflow/tensorflow#6313. The thread mentions a workaround, but the root problem of unsupported logdir paths on windows is unresolved.

> I use Tensorflow 0.12rc1 on Windows. "Tensorboard" has problems parsing the logdir. My log-directory is at E:\tmp\tflogs. When I start tensorboard from the windows shell (cmd.exe) with:
> 
> tensorboard --logdir=E:\tmp\tflogs
> 
> it depends on the current directory / drive if it works or not (i.e., if tensorboard finds the runs and shows the data). If the current directory is, e.g., on the C:\ drive, tensorboard tries to add runs from c:\tmp\tflogs instead of E:\tmp\tflogs.
> 
> Example:
> C:\Users\wrammer>tensorboard --logdir=E:\tmp\tflearn_logs --debug
> The log contains lines such as:
> INFO:tensorflow:Starting AddRunsFromDirectory: C:\tmp\tflearn_logs

**Comment by dandelionmane** [comment] 2017-06-22 18:11
Duplicate of https://github.com/tensorflow/tensorboard/issues/52

**Closed by dandelionmane** 2017-06-22 18:11 UTC
Labels: (╯°□°)╯windows, type:bug/performance
