### ISSUE TITLE
Delete runs from the web interface of tensorboard

### ISSUE THREAD

**Issue by roboserg** [tensorflow/tensorboard#2230] opened 2019-05-14 05:01 UTC
Referencing a very old feature request. It was never implemented. https://github.com/tensorflow/tensorflow/issues/5039

**Comment by nfelt** [comment] 2019-05-14 17:39
Duplicate of #785 

Please see latest comment there which is pretty much still the status.

**Closed by nfelt** 2019-05-14 17:39 UTC
Labels: type:feature
