### ISSUE TITLE
AttributeError: module 'tensorboard' has no attribute 'lazy'

### ISSUE THREAD

**Issue by Threynaud** [tensorflow/tensorboard#1862] opened 2019-02-16 17:21 UTC
- Tensorboard version: 1.12.2
- Tensorflow version: tf-nightly-2.0-preview==2.0.0.dev20190216
- OS: MacOS Mojave
- Python version: 3.6.5

Training a simple model with `tf.keras` in the latest  `tf-nightly-2.0-preview` will result in the following error even without using any Tensorboard callback during training:

```Traceback (most recent call last):
  File "/Users/thms/.virtualenvs/tf2/bin/tensorboard", line 6, in <module>
    from tensorboard.main import run_main
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/site-packages/tensorboard/main.py", line 45, in <module>
    from tensorboard import default
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/site-packages/tensorboard/default.py", line 34, in <module>
    import tensorflow as tf
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/__init__.py", line 30, in <module>
    from tensorflow._api.v2 import compat
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/_api/v2/compat/__init__.py", line 22, in <module>
    from tensorflow._api.v2.compat import v2
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 306, in <module>
    "Limited tf.compat.v2.summary API due to missing TensorBoard "
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/site-packages/tensorflow/python/tools/component_api_helper.py", line 56, in package_hook
    child_pkg = importlib.import_module(child_package_str)
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/site-packages/tensorboard/summary/__init__.py", line 32, in <module>
    from tensorboard.summary import v2
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/site-packages/tensorboard/summary/v2.py", line 24, in <module>
    from tensorboard.plugins.audio.summary_v2 import audio
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/site-packages/tensorboard/plugins/audio/summary_v2.py", line 30, in <module>
    from tensorboard.compat import tf2 as tf
  File "/Users/thms/.virtualenvs/tf2/lib/python3.6/site-packages/tensorboard/compat/__init__.py", line 28, in <module>
    import tensorboard.lazy as _lazy
AttributeError: module 'tensorboard' has no attribute 'lazy'
```

Is there a specific tensorboard build to use with the TF2.0 preview?

**Comment by nfelt** [comment] 2019-02-16 21:13
At this point only the nightly build of TensorBoard (`tb-nightly`) is compatible with the TF 2.0 preview, 1.12.2 is not expected to work.  If you just install `tf-nightly-2.0-preview` alone in a fresh virtualenv it should install a compatible `tb-nightly`.

I also had trouble reproducing this error, with the same setup except High Sierra instead of Mojave which I doubt makes a difference here - I hit an error at `AttributeError: module 'tensorflow._api.v2.train' has no attribute 'SessionRunHook'` instead.  Is it possible you had `tb-nightly` installed as well as 1.12.2?  They both provide the `tensorboard` package so if both are installed you might be in an indeterminate state.

**Comment by Threynaud** [comment] 2019-02-16 21:19
Yes I pip installed tensorboard separately indeed. I didn't see it was installing `tb-nightly` in the background. How do you launch the nightly version of tensorboard then? The `tensorboard` command does not exist..

Thanks for your response!

**Comment by nfelt** [comment] 2019-02-17 00:33
Okay, great.  I'll go ahead and close this since it sounds like that worked for you.

**Closed by nfelt** 2019-02-17 00:33 UTC

**Comment by zmjjmz** [comment] 2019-08-13 17:48
I've found this issue to also occur with TensorFlow 1.14, and was able to resolve it by installing `tb-nightly`.

**Comment by hzlenjoy** [comment] 2019-08-16 03:51
if using `pip`, somehow the order of `tensorflow-tensorboard` and `tensorboard` matter...
```
pip install tensorflow-tensorboard==1.5.1
```
then
```
pip install tensorboard==1.14.0
```
this will be solved

**Comment by lenjoy** [comment] 2019-08-16 03:54
if using `pip`, somehow the order of `tensorflow-tensorboard` and `tensorboard` matter...

```
pip install tensorflow-tensorboard==1.5.1
```
then
```
pip install tensorboard==1.14.0
```
this will be solved

**Comment by wchargin** [comment] 2019-08-16 04:03
@lenjoy: The `tensorflow-tensorboard` distribution is a relic of a
bygone era; there’s no need to install it anymore. As noted on [the PyPI page][1]

> **NOTICE:** This PyPI entry has been deprecated in favor of the
> `tensorboard` name found at <https://pypi.python.org/pypi/tensorboard>
> for TensorBoard 1.6.0+. Only bugfix updates on 1.5.x will be applied
> to this old package name.
>
> To upgrade past the version shown on this page, please ensure that you
> _first_ `pip uninstall tensorflow-tensorboard` and then `pip install
> tensorboard`.

[1]: https://pypi.org/project/tensorflow-tensorboard/

**Comment by lenjoy** [comment] 2019-08-16 17:02
@wchargin , got it. thanks! it works!

**Comment by a1-mukul** [comment] 2019-09-25 13:54
@wchargin Thanks I was looking for this answer. This thing worked for me.

**Comment by adithya-tp** [comment] 2020-01-17 18:34
@wchargin Thanks for this!

**Comment by franklee24** [comment] 2021-02-20 01:42
> 
> 
> if using `pip`, somehow the order of `tensorflow-tensorboard` and `tensorboard` matter...
> 
> ```
> pip install tensorflow-tensorboard==1.5.1
> ```
> 
> then
> 
> ```
> pip install tensorboard==1.14.0
> ```
> 
> this will be solved



> 
> 
> if using `pip`, somehow the order of `tensorflow-tensorboard` and `tensorboard` matter...
> 
> ```
> pip install tensorflow-tensorboard==1.5.1
> ```
> 
> then
> 
> ```
> pip install tensorboard==1.14.0
> ```
> 
> this will be solved

still this bug...how can i do ?

**Comment by wchargin** [comment] 2021-02-20 01:46
@franklee24: As mentioned above, please **uninstall** all versions of
`tensorboard` and `tensorflow-tensorboard` and `tb-nightly`, and then
install just the version that you want.

If that does not suffice, please open an issue and include all the
requested information.
