### ISSUE TITLE
Error when trying to start Tensorboard in Colab

### ISSUE THREAD

**Issue by NielsRogge** [tensorflow/tensorboard#3186] opened 2020-01-28 10:06 UTC
I'm trying to start Tensorboard in Google Colab, by running the basic [tutorial](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks). Unfortunately, running this tutorial on my Macbook Pro in Google Chrome only gives me the message "403. That's an error. That's all we know". It happens when running 
``
%tensorboard --logdir logs. 
``
After re-running this command, I still get the 403 error together with the message
``
"Reusing TensorBoard on port 6006 (pid 228), started 0:00:07 ago. (Use '!kill 228' to kill it.)". 
``

**Comment by wchargin** [comment] 2020-01-28 18:04
Hi @NielsRogge! I’ve just tried running that notebook and can’t
reproduce the error, but I’m on Linux—@stephanwlee, mind taking a look
at this on your macOS machine?

In the meantime, can you post a screenshot of the error (is it a Chrome
“sad tab” page, or a message served by googleusercontent?) and the
contents of any JS console logs, and also let us know what version of
Chrome you’re using? You could also try resetting your Colab runtimes
(*Runtime* → *Factory reset runtime*), which will give you a clean slate
in case something got into a bad state, but I can’t promise that that
will fix the problem.

**Comment by stephanwlee** [comment] 2020-01-28 18:26
I tried running the tutorial from the top to bottom on Colab. I found the TensorBoards on the two output cells to work as expected on Chrome 79.

Few things that are on my minds are:
- this problem should not be unique to macOS.
- Colab's ServiceWorker is known to be a bit flaky (especially after long period of time).

@NielsRogge, what browser are you using? Which version? Also, can you please reset/restart the kernel and execute all cells?

**Comment by NielsRogge** [comment] 2020-01-30 09:33
Thank you both for the quick reply. I tried running the notebook again from top to bottom. However, I still get the error. A screenshot can be found here: https://photos.app.goo.gl/9AgJRRvMh1JS5rtBA. 

My laptop is a Macbook Pro running MacOS High Sierra 10.13.
I'm running this Colab notebook on Google Chrome version 79.0.3945.130 (Official build) (64-bits).

**Comment by stephanwlee** [comment] 2020-01-30 15:57
Thanks for the browser details.

When you open up chrome://serviceworker-internals/, do you see any entry with "colab" in it? 
In Colab, when you open up Chrome DevTools (Menu > More Tools > Developer Tools), do you see any streak of errors?

**Comment by NielsRogge** [comment] 2020-01-30 20:08
Figured it out. It had to do with third-party cookies that are disabled in my Google Chrome settings.
I went to chrome://settings/content/cookies and had to unable the "block indirect cookies" setting. 

However, what's weird is that I cannot enable this setting and put colab.research.google.com on the list of websites which are allowed to have cookies. Shouldn't this work?

**Comment by stephanwlee** [comment] 2020-01-30 20:46
Fascinating. Thanks for sharing that. 

Does putting `googleusercontent.com` on the list help? The ServiceWorker uses that URL.

**Comment by NielsRogge** [comment] 2020-01-31 08:13
No, it does not help. It only works when I disable the option "block third-party cookies", even when I put colab.research.google.com, googleusercontent.com and colab.googleusercontent.com on the list of "allowed".

**Comment by stephanwlee** [comment] 2020-01-31 16:23
Thanks for checking that. I was able to reproduce it, too. 

I filed a bug on Colab. There are no actions required on your part and we will leave this bug open until we hear back from them.

**Comment by wchargin** [comment] 2020-01-31 19:10
Cross-reference for Googlers: <http://b/148665442>. (Thanks, @stephanwlee!)

**Comment by stephanwlee** [comment] 2020-02-04 17:38
There were very little updates to the bug besides references to the public policy of Colab's.

> Colab uses HTML iframes and service workers hosted on separate origins in order to display rich outputs securely. Browsers require enabling third-party cookies to use the service workers within iframes. An alternative to enabling third-party cookies for all sites is to whitelist the following hostname in your browser settings: googleusercontent.com.

(source: <https://research.google.com/colaboratory/faq.html#third-party-cookies>)

I could not get the whitelist as describe in the policy to work on Chrome 79, so I inquired them but there was not much update on the bug.

While I will relay any updates to the bug, I will close this issue since there isn't action TensorBoard can take and the bug is for Colab to address.

**Closed by stephanwlee** 2020-02-04 17:38 UTC
Labels: type:support

**Comment by j0ner0n** [comment] 2020-07-24 13:19
Small note for Brave browser users: Similar issue to Google Chrome as the browser will block required functionality by default. Turn shields off and it should work

**Comment by Vasuki8** [comment] 2020-09-08 12:11
Make sure third party cookies are allowed.

**Comment by Byron1990** [comment] 2022-05-27 05:08
I had the same problem, in my case the problem was that I was using FIrefox with "Total Cookie Protection" enabled. I disabled it and now everything is fine.

**Comment by ROBOTIS-David** [comment] 2023-10-16 15:27
I tried to display Tensor board on my colab (at Latest version of Chrome, M1 Mac), but what I only get is 403 Error after running a tensorboard launch cell.  But Microsoft Edge properly display the board. 

Environment: 
1. Version of Mac: Ventura 13.2.1 
2. Chrome Version: 118.0.5993.70 (Official Build) *arm64
3. Allowed third-party cookies (I am not using Inconition Mode) 

![Screenshot 2023-10-17 at 12 20 07 AM](https://github.com/tensorflow/tensorboard/assets/48426280/edb2b9f3-7b2d-49cf-a777-9de111c8b130)

Hope that I can find any clue to this issue.

**Comment by rjtp5670** [comment] 2023-10-16 15:30
I tried to display Tensor board on my colab (at Latest version of Chrome, M1 Mac), but what I only get is 403 Error after running a tensorboard launch cell. But Microsoft Edge properly display the board.

Environment:

Version of Mac: Ventura 13.2.1
Chrome Version: 118.0.5993.70 (Official Build) *arm64
Allowed third-party cookies (I am not using Inconition Mode)

![image](https://github.com/tensorflow/tensorboard/assets/49303847/9ae1445e-8cf8-4cac-ae80-f2817e324494)

Hope that I can find any clue to this issue.

**Comment by bmd3k** [comment] 2023-10-17 11:51
Hi @rjtp5670.
For the latest problems of TensorBoard running in Colab in Chrome, the Colab team have been investigating. We expect them to comment here with updates:

https://github.com/googlecolab/colabtools/issues/3990

**Comment by bileschi** [comment] 2023-10-23 17:58
Googlers: tracked internally at b/301984066

**Comment by g-i-o-r-g-i-o** [comment] 2024-07-03 09:01
I still have the same problem on firefox.
