### ISSUE TITLE
Embeddings projector doesn't blend sprites with alpha correctly

### ISSUE THREAD

**Issue by frankier** [tensorflow/tensorboard#3778] opened 2020-07-01 06:48 UTC
## Issue description

If you provide a sprite sheet with an alpha channel, all transparent pixels are solid grey rather than transparent. This is probably because the MULTIPLY blending modes do not take into account alpha information by default.

(See https://threejs.org/docs/#api/en/constants/CustomBlendingEquations)

**Comment by rmothukuru** [comment] 2020-07-01 10:38
@frankier,
Can you please elaborate your issue. Can you please share the screenshots so that we can understand the issue better. Also, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by frankier** [comment] 2020-07-01 11:02
![Screenshot from 2020-07-01 13-58-21](https://user-images.githubusercontent.com/299380/86236622-11262f80-bba3-11ea-9d51-a14b37edffa5.png)
[handtslocal2.zip](https://github.com/tensorflow/tensorboard/files/4857399/handtslocal2.zip)

**Comment by nfelt** [comment] 2020-07-01 17:14
Thanks for the report.  We'd be happy to take a PR that addresses this if you're familiar with the changes that would need to be made to support alpha channel blending.

**Comment by BlGene** [comment] 2021-03-14 18:07
Tensorboard seems to always be blending sprites, when trying to run T-SNE with a large number of data-points, which is required in order to get a good embedding, this results in not so usable figures (see below).

I think this may be a separate issue, since it also happens when there are no alpha value in the sprites.

Tensorboard v 2.4.1, Firefox v. 86, but also happens on Chromium.

When trying to plot the figure manually, I couldn't download the bookmark of the results as I was getting the following error:
```Content Security Policy: The page’s settings blocked the loading of a resource at blob:http://localhost:6006/beb5fa3f-63a4-4c62-83b5-d06234739370 (“frame-src”).```

![tensorboard_tsne_fail](https://user-images.githubusercontent.com/1850503/111078731-44bda580-84f7-11eb-9d7f-ea1203021495.png)

**Comment by tyhenry** [comment] 2021-04-27 01:01
@BlGene I have the same problem with the Embedding Projector always blending sprite images.  I believe it's due to Embedding Projector using THREE.js multiply blendmode for sprite images.
See this issue for a fix: https://github.com/tensorflow/tensorboard/issues/4911

**Comment by BlGene** [comment] 2021-04-27 09:10
@tyhenry: Thank you for posting the fix. :+1:

**Comment by nfelt** [comment] 2021-08-05 17:24
I believe this has been fixed by a combination of #4911 (actual PR #4921) as mentioned above, to stop using multiply blendmode, followed by #5149 to ensure sprites with alpha actually are transparent rather than occluding whatever's behind them.  Thanks for the contributions everyone.

**Closed by nfelt** 2021-08-05 17:24 UTC
Labels: type:bug, stat:contributions welcome, plugin:projector
