### ISSUE TITLE
Feature Request: Plotly plots

### ISSUE THREAD

**Issue by dzimmerer** [tensorflow/tensorboard#513] opened 2017-09-11 18:40 UTC
Hey,

really great would be a plugin for arbitrary plot.ly plots ( /plotly.js similar to visdom). Not sure if it's that easy (and I probably won't have much time to look into it in the next weeks). 

Just wanted to tell you.

Cheers

**Comment by dandelionmane** [comment] 2017-09-12 21:56
Thanks for the suggestion!

Adding support for an arbitrary plotting library is actually quite complicated. The issue is twofold:
1. Arbitrary plots will tend to have arbitrary data. How is the data format standardized or communicated to the frontend? What would the APIs on the TensorFlow layer look like, for expressing that data?
2. Arbitrary plots will require coding/frontend configuration. Where will the user write that code? Will they put the javascript in the backend, or will there be an IDE-like interface in the frontend where the user can write code (or choose from predetermined options) to configure their plots?

Without answers to those questions, this suggestion isn't actionable. Since you said you won't have much time to look into it in the next weeks, I'm going to close the issue, but please feel free to re-open it when you have time to sketch out a proposal :)

**Closed by dandelionmane** 2017-09-12 21:56 UTC
Labels: stat:contributions welcome, type:feature (new plugin)
