### ISSUE TITLE
Scalar Roll-overs incorrectly display summary information

### ISSUE THREAD

**Issue by ro3c** [tensorflow/tensorboard#451] opened 2017-08-31 16:17 UTC
Attached screenshot shows that the values in the scalar roll-over box are shifted to the left.

![image](https://user-images.githubusercontent.com/14815348/29933574-204946e2-8e46-11e7-8239-62a4e3983437.png)

Problem occurs at all levels of zoom

**Comment by wchargin** [comment] 2017-08-31 16:25
I suspect that (a) you have chart smoothing turned off, and (b) you are using an old version of TensorBoard. Could you please run `pip install --upgrade tensorflow tensorflow-tensorboard`, then check whether you still observe this problem? (I fixed it in #191, though it's possible that a particular recent PR may have reintroduced it.)

**Comment by chihuahua** [comment] 2017-09-01 06:13
As @wchargin noted, #191 fixed the issue. There's a chance that #388 re-introduced the issue. That being said, I don't think I can repro at HEAD:

![5brkc4ejduz](https://user-images.githubusercontent.com/4221553/29957197-f73d5620-8ea0-11e7-98f3-7f110fa6d4dc.png)

And it seems like we currently create 1 table data per column
https://github.com/tensorflow/tensorboard/blob/534c23c6ab37b50dfb5f106b3d4433ce6323d040/tensorboard/components/vz_line_chart/vz-line-chart.ts#L707

as well as 1 table header per column
https://github.com/tensorflow/tensorboard/blob/534c23c6ab37b50dfb5f106b3d4433ce6323d040/tensorboard/components/vz_line_chart/vz-line-chart.ts#L296

regardless of whether smoothing is enabled. Indeed, @ro3c, if you could help us debug by comparing behavior at head ([the latest TensorBoard](https://pypi.python.org/pypi/tensorflow-tensorboard)), we'd appreciate it!

**Comment by ro3c** [comment] 2017-09-01 20:01
I don't usually use chart smoothing, but turning it on doesn't make any difference.
How do I confirm whether I have the latest tensorboard?  I build TF from source and use the included TensorBoard.

**Comment by wchargin** [comment] 2017-09-01 20:10
@ro3c `tensorboard --version` should be `0.4.0`; `0.3.0` is also fine for this purpose.

If you're building TensorFlow from source, it shouldn't be too hard to build TensorBoard from source, too. Alternately, you can `pip install tensorflow-tensorboard==0.4.0`. This will still let you use TensorFlow from source: it will not install a TensorFlow package from PyPI.

**Comment by ro3c** [comment] 2017-09-01 20:18
Ok, I will do the pip install in about 2 hours. I currently have a big test running and don't want to disturb it.

**Comment by ro3c** [comment] 2017-09-01 20:53
@wchargin  did you mean 0.1.4 ?

**Comment by wchargin** [comment] 2017-09-01 21:01
0.1.4 is fine, yes. This problem should also have been fixed in 0.1.3, though, so 0.1.3 is fine as well.

Yes, where I wrote `tensorflow-tensorboard==0.4.0` I meant `0.1.4`. It appears that we have `0.1.5` out, too, so you can use that.

**Comment by ro3c** [comment] 2017-09-01 21:10
I loaded 0.1.4
First page looks better, but name is not in the box.
2nd and 3rd pages have run-on names at all levels of zoom.
I'll load 0.1.5 and try that as well

![image](https://user-images.githubusercontent.com/14815348/29987758-ad63ba0c-8f37-11e7-88f1-6e11e82f403c.png)

![image](https://user-images.githubusercontent.com/14815348/29987890-6194e0e6-8f38-11e7-883a-186177d096e4.png)

**Comment by wchargin** [comment] 2017-09-01 21:32
It's not clear to me what you mean by "name is not in the box." Are you noting that the run names are ~10 px to the left of the chart boundaries? (If so, this is not a bug.) The screenshot that you include does show the run name in the tooltip: it is `.`, a single period.

The run-on names are a known issue, unrelated to this issue (I can look into the best way to do this; I know of a few potential fixes), so it looks like this was fixed by using a current version of TensorBoard—yes?

0.1.5 should have the same behavior.

**Comment by chihuahua** [comment] 2017-09-02 02:36
@ro3c, thanks a lot for taking the time to confirm! That looks like expected behavior to me. The run name is indeed just a terse "." because events for that run are stored in the logdir itself (not a subdirectory).

**Comment by ro3c** [comment] 2017-09-02 02:44
Version 1.5 behaves the same as 1.4
Values are aligned with correct headings. Labels on pages after the first page overlap.

Regarding the "name in the box", please pardon my imprecise language:
I was trying to convey that no name appeared in the tooltip roller-over box.  I was unaware that it was supposed to be the "run name."  In previous versions name of the graph was displayed where the mag-glass icon and run name ( .*  in my example) now appear at the top, and the "." on the run list was/is still barely visible.  Thanks for clearing this up for me.  I had not noticed this, because I had no need to switch among multiple runs.

Since the overlapping titles is a known problem, I concur with closing this issue.

**Comment by wchargin** [comment] 2017-09-02 02:56
Got it. Thanks for checking back in with us. Let us know if there's anything else we can do for you.

**Closed by wchargin** 2017-09-02 02:56 UTC
