### ISSUE TITLE
Tensorboard 1.12.0 - "KeyError: None" for object detection training session

### ISSUE THREAD

**Issue by switchedfabric** [tensorflow/tensorboard#1555] opened 2018-10-26 07:23 UTC
Hi,

 - TensorBoard version: 1.12.0, installed from source
 - TensorFlow version: 1.12.0-rc0, installed from source
 - OS Platform and version: Linux Ubuntu 18.04
 - Python version: 2.7.15rc1
 - Browser: Chromium Version 59.0.3071.109 (Developer Build) Built on Ubuntu , running on Ubuntu 16.10 (64-bit)

I run an object detection training session using the provided script in tensorflow/models/research/object_detection/model_main.py.  This runs fine.

I also start up tensorboard but the display in the browser just ticks over (that looping thingie in each graph) and tensorboard stdout/stderr has lots of:

---- 8< ----
E1026 07:09:23.703738 140651287004928 _internal.py:88] Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py", line 307, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/wrappers.py", line 308, in application
    resp = f(*args[:-2] + (request,))
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/plugins/scalar/scalars_plugin.py", line 199, in scalars_route
    (body, mime_type) = self.scalars_impl(tag, run, experiment, output_format)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/plugins/scalar/scalars_plugin.py", line 157, in scalars_impl
    tensor_events = self._multiplexer.Tensors(run, tag)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 397, in Tensors
    accumulator = self.GetAccumulator(run)
  File "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 473, in GetAccumulator
    return self._accumulators[run]
KeyError: None
---- 8< ----

The display in the browser is also all jumbled up:

![image](https://user-images.githubusercontent.com/4634383/47550750-7ae73400-d900-11e8-8ee7-8744d397188e.png)

**Comment by alescire94** [comment] 2018-11-03 10:50
Try to upgrade tensorflow. For me it solved the problem

**Comment by switchedfabric** [comment] 2018-11-05 09:34
@alescire94 from which version to which did you upgrade?

I'm already on 1.12.  On 1.11 it also gives me the error.  1.10 works ok.

**Comment by stephanwlee** [comment] 2018-11-05 23:51
Hi @switchedfabric, can you please provide me with more details? I just tried it with VOC using ssd_mobilenet_v1_coco and I couldn't reproduce the bug. Which model/dataset/config did you use?

**Comment by nanyoullm** [comment] 2018-12-05 03:11
I also meet this issue like you @switchedfabric

**Comment by tifeng** [comment] 2019-01-19 15:37
I also meet this issue ,but how to solved the problem.
TensorBoard version: 1.12.0, and i upgrade to 1.12.0 ,it also gives this error.

**Comment by mike-edmonds** [comment] 2019-01-24 00:11
I have also hit this issue w/ the tensorboard that comes with tf 1.12 using python3.6.
it's a custom tf.Estimator.estimator for the iris dataset, but it's very vanilla (not doing anything w/ writers)

**Comment by fazhiyang** [comment] 2019-01-24 14:03
I also meet this issue, and I think this issue maybe come from  remote server, but I'm not sure.  My TB version: 1.12.2.

**Comment by mike-edmonds** [comment] 2019-01-25 16:12
I too have gone back tensorboard versions -
  1.10.0 works as expects
  1.11.0 does not throw the "E0125 ... _internal.py:88] Error on request:" error, but the web is unusable
  1.12.2 shows no graphs and throws:
E0125 15:59:21.107727 140196783843072 _internal.py:88] Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/application.py", line 307, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/wrappers.py", line 308, in application
    resp = f(*args[:-2] + (request,))
  File "/usr/local/lib/python3.6/site-packages/tensorboard/plugins/scalar/scalars_plugin.py", line 199, in scalars_route
    (body, mime_type) = self.scalars_impl(tag, run, experiment, output_format)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/plugins/scalar/scalars_plugin.py", line 157, in scalars_impl
    tensor_events = self._multiplexer.Tensors(run, tag)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 397, in Tensors
    accumulator = self.GetAccumulator(run)
  File "/usr/local/lib/python3.6/site-packages/tensorboard/backend/event_processing/plugin_event_multiplexer.py", line 473, in GetAccumulator
    return self._accumulators[run]
KeyError: None

**Comment by lshmouse** [comment] 2019-02-01 08:52
Ref https://github.com/tensorflow/tensorboard/issues/1555.
Change tf version to 1.10 will fix this issue.

**Comment by noctune** [comment] 2019-06-06 07:17
Also hitting this issue in TF 1.13.1. We use the `--path_prefix` parameter and serve it behind a reverse proxy. Could this be relevant?

**Comment by RaghuSpaceRajan** [comment] 2019-08-14 13:17
I faced this with TensorBoard 1.14 and TensorFlow 1.14. But my error was:
KeyError: 'DQN_BreakoutNoFrameskip-v4_0_2019-05-28_11-57-41hmp3w0qr'
which was actually the name of a directory inside a previous **logdir** I had loaded with tensorboard. No matter how many times I loaded a new **logdir**, it threw this error.
Reverting to tensorboard-1.12.2 and tensorflow-1.13.0rc1 seems to have worked.

Does TensorBoard have a cache that keeps names of old directories? Can we clear this somehow?

**Comment by wchargin** [comment] 2019-08-14 15:03
@RaghuSpaceRajan: Usually this happens when you launch TensorBoard, open
it in a browser, shut down the TensorBoard process, and start a new one
while keeping the old browser tab up. The old browser tab will continue
making requests to the refresh the charts that it already loaded, which
may not exist in the new TensorBoard process.

The solution is to just close the old TensorBoard tab.

**Comment by RaghuSpaceRajan** [comment] 2019-08-14 15:51
@wchargin: I see. That's very well possible since I tend to not close the old tab, but I don't remember this happening ever before. Strange!

Thanks for the info!

**Comment by elrond79** [comment] 2019-08-30 19:38
Got this with with TensorBoard 1.14 and TensorFlow 1.14, but unlike @RaghuSpaceRajan, it was the original error: KeyError: None.

**Comment by wchargin** [comment] 2019-08-30 23:43
@elrond79, are you finding that TensorBoard works as expected but also
logs `KeyError: None` errors, or is TensorBoard inoperable and rendering
incorrectly as in the original post? Are any other, old TensorBoard
browser tabs open?

In either case, could you please run [`diagnose_tensorboard.py`][d] from
the same environment in which you run TensorBoard and paste the output
here?

[d]: https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

**Comment by wchargin** [comment] 2019-08-31 00:09
I think that it’s pretty likely that this will be resolved by #2611. The
original repro refers to a script that’s no longer available at its
original path, and the object detection script doesn’t appear to be
maintained at its new home (has `PYTHONPATH` module resolution errors,
missing dependencies, …).

If you think that the **original** issue here is still occurring, please
open a new issue and provide all the information requested in the issue
template about how to reproduce the problem. Thanks!

**Closed by wchargin** 2019-08-31 00:09 UTC
Labels: core:backend
