### ISSUE TITLE
ValueError: Duplicate plugins for name whatif

### ISSUE THREAD

**Issue by kkelchte** [tensorflow/tensorboard#3592] opened 2020-05-06 09:03 UTC
Error:

`
Traceback (most recent call last):
  File "******/virtualenvironment/venv/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "virtualenvironment/venv/lib/python3.7/site-packages/tensorboard/main.py", line 66, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "virtualenvironment/venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "virtualenvironment/venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "virtualenvironment/venv/lib/python3.7/site-packages/tensorboard/program.py", line 268, in main
    return runner(self.flags) or 0
  File "virtualenvironment/venv/lib/python3.7/site-packages/tensorboard/program.py", line 282, in _run_serve_subcommand
    server = self._make_server()
  File "virtualenvironment/venv/lib/python3.7/site-packages/tensorboard/program.py", line 361, in _make_server
    self.assets_zip_provider)
  File "virtualenvironment/venv/lib/python3.7/site-packages/tensorboard/backend/application.py", line 165, in standard_tensorboard_wsgi
    flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer)
  File "virtualenvironment/venv/lib/python3.7/site-packages/tensorboard/backend/application.py", line 234, in TensorBoardWSGIApp
    return TensorBoardWSGI(tbplugins, flags.path_prefix)
  File "virtualenvironment/venv/lib/python3.7/site-packages/tensorboard/backend/application.py", line 286, in __init__
    raise ValueError('Duplicate plugins for name %s' % plugin.plugin_name)
ValueError: Duplicate plugins for name whatif
`
Diagnostics output:
`### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version d515ab103e2b1cfcea2b096187741a0eeb8822ef

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Darwin', nodename='******', release='19.4.0', version='Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: '*****/virtualenvironment/venv'

--- check: installed_packages
INFO: installed: tensorboard==2.1.1
INFO: installed: tensorflow==2.1.0
INFO: installed: tensorflow-estimator==2.1.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.1.1'

--- check: tensorflow_python_version
INFO: tensorflow.__version__: '2.1.0'
INFO: tensorflow.__git_version__: 'v2.1.0-rc2-17-ge5bf8de410'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'******/virtualenvironment/venv/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 1024>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 1024>
Loopback infos: [(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): '1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa'

--- check: stat_tensorboardinfo
INFO: directory: /var/folders/lb/pxx32qzs6r1g9xfl9114p9nc0000gn/T/.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['*********/virtualenvironment/venv/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.9.0
appnope==0.1.0
astor==0.8.1
astroid==2.3.3
atari-py==0.2.6
attrs==19.3.0
autobahn==19.11.2
Automat==0.8.0
backcall==0.1.0
bleach==3.1.4
box2d-py==2.3.8
cachetools==4.0.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cloudpickle==1.2.2
constantly==15.1.0
cryptography==2.8
cycler==0.10.0
dataclasses==0.6
dataclasses-json==0.3.7
DateTime==4.3
decorator==4.4.1
defusedxml==0.6.0
entrypoints==0.3
et-xmlfile==1.0.1
frozendict==1.2
future==0.18.2
gast==0.2.2
google-auth==1.12.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
graphviz==0.14
grpcio==1.27.2
gym==0.17.1
h5py==2.10.0
hyperlink==19.0.0
idna==2.8
imageio==2.6.1
importlib-metadata==1.3.0
incremental==17.5.0
ipykernel==5.2.0
ipython==7.11.1
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
jdcal==1.4.1
jedi==0.15.2
Jinja2==2.11.1
joblib==0.14.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
Markdown==3.2.1
MarkupSafe==1.1.1
marshmallow==3.3.0
marshmallow-enum==1.5.1
matplotlib==3.1.2
mccabe==0.6.1
mistune==0.8.4
mock==3.0.5
more-itertools==8.0.2
mpi4py==3.0.3
mypy-extensions==0.4.3
nbconvert==5.6.1
nbformat==5.0.5
networkx==2.4
notebook==6.0.3
numpy==1.18.1
oauthlib==3.1.0
opencv-python==4.2.0.32
openpyxl==3.0.3
opt-einsum==3.2.0
packaging==20.0
pandocfilters==1.4.2
parso==0.5.2
pexpect==4.7.0
pickleshare==0.7.5
Pillow==7.0.0
pip==20.1
pluggy==0.13.1
prometheus-client==0.7.1
prompt-toolkit==3.0.2
protobuf==3.11.3
psutil==5.7.0
ptyprocess==0.6.0
py==1.8.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.19
pyglet==1.5.0
Pygments==2.5.2
PyHamcrest==1.9.0
pylint==2.4.4
pyparsing==2.4.6
pyrsistent==0.16.0
pytest==5.3.2
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3
pyzmq==18.1.1
qtconsole==4.7.2
QtPy==1.9.0
requests==2.22.0
requests-oauthlib==1.3.0
roslibpy==0.7.1
rsa==4.0
scikit-image==0.16.2
scikit-learn==0.22.1
scipy==1.4.1
Send2Trash==1.5.0
setuptools==44.0.0
six==1.13.0
stringcase==1.2.0
tablib==1.1.0
tensorboard==2.1.1
tensorboard-plugin-wit==1.6.0.post2
tensorflow==2.1.0
tensorflow-estimator==2.1.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
torch==1.3.1
torchvision==0.4.2
tornado==6.0.3
tqdm==4.44.1
traitlets==4.3.3
Twisted==19.10.0
txaio==18.8.1
typed-ast==1.4.0
typing-extensions==3.7.4.1
typing-inspect==0.5.0
urllib3==1.25.7
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==1.0.1
wheel==0.33.6
widgetsnbextension==3.5.1
wrapt==1.11.2
zipp==0.6.0
zope.interface==4.7.1

``````

Process finished with exit code 0`

Installed with pip in virtual environment python3.7 .

**Comment by wchargin** [comment] 2020-05-06 15:53
Hi @kkelchte! Thanks for the report, and sorry for the trouble. This is
a known incompatibility between specifically versions 2.1.x of
TensorBoard and version 1.6.0post2 of the standalone What-If Tool
package (`tensorboard-plugin-wit`). Could you please upgrade the What-If
Tool to the latest version—currently `1.6.0post3`—and try again?

You should be able to run the following inside your virtualenv:

    pip install -U tensorboard-plugin-wit

**Comment by wchargin** [comment] 2020-05-14 06:21
Duplicate of #3460

**Closed** 2020-05-14 06:21 UTC
Labels: type:support
