### ISSUE TITLE
Ability to copy a link to a particular run selection state

### ISSUE THREAD

**Issue by talesa** [tensorflow/tensorboard#154] opened 2017-06-24 16:15 UTC
Feature request:
There is a runSelectionState variable in the url when accessing Tensorboard through the browser, but when you copy and paste the url (e.g. share it) it doesn't influence the run selection state after loading the website, it is set to default.
It would be great to be able to save or share a link to a particular selection of runs in Tensorboard.

Thanks!

**Comment by wchargin** [comment] 2017-07-10 17:48
I'm not able to reproduce this: the run selection state persists correctly for me on latest master and with TensorBoard 55 from pip. I'm pasting the URLs into an incognito window, so there shouldn't be any state contamination.

If you're still having this issue, could you provide the details of your setup? (TensorFlow and TensorBoard versions, how you're launching TensorBoard, and what browser(s) you're using?)

**Comment by psybuzz** [comment] 2021-01-23 02:42
I'm also unable to reproduce this as well.  Closing the issue for now, but please feel free to comment if you have more info and are still seeing this.

**Closed by psybuzz** 2021-01-23 02:42 UTC
Labels: core:frontend, type:bug
