### ISSUE TITLE
Dark Mode please - reduce eye strain

### ISSUE THREAD

**Issue by jheffez** [tensorflow/tensorboard#3173] opened 2020-01-24 18:13 UTC
I've been using Dark Mode browser extension to make it easier to view and reduce eye strain. Since TF 1.15 the extension stopped working. 
It would be greatly appreciated to have dark mode or correct the issue introduced in 1.15 to allow the dark mode extension to start working again.

Thanks,
Jake

**Comment by stephanwlee** [comment] 2020-02-04 17:17
Duplicate of #1277.

Do note that the ShadowDOM Polymer uses make theming quite tricky especially for something like the Chrome extension. You can still use `filter: invert(1);` on HTML to achieve the minimal "viable" dark theming.

**Closed by stephanwlee** 2020-02-04 17:17 UTC
Labels: stat:awaiting tensorflower, type:browser, type:feature
