### ISSUE TITLE
Loading tf.function graph fails with 404

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorboard#2203] opened 2019-05-07 10:03 UTC
- TensorBoard version (from pip package, also printed out when running `tensorboard`) TensorBoard 1.14.0a20190301
 - TensorFlow version if different from TensorBoard 2.0-alpha
 - OS Platform and version (e.g., Linux Ubuntu 16.04) Win10
 - Python version (e.g. 2.7, 3.5) 3.7.3
 
I tried exporting a graph with:
```python
@tf.function
def train_step(data):
  ...

self.summary_writer = tf.summary.create_file_writer(self.summary_dir)
tf.summary.trace_on()
train_step(data)
with self.summary_writer.as_default():
     tf.summary.trace_export("graph", 0)
     tf.summary.flush(self.summary_writer)
```

The existence of a graph file is recognized by tensorboard but it fails to load it with a 404.
![grafik](https://user-images.githubusercontent.com/9438971/57291137-23036400-70bf-11e9-91b0-d7280c76285c.png)

My event file is (just download it and remove `.zip` at the end, github does not support `.v2` file upload)
[events.out.tfevents.1557222506.HIDDEN.9596.173.v2.zip](https://github.com/tensorflow/tensorboard/files/3151955/events.out.tfevents.1557222506.HIDDEN.9596.173.v2.zip)
Tensorboard console output: `... 13396 _internal.py:122] ::1 - - [07/May/2019 12:01:49] "?[33mGET /data/plugin/graphs/graph?conceptual=false&run=gan%5Cunconditioned%5Cmnist%5Csummary&tag=graph HTTP/1.1?[0m" 404 -`

I don't really have a clue why it does not work. I also tried with a toy example and that worked.

```python
import tensorflow as tf

@tf.function
def graph():
    a = tf.ones([10,10])
    b = tf.ones([10,10])
    return a * b

w = tf.summary.create_file_writer('models/')

tf.summary.trace_on()
graph()
with w.as_default():
    tf.summary.trace_export('graph', 0)
```

**Comment by stephanwlee** [comment] 2019-05-07 15:16
HI @sleighsoft, thanks a lot for very thorough report. I was able to reproduce this.

First off, I will recommend you to upgrade the tb-nightly to the latest with `pip install -U tb-nightly`. Your current version is stuck on one from March 1st.

In more recent version, with your event file, you will see this
![image](https://user-images.githubusercontent.com/2547313/57311285-33581680-70a0-11e9-95d6-c2903a49d72e.png)

Above error happens when TensorBoard fails to safely reconcile multiple graphs collected from a trace and this often happens when you invoke multiple tf.functions. If your upper example snippet a complete copy-paste or is it a contrived example?

Thanks!

**Comment by sleighsoft** [comment] 2019-05-08 09:08
Hi @stephanwlee, thanks for the tip of upgrading. 
This is the install output
```bash
ERROR: tensorflow 2.0.0a0 has requirement tb-nightly<1.14.0a20190302,>=1.14.0a20190301, but you'll have tb-nightly 1.14.0a20190507 which is incompatible.
Installing collected packages: tb-nightly
  Found existing installation: tb-nightly 1.14.0a20190301
    Uninstalling tb-nightly-1.14.0a20190301:
      Successfully uninstalled tb-nightly-1.14.0a20190301
Successfully installed tb-nightly-1.14.0a20190507
```

It is a contrived example. Basically what I do is the folllowing.
```python
import tensorflow as tf

model = MyModel() # a subclass of tf.keras.Model
model2 = OtherModel() # a subclass of tf.keras.Model

@tf.function
def train_step(data):
    output = model(data)
    output = model2(output)
    return output

w = tf.summary.create_file_writer('models/')

dataset = Dataset() # a tf.data.Dataset

step = 0
for data in dataset:
   if step == 0:
    tf.summary.trace_on()
    train_step(data)
    with w.as_default():
       tf.summary.trace_export('graph', 0)
   else:
     train_step(data)
   step += 1
```

Hope that helps. I am not running multiple `tf.functions` unless `keras.Model` does that internally

**Comment by stephanwlee** [comment] 2019-05-09 22:16
Sorry for delayed response. Computer "crashed" and my response got lost :\

```py
import numpy as np
import tensorflow as tf

input1 = tf.keras.Input(shape=[4])
dense_layer = tf.keras.layers.Dense(4)

output1 = dense_layer(input1)

input2 = tf.keras.Input(shape=[4])
dense_2_layer = tf.keras.layers.Dense(2)
output2 = dense_2_layer(input2)

model = tf.keras.Model(inputs=[input1],
                       outputs=[output1])
model2 = tf.keras.Model(inputs=[input2],
                       outputs=[output2])

num_examples = 8
xs1 = np.zeros([num_examples, 4])
xs2 = np.ones([num_examples, 4])
xs3 = np.ones([num_examples, 4])


@tf.function
def train_step(x1):
  output = model(x1)
  output = model2(output)

w = tf.summary.create_file_writer('res')

step = 0
for data in [xs1, xs2, xs3]:
   if step == 0:
    tf.summary.trace_on()
    train_step(data)
    with w.as_default():
       tf.summary.trace_export('graph', 0)
   else:
     train_step(data)
   step += 1
```

I do not know what I am doing differently but I can't seem to reproduce the issue. Struggling to reproduce, I looked into how our graph plugin is reading your event file and there seems to be multiple graph defs (two, specifically) inside the RunMetadata. 

I do not know how I can better debug without more tangible example :(

**Comment by sleighsoft** [comment] 2019-05-10 10:39
I cannot come up with a better example right now.
I'll try to spend some time on this over the weekend.

**Comment by rmothukuru** [comment] 2019-07-25 11:05
@sleighsoft ,
Can you please provide the example requested by @stephanwlee. Thanks!

**Comment by sleighsoft** [comment] 2019-07-25 14:07
Sorry for the long wait. It was part of a larger project I was working on and pulling out individual pieces to reproduce this is very diffcult + I currently don't have time to look into this again. If you don't mind leave the issue open, otherwise I would propose closing this issue and if I get time to look into it again I will ask for this issue to be re-opened and post my new results.

**Comment by rmothukuru** [comment] 2019-07-29 06:14
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-07-29 06:14 UTC
Labels: plugin:graph, stat:awaiting response, type:support
