### ISSUE TITLE
ValueError no recognised filesystem for prefix E

### ISSUE THREAD

**Issue by dumbledad** [tensorflow/tensorboard#4080] opened 2020-08-25 16:18 UTC
## Environment information (required)

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 724b56cee52e7d8eb89bbeec1f0d5ce3e38c9682

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
INFO: os.name: nt
INFO: os.uname(): N/A
INFO: sys.getwindowsversion(): sys.getwindowsversion(major=10, minor=0, build=19041, platform=2, service_pack='')

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.3.0
INFO: installed: tb-nightly==2.4.0a20200818
WARNING: conflicting installations: ['tb-nightly', 'tensorboard']
INFO: installed: tensorflow==2.3.0
INFO: installed: tensorflow-estimator==2.3.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.3.0'

--- check: tensorflow_python_version
Traceback (most recent call last):
  File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "diagnose_tensorboard.py", line 487, in main
    suggestions.extend(check())
  File "diagnose_tensorboard.py", line 78, in wrapper
    result = fn()
  File "diagnose_tensorboard.py", line 270, in tensorflow_python_version
    import tensorflow as tf
  File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

--- check: tensorboard_binary_path
INFO: which tensorboard: b'C:\\Users\\timregan\\Miniconda3\\envs\\talia38\\Scripts\\tensorboard.exe\r\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 1024>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 1024>
Loopback infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET6: 23>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('::', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 0, '', ('0.0.0.0', 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'timwinvm2.vpvcaufv24te1f5yagntkivxph.ax.internal.cloudapp.net'

--- check: stat_tensorboardinfo
INFO: directory: C:\Users\timregan\AppData\Local\Temp\.tensorboard-info
INFO: .tensorboard-info directory does not exist

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['C:\\Users\\timregan\\Miniconda3\\envs\\Talia38\\lib\\site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.9.0
adal==1.2.4
applicationinsights==0.11.9
argon2-cffi @ file:///C:/ci/argon2-cffi_1596828585465/work
astroid @ file:///C:/ci/astroid_1592487315634/work
astunparse==1.6.3
attrs==19.3.0
azure-common==1.1.25
azure-core==1.8.0
azure-graphrbac==0.61.1
azure-identity==1.2.0
azure-mgmt-authorization==0.61.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-keyvault==2.2.0
azure-mgmt-resource==10.2.0
azure-mgmt-storage==11.1.0
azureml==0.2.7
azureml-automl-core==1.11.0
azureml-core==1.11.0.post1
azureml-dataprep==2.0.7
azureml-dataprep-native==20.0.2
azureml-dataset-runtime==1.11.0.post1
azureml-pipeline==1.11.0
azureml-pipeline-core==1.11.0
azureml-pipeline-steps==1.11.0
azureml-sdk==1.11.0
azureml-telemetry==1.11.0
azureml-tensorboard==1.11.0
azureml-train==1.11.0
azureml-train-automl-client==1.11.0.post1
azureml-train-core==1.11.0
azureml-train-restclients-hyperdrive==1.11.0
backcall==0.2.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bleach==3.1.5
blinker==1.4
boto==2.49.0
boto3==1.14.47
botocore==1.17.47
brotlipy==0.7.0
cachetools @ file:///tmp/build/80754af9/cachetools_1596822027882/work
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cloudpickle==1.5.0
colorama==0.4.3
contextlib2==0.6.0.post1
coverage==5.0
cryptography==2.9.2
cycler==0.10.0
Cython==0.29.14
decorator==4.4.2
defusedxml==0.6.0
distro==1.5.0
docker==4.3.0
docutils==0.15.2
dotnetcore2==2.1.14
entrypoints==0.3
fusepy==3.0.1
future==0.18.2
gast==0.3.3
gensim==3.8.3
google-auth @ file:///tmp/build/80754af9/google-auth_1596863485713/work
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio @ file:///C:/ci/grpcio_1597406462198/work
h5py==2.10.0
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
importlib-metadata @ file:///C:/ci/importlib-metadata_1593446511143/work
ipykernel @ file:///C:/ci/ipykernel_1596190155316/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///C:/ci/ipython_1593447482397/work
ipython-genutils==0.2.0
ipywidgets==7.5.1
isodate==0.6.0
isort==4.3.21
jedi==0.17.0
jeepney==0.4.3
Jinja2==2.11.2
jmespath==0.10.0
joblib @ file:///tmp/build/80754af9/joblib_1594236160679/work
jsonpickle==1.4.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1594826976318/work
jupyter-console==6.1.0
jupyter-core==4.6.3
Keras-Preprocessing==1.1.2
keyring @ file:///C:/ci/keyring_1593109799227/work
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
Markdown @ file:///C:/ci/markdown_1597415206643/work
MarkupSafe==1.1.1
matplotlib @ file:///C:/ci/matplotlib-base_1592837548929/work
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.1.0
mkl-random==1.1.0
mkl-service==2.3.0
msal==1.4.3
msal-extensions==0.1.3
msrc-appconfig==0.5.4
msrc-appconfig-param==0.5.4
msrc-azureml-runner==0.5.3
msrest==0.6.18
msrestazure==0.6.4
mypy @ file:///tmp/build/80754af9/mypy_1593442617121/work
mypy-extensions==0.4.3
nbconvert==5.6.1
nbformat==5.0.7
ndg-httpsclient==0.5.1
networkx==2.5
notebook @ file:///C:/ci/notebook_1596840175976/work
numpy @ file:///C:/ci/numpy_and_numpy_base_1596215850360/work
oauthlib==3.1.0
olefile==0.46
onnx==1.7.0
onnxruntime==1.4.0
opt-einsum==3.3.0
packaging==20.4
pandas==0.25.3
pandocfilters==1.4.2
param==1.9.2
parso @ file:///tmp/build/80754af9/parso_1596826841367/work
pathspec==0.8.0
pickleshare==0.7.5
Pillow @ file:///C:/ci/pillow_1594298230227/work
pip==20.2.2
portalocker==1.7.1
prometheus-client==0.8.0
prompt-toolkit==3.0.5
protobuf==3.12.4
psutil==5.7.0
pyarrow==0.17.1
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
Pygments==2.6.1
PyJWT==1.7.1
pylint @ file:///C:/ci/pylint_1592482039483/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
pyparsing==2.4.7
pyro-api==0.1.2
pyro-ppl==1.4.0
pyrsistent==0.16.0
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2020.1
pywin32==227
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==5.3.1
pyzmq==19.0.1
qtconsole @ file:///tmp/build/80754af9/qtconsole_1592848611704/work
QtPy==1.9.0
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
requests-oauthlib==1.3.0
rsa @ file:///tmp/build/80754af9/rsa_1596998415516/work
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
s3transfer==0.3.3
scikit-learn @ file:///C:/ci/scikit-learn_1592853510272/work
scipy @ file:///C:/ci/scipy_1592916963468/work
seaborn==0.10.1
SecretStorage==3.1.2
Send2Trash==1.5.0
setuptools==49.6.0.post20200814
sip==4.19.13
six==1.15.0
smart-open==2.1.0
tabulate==0.8.7
tb-nightly==2.4.0a20200818
tensorboard==2.3.0
tensorboard-plugin-wit==1.6.0
tensorflow==2.3.0
tensorflow-estimator==2.3.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
toml @ file:///tmp/build/80754af9/toml_1592853716807/work
torch @ file:///C:/ci/pytorch_1596373105144/work
torchfile==0.1.0
torchvision==0.7.0
tornado==6.0.4
tqdm==4.48.2
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1592847887441/work
urllib3 @ file:///tmp/build/80754af9/urllib3_1597086586889/work
visdom==0.1.8.9
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
websocket-client==0.57.0
Werkzeug==1.0.1
wheel==0.34.2
widgetsnbextension==3.5.1
win-inet-pton==1.1.0
wincertstore==0.2
wrapt==1.11.2
yolk3k==0.9
zipp==3.1.0

``````

## Issue description

In Python 3.8 on Windows we have been using foward-slash as the path component separator without issue until now. For example `Path('E://Data/rf').mkdir(exist_ok=True)` makes the directory `E:\\Data\rf`

But initialising [torch.utils.tensorboard.writer.SummaryWriter](https://pytorch.org/docs/master/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter) throws an odd error:

 - `SummaryWriter(log_dir=r'E:\\Data\rf')` works fine, but
 - `SummaryWriter(log_dir=r'E://Data/rf')` throws the error

> ValueError: No recognized filesystem for prefix E  

Here's the full stack, after our code hands off to tensorboard

    File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\torch\utils\tensorboard\writer.py", line 225, in __init__  
    self._get_file_writer()  
    File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\torch\utils\tensorboard\writer.py", line 255, in _get_file_writer  
    self.file_writer = FileWriter(self.log_dir, self.max_queue,  
    File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\torch\utils\tensorboard\writer.py", line 65, in __init__  
    self.event_writer = EventFileWriter(  
    File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 76, in __init__  
    if not tf.io.gfile.exists(logdir):  
    File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 613, in exists  
    return get_filesystem(filename).exists(filename)  
    File "C:\Users\timregan\Miniconda3\envs\Talia38\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 81, in get_filesystem  
    raise ValueError("No recognized filesystem for prefix %s" % prefix)  
    ValueError: No recognized filesystem for prefix E 

One explanation (from the source code [here](https://github.com/tensorflow/tensorboard/blob/34741671ccd49f37ab58e9a064e09bddbc841487/tensorboard/compat/tensorflow_stub/io/gfile.py#L72) via a comment [here](https://stackoverflow.com/q/63582210/575530)) is that Tensorboard is checking for the presense of `://` and then not understanding the drive letter prefix.

    def get_filesystem(filename):
        """Return the registered filesystem for the given file."""
        filename = compat.as_str_any(filename)
        prefix = ""
        index = filename.find("://")
        if index >= 0:
            prefix = filename[:index]
        fs = _REGISTERED_FILESYSTEMS.get(prefix, None)
        if fs is None:
            raise ValueError("No recognized filesystem for prefix %s" % prefix)
        return fs

**Comment by bileschi** [comment] 2020-08-26 14:29
Thank you for the comprehensive issue description.  We will look into reproducing the error.

**Comment by nfelt** [comment] 2020-08-26 18:42
As you've surmised, this happens because the filesystem layer supports URI scheme prefixes, and specifying `E://...` makes it look like a URI scheme.

Is there a reason you need both slashes?  Could you equivalently use `E:/...`?

If not, I think we'd probably accept a contribution to allow a pass-through URI scheme like `file://` so that you could escape the rest from scheme interpretation, e.g. `file://E://Data/rf`.

**Comment by rmothukuru** [comment] 2020-12-04 12:45
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-12-04 12:45 UTC
Labels: core:backend, os:windows, stat:awaiting tensorflower, type:bug
