### ISSUE TITLE
Consider adding a plugin for confusion matrices.

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#368] opened 2017-08-16 09:26 UTC
Several folks have asked for [confusion matrices](https://en.wikipedia.org/wiki/Confusion_matrix) to be supported in TensorBoard. Currently, some folks use the image dashboard to hack out a confusion matrix:

<img width="362" alt="screen shot 2017-08-16 at 12 39 31 am" src="https://user-images.githubusercontent.com/4221553/29356731-0c46aa2c-822a-11e7-9010-5c487bd3484c.png">

And one could theoretically use the text dashboard, but that's suboptimal for visualizing the values. And of course, one has to code the formatting for the table that is the matrix.

**Comment by wchargin** [comment] 2017-08-17 16:36
What's hacky about using the image dashboard?

**Comment by chihuahua** [comment] 2017-08-17 17:33
The image dashboard's fine for some cases - the user just doesn't get the numeric values (without say examining pixel value). And it's hard to compare colors sometimes.

**Comment by hkhatod** [comment] 2017-12-29 00:54
The "text summary" of confusion is matrix is OK but not intuitive enough...A plugin that could combine the 
 image and numbers would be useful.

**Comment by hkhatod** [comment] 2017-12-29 00:55
```
	with tf.name_scope('confusion_matrix'):
				self.confusion_matrix = tf.as_string(tf.confusion_matrix(self.currect_ans, self.predictions, num_classes=num_classes, name='Confusion'))



          confusion_mat =tf.summary.text("confusion_matrix",cnn_rnn.confusion_matrix)
```

**Comment by hkhatod** [comment] 2017-12-29 12:50
we need this in tensorflow https://rare-technologies.com/wp-content/uploads/2017/10/facets_dive_20newsgroups-widget_only.html

**Comment by benprofessionaledition** [comment] 2018-01-24 02:06
This guy made something cool but it looks like he uses sklearn's confusion matrix instead of tensorflow's for some reason: https://stackoverflow.com/a/48030258/4449954

@wchargin using the image dashboard to display a confusion matrix is hacky because it's not the apparent intended use case of the image dashboard nor a confusion matrix, i.e. a hack 😃

**Comment by hkhatod** [comment] 2018-01-24 14:19
@benprofessionaledition  I am the "this guy".  I tried to used tf cm but getting it to matplotlib was bit of pain. I would love to have it all in the tf graph is possible. Please improve upon my solution.

**Comment by nfelt** [comment] 2020-10-24 00:44
Duplicate of #227

**Comment by nfelt** [comment] 2020-10-24 00:44
Closing in favor of https://github.com/tensorflow/tensorboard/issues/227 which has a bit more overall activity and was opened earlier.

**Closed by nfelt** 2020-10-24 00:44 UTC
Labels: type:feature (new plugin)
