### ISSUE TITLE
Enhancement: Remove ability to zoom in and out of charts without shift-holding

### ISSUE THREAD

**Issue by ShaneSmiskol** [tensorflow/tensorboard#2339] opened 2019-06-10 20:12 UTC
For me, when I'm scrolling through my TensorBoard page, it seems to still zoom the graphs as I'm scrolling which is really annoying when you have the graph exactly how you like it. To avoid this I have to place my mouse in the small white section on the left to scroll and avoid changing the views on my graphs. Here's a video showing the bug: https://streamable.com/5sp0g

**Comment by stephanwlee** [comment] 2019-06-10 21:16
Duplicate of #2214. Should be addressed by #2221.

**Closed by stephanwlee** 2019-06-10 21:16 UTC
Labels: core:frontend, stat:awaiting tensorflower, type:feature
