### ISSUE TITLE
Tensorboard not showing whole results

### ISSUE THREAD

**Issue by lucadigiammarino** [tensorflow/tensorboard#991] opened 2018-02-22 11:42 UTC
I've trained a DQN for a Reinforcement Learning project. For this I've used a remote server. After 1 night of iterations I've copied the folder locally and explored the summaries in tensorboard.

I've noticed that in this static conditions (the summary files don't get updated anymore) tensorboard keeps updating my result as usual every 30 seconds.

To make it clear I'll do an example. I've started iterating at 17.30 of Day 1 until 8.00 of Day 2. My tensorboard right now after 15 minutes, shows results from 17.30 til 21.00.

There is actually a way to show the complete result? Or do I need to wait in order to allow tensorboard reading the file completely?

I had a look on the documentation and it seems like there is not a solution. But I am still confused.

From Tensorboard Github Official:

_TensorBoard is showing only some of my data, or isn't properly updating!
This issue usually comes about because of how TensorBoard iterates through the tfevents files: it progresses through the events file in timestamp order, and only reads one file at a time. Let's suppose we have files with timestamps a and b, where a<b. Once TensorBoard has read all the events in a, it will never return to it, because it assumes any new events are being written in the more recent file. This could cause an issue if, for example, you have two FileWriters simultaneously writing to the same directory. If you have multiple summary writers, each one should be writing to a separate directory._

Could anyone clarify this issue? I am new with Tensorflow.

Thank you in advance

**Comment by nfelt** [comment] 2018-02-22 18:04
Roughly how much data do you have?  If it's a lot, sometimes loading fully can take quite a long time.  I agree that in your case the FAQ answer probably isn't relevant since you're running off a static copy of the files.

If the summary data isn't that large, is there some way you could share it or some subset of it that reproduces this issue?  If that's not possible, could you instead try running `tensorboard --inspect --logdir=<logdir>` and provide the output from that command?

**Comment by nikhilsaldanha** [comment] 2018-10-05 01:04
@lucadigiammarino Did you manage to fix this? I'm having the same problem. Essentially, the tensorboard is loading the results over time, as it would appear when the model is training. So I have to wait for as long as the model took to train to observe all the metrics.

**Comment by lucadigiammarino** [comment] 2018-10-05 12:59
No, I still have no idea of what is going on. I've tried TB for different projects and it does not often have this behaviour.

On Oct 5, 2018, at 3:04 AM, Nikhil Saldanha <notifications@github.com<mailto:notifications@github.com>> wrote:


@lucadigiammarino<https://github.com/lucadigiammarino> Did you manage to fix this? I'm having the same problem. Essentially, the tensorboard is loading the results over time, as it would appear when the model is training. So I have to wait for as long as the model took to train to observe all the metrics.

**Comment by gowtham-kp** [comment] 2019-07-31 23:17
@lucadigiammarino Are you still facing the issue? If you have resolved it, can you post the solution for the issue. Thanks!

**Comment by tiancaipipi110** [comment] 2019-08-09 08:07
Just encountered the same issue, fixed by `Ctrl+C` to quit the current console session, then do `tensorboard --logdir=<MyDataDir>`

**Comment by bileschi** [comment] 2020-01-02 19:32
I wonder if this was related to some of the memory leak issues that were recently fixed?  Closing for now.  Please re-open if you still encounter this issue.  Thanks!

**Closed by bileschi** 2020-01-02 19:32 UTC
Labels: stat:awaiting response, type:support

**Comment by RishikMani** [comment] 2020-06-28 15:09
Unfortunately, in my case it is only loading partial data. At every 500th iteration I save the model. Currently, my directory has model-49500.* and model-50000.* files, but on running tensorboard I do not see the whole summary.

The output of `tensorbaord --inspect --logdir=train_dir` is as follows:
```
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

Found event files in:
train_dir\baseline-20200626-165240
train_dir\rn-20200626-153759

These tags are in train_dir\baseline-20200626-165240:
audio -
histograms -
images -
scalars
   accuracy_1
   cross_entropy
   optimizer_loss/global_norm/clipped_gradient_norm
   optimizer_loss/global_norm/gradient_norm
   optimizer_loss/loss
tensor -
======================================================================

Event statistics for train_dir\baseline-20200626-165240:
audio -
graph -
histograms -
images -
scalars
   first_step           1
   last_step            11460
   max_step             11460
   min_step             1
   num_steps            11460
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================

These tags are in train_dir\rn-20200626-153759:
audio -
histograms -
images -
scalars
   accuracy_1
   cross_entropy
   optimizer_loss/global_norm/clipped_gradient_norm
   optimizer_loss/global_norm/gradient_norm
   optimizer_loss/loss
tensor -
======================================================================

Event statistics for train_dir\rn-20200626-153759:
audio -
graph -
histograms -
images -
scalars
   first_step           1
   last_step            10985
   max_step             10985
   min_step             1
   num_steps            10985
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -
======================================================================
```

I do not understand why the models do not show the last step as 50000. Could anyone help me with this issue?

**Comment by nfelt** [comment] 2020-06-30 02:10
Hi - please file a new issue (https://github.com/tensorflow/tensorboard/issues/new/choose) with the details from the issue template and any steps needed to reproduce the problem. Thanks!

**Comment by gingsi** [comment] 2020-12-03 13:33
Here is the link to the new issue that was created: https://github.com/tensorflow/tensorboard/issues/3771

**Comment by tamurajunichi** [comment] 2021-11-18 10:11
I was faced with the same problem.
In my environment, after connecting to the local host, it seems to gradually load the entire file by pressing the Update button in the upper right corner. However, this takes a long time.
