### ISSUE TITLE
feature request: only show tag/summries in current run

### ISSUE THREAD

**Issue by weiliu620** [tensorflow/tensorboard#351] opened 2017-08-14 15:51 UTC
When tensorboard shows multiple runs, it shows all tags in all runs. So, if run A has tag a but not tag b, run B has tag B but not a, tensorboard shows both a and b even I only check run A on left side. 

Is it easy to only show those tags specific to current runs (those checked on the left)?

**Comment by chihuahua** [comment] 2017-08-15 22:34
To make sure I'm understanding this issue correctly, let me repeat it with an example.

When no runs are selected (or there are no runs for a tag), the scalars dashboard today still shows all charts, as this screenshot demonstrates.

![xeq6tun9tai](https://user-images.githubusercontent.com/4221553/29339439-1ad13004-81cf-11e7-90cc-53e07d4d8077.png)

The feature request here is to only show charts with relevant runs selected. Does that sound like a correct description? Thanks!

If so, I wonder how we can design this feature so that charts don't shift too much when the user toggles runs.

**Comment by weiliu620** [comment] 2017-08-17 13:04
Yes, I think that's a correct description of the request. That is, only shows tags corresponding to the runs with a checkmark. 

Sometimes I have previous runs with different tags/charts defined with my latest runs.

**Comment by wchargin** [comment] 2017-08-17 16:37
Thanks for the suggestion. This is a duplicate of https://github.com/tensorflow/tensorboard/issues/170; please see discussion there.

**Closed by wchargin** 2017-08-17 16:37 UTC
