### ISSUE TITLE
Windows server, chrome: No edges shown in the graph

### ISSUE THREAD

**Issue by wqmike123** [tensorflow/tensorboard#788] opened 2017-12-03 10:57 UTC
when I run the same codes on Ubuntu, there is no problem. But when I run it on the windows server, there is no dataflow edge and reference edge showing up (there is no problem with other parts).

![screenshot from 2017-12-03 11 53 53](https://user-images.githubusercontent.com/14854546/33524628-df4d75b2-d820-11e7-9be3-f96abfd2d682.png)
![screenshot from 2017-12-03 11 54 53](https://user-images.githubusercontent.com/14854546/33524630-df70c490-d820-11e7-9bdf-2815e04b0982.png)

Wondering why this happening... anything to do with the chrome setting?

**Comment by nfelt** [comment] 2017-12-06 03:14
Hm, strange.  What's your TensorBoard version and Chrome version?

**Comment by chihuahua** [comment] 2017-12-06 04:33
See #425. As @nfelt noted, you may need to update the version of TensorBoard on the windows server.

**Comment by nfelt** [comment] 2017-12-06 19:45
I'm actually going to go ahead and close this since it sounds like it's caused by #425 and should be fixed in 0.4.0 onwards.

If you're still experiencing this with 0.4.0+ then feel free to re-open, but as mentioned above, could you provide all relevantTensorBoard and Chrome versions and also clarify whether by Ubuntu vs Windows Server you are referring to the platform on which TensorBoard is running, the platform on which you're using Chrome, or both?

**Closed by nfelt** 2017-12-06 19:45 UTC
Labels: (╯°□°)╯windows, plugin:graph, type:bug/performance

**Comment by wqmike123** [comment] 2017-12-10 10:20
hi @nfelt , thanks a lot for your kind help! 
the chrome is v 62.0.3202.94 (quite updated).. and the tb is 0.1.5.. i update it to 0.1.8 then it works..
really appreciate : )

**Comment by nfelt** [comment] 2017-12-11 19:34
Okay, glad that got it working for you!
