### ISSUE TITLE
tensorboard error while setting log directory

### ISSUE THREAD

**Issue by Deltaidiots** [tensorflow/tensorboard#609] opened 2017-10-03 19:36 UTC
```Traceback (most recent call last):
  File "c:\users\asad hayat\appdata\local\conda\conda\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\asad hayat\appdata\local\conda\conda\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Asad Hayat\AppData\Local\conda\conda\envs\tensorflow\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "c:\users\asad hayat\appdata\local\conda\conda\envs\tensorflow\lib\site-packages\tensorboard\main.py", line 36, in <module>
    from tensorboard.plugins.audio import audio_plugin
  File "c:\users\asad hayat\appdata\local\conda\conda\envs\tensorflow\lib\site-packages\tensorboard\plugins\audio\audio_plugin.py", line 27, in <module>
    from tensorboard import plugin_util
  File "c:\users\asad hayat\appdata\local\conda\conda\envs\tensorflow\lib\site-packages\tensorboard\plugin_util.py", line 21, in <module>
    import bleach
  File "c:\users\asad hayat\appdata\local\conda\conda\envs\tensorflow\lib\site-packages\bleach\__init__.py", line 5, in <module>
    from bleach.linkifier import (
  File "c:\users\asad hayat\appdata\local\conda\conda\envs\tensorflow\lib\site-packages\bleach\linkifier.py", line 6, in <module>
    from html5lib.filters.sanitizer import allowed_protocols
ImportError: cannot import name 'allowed_protocols'``` 

I have just installed  tensorflow 1.3 and got this message when trying to host tensorboard version 0.1.8. I am on Windows. search online but there is no solution on stackoverflow or anywhere else. I believe the latest release has some version errors.

**Comment by chihuahua** [comment] 2017-10-06 01:54
I am going to mark this as a duplicate of #588. If you deem this to be a separate issue, we can reopen.

Feel free to join the discussion at #588.

**Closed by chihuahua** 2017-10-06 01:54 UTC
