### ISSUE TITLE
Name of plot's lines not fully visible

### ISSUE THREAD

**Issue by lcswillems** [tensorflow/tensorboard#1228] opened 2018-06-05 15:21 UTC
I would like to see the name of the blue line, but when I scroll down, it disappears.

![screenshot from 2018-06-05 11-16-57](https://user-images.githubusercontent.com/5437552/40985635-8b66785e-68b2-11e8-86be-93af91e92236.png)

**Comment by nfelt** [comment] 2018-06-05 23:12
Duplicate of #1019 

I think the best way to address this would be something like what #1019 proposes as a feature request, where there's a way to "pin" the pop up so that you can scroll over it, select values from it, and maybe even sort it or download it as the OP on #1019 suggests.

**Comment by nfelt** [comment] 2018-06-05 23:13
Duplicate of #1019

**Closed by nfelt** 2018-06-05 23:13 UTC

**Comment by lcswillems** [comment] 2018-06-06 05:09
Thank you for the answer!
