### ISSUE TITLE
Add an option to disable dimensionality reduction

### ISSUE THREAD

**Issue by smivv** [tensorflow/tensorboard#3656] opened 2020-05-20 08:57 UTC
Hello,

I am logging to projector features, that are already have 2 or 3 dimensions, but I didn't find an option to disable dimensionality reduction for them, so is not possible to see original features.

Could we please elaborate that?

Best regards,
Vladimir.

**Comment by nfelt** [comment] 2020-05-26 22:27
Duplicate of #1192

**Comment by nfelt** [comment] 2020-05-26 22:27
Yes, there's currently no option to do no dimensionality reduction at all - tracked in #1192.

**Closed by nfelt** 2020-05-26 22:27 UTC
Labels: plugin:projector
