### ISSUE TITLE
Run error after building from tensorflow source

### ISSUE THREAD

**Issue by LynnHo** [tensorflow/tensorboard#715] opened 2017-11-09 11:05 UTC
I build tensorflow from source and install the package, and tensorboard is installed together. When I run tensorboard, I get the error:

ERROR:root:Trying to access flag --debugger_data_server_grpc_port before flags were parsed.

**Comment by nfelt** [comment] 2017-11-10 23:21
Thanks for the report, this should be addressed by pending PR #716.

**Comment by taesikna** [comment] 2017-11-15 23:03
I was using tensorflow installed with pip.
And I've installed tensorflow from source today, and I'm also getting the same error when I run tensorboard.
Would you let me know how to fix it?

**Comment by taesikna** [comment] 2017-11-16 16:48
I've downloaded tensorflow_tensorboard-0.4.0rc3-py2-none-any.whl (md5) from https://pypi.python.org/pypi/tensorflow-tensorboard.
Re-installed tensorboard, now it works fine.

**Comment by jart** [comment] 2017-11-16 17:27
Glad to hear it.

**Comment by jart** [comment] 2017-11-16 17:28
Note: This should have only impacted `tf-nightly` users. We're in the process of setting up a `tb-nightly` package, right now, to avoid this happening again in the future.

**Closed by jart** 2017-11-16 17:27 UTC

**Comment by zjpopeye** [comment] 2017-11-22 06:21
@taesikna Thank you!

**Comment by chrisrn** [comment] 2017-12-18 13:16
The problem remains for tf-nightly. Any solution?

**Comment by vspinu** [comment] 2017-12-18 16:28
Building from source and then `bazel-bin/tensorboard/tensorboard --logdir logdir` solved the issue for me.

**Comment by wookayin** [comment] 2018-01-19 22:42
Using Tensorboard 0.4.0 (released stable just 2 days ago) and TensorFlow==1.4.0, still the error presents. FYI: The PR #716 seems to be not a part of 0.4.0 release ...

**Comment by nfelt** [comment] 2018-01-22 23:46
PR #716 should have gone out as part of the 0.4.0 release, see this commit:
https://github.com/tensorflow/tensorboard/commit/cb525a70f3c45863e65fb626506a1ca68721f9db

@wookayin were you building TensorFlow==1.4.0 from source or installing it with pip?  For a pip installation I can't reproduce this issue; it installs tensorflow-tensorboard==0.4.0 as a dependency and it launches without any error for me.

If it's possible for you to give exact steps to reproduce that would be most helpful in tracking this down.

**Comment by wookayin** [comment] 2018-01-22 23:54
I see, I was looking e6c1b4e44 (which is the attached commit in PR and that's why I suspected so) but it seems that later new commit was made.

I wiped everything out from my virtualenv, and reinstalled `tensorflow==1.4.0` and `tensorflow-tensorboard==0.4.0` and now I have no errors. My bad, sorry about that!

**Comment by nfelt** [comment] 2018-01-23 00:08
No problem, glad that it's fixed for you now!

Yeah, the commit SHA-1s are different for the original commit to master (attached to this PR) and the one on the 0.4 release branch (since the release branch one has a different set of ancestor commits).  GitHub could probably do a better job showing a connection between them, but alas it doesn't.
