### ISSUE TITLE
Windows 10. When running tensorboard from different drive of logdir, no data is shown

### ISSUE THREAD

**Issue by mendi80** [tensorflow/tensorboard#432] opened 2017-08-28 06:22 UTC
In process monitor i can see that tensorboard ignore the logdir drive(logdir="Z:/tf/"), and it search for the directory in the drive the tensorboard was launched from (D:/tf/).

**Comment by wchargin** [comment] 2017-08-28 12:40
Thanks for reporting. This is known. It is a duplicate of #52.

**Closed by wchargin** 2017-08-28 12:40 UTC
