### ISSUE TITLE
Tensorboard Embedding training faster r-cnn inception v2

### ISSUE THREAD

**Issue by JoseGnRLuis** [tensorflow/tensorboard#1125] opened 2018-04-11 18:01 UTC
Hello,

I'm using faster_rcnn_inception_v2_coco.config to train a model with my own images.

Using that config, in tensorboard I see the the Projector tab with the PCA and T_SNE visualizations (1024 points and 36 dimension)

How can I create the tsv and sprite to visualize my labels and images there?

I don't know how to extract the features from the Faster r-cnn inception V2 so I could create the tsv and sprite for those 1024 points, or whatever is needed for label and image visualization.

Is there any code, or tutorial for doing this?

Thank you!

**Comment by jart** [comment] 2018-04-20 05:35
This might be a better question for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorboard) since it's not a bug or feature request. There's a larger community there with better searchability.

**Comment by jart** [comment] 2018-04-20 05:36
Re-opening because this was triaged. Please accept my apologies.

**Comment by bileschi** [comment] 2020-01-02 20:11
Closing as a support issue over 1 year old.  Please re-open if this is still an issue.  Thanks!

**Closed by bileschi** 2020-01-02 20:11 UTC
Labels: plugin:projector
