### ISSUE TITLE
Scalar plots should have true log scaling option

### ISSUE THREAD

**Issue by gonnet** [tensorflow/tensorboard#938] opened 2018-02-02 21:39 UTC
Logarithmic scaling for scalar summaries is broken in several ways:

 * Y-axis shows negative values, negative values are plotted as -log(-y).
 * Values are scaled logarithmically down to ~0.1, below that linearly to zero.

![log_scaling_this_is_not](https://user-images.githubusercontent.com/10587723/35755921-7ea460a8-0869-11e8-91da-935ea466a9a3.png)

I'm guessing this was done to make accidental plotting of not strictly positive values less painful for the inexperienced user, but it makes the whole thing kind of useless for the rest of us. E.g. if I have some loss that converges gently towards zero, I'm actually quite interested in seeing how it behaves below 0.1. Plotting values linearly below that range makes them mostly indistinguishable.

Are there any plans to fix this, or can we add a setting to enable genuine logarithmic scaling for non-novice users?

**Comment by nfelt** [comment] 2018-02-22 23:53
Yes, the "log" scale is actually a "ModifiedLog" scale:

"A ModifiedLog Scale acts as a regular log scale for large numbers. As it approaches 0, it gradually becomes linear. Consequently, a ModifiedLog Scale can process 0 and negative numbers."
http://plottablejs.org/docs/classes/plottable.scales.modifiedlog.html

I agree that at a minimum there should be some ability to control the point at which the linearization begins, and probably it would be best to have a true log scale option (though this is a little more work to implement).  Here's a few questions that could help guide what this looks like:

- What should the plots do for 0 values or negative numbers?  Should those just be omitted entirely?  Should there be some kind of warning on the plot?

- Do people think there's any value at all in the existing ModifiedLog scale (maybe with an adjusted base point), i.e. would they want to see two different scale options?  Or is the desire to just replace the current log scale button with a true log scale?

**Comment by shoyer** [comment] 2018-02-23 00:07
> What should the plots do for 0 values or negative numbers? Should those just be omitted entirely? Should there be some kind of warning on the plot?

Simply not showing them would be a reasonable option -- better than what we currently have. It's always easy to switch back to linear scaling if necessary.

I think my favorite option would be ignoring them in setting axis-boundaries and then showing vertical lines diverging off the screen, like matplotlib:
```
>>> import matplotlib.pyplot as plt
>>> plt.semilogy([1, 2, 3, 4, -1, 6, 7, 8, -1, 9, 10])
```
![image](https://user-images.githubusercontent.com/1217238/36570959-5858df5c-17e9-11e8-96fc-bdce3d15665f.png)

One thing that would be best to avoid is simply dropping invalid plots and showing straight lines between the remaining valid values. This could led to the misleading impression that there are no negative values.

> Do people think there's any value at all in the existing ModifiedLog scale (maybe with an adjusted base point), i.e. would they want to see two different scale options?

I have been doing scientific visualization for over a decade now. I've used a log scale many times, but I can only think of one case where I've seen a variation on a modified log-scale used (and it wasn't in machine learning). It's just not a standard visualization technique. So my preference would be to for dropping it entirely, though I would not be strongly opposed to keeping it as an option.

**Comment by gonnet** [comment] 2018-02-23 09:05
> What should the plots do for 0 values or negative numbers? Should those just be omitted entirely? Should there be some kind of warning on the plot?

I'm also for the vertical lines, as suggested by @shoyer, ideally making them dotted :smiley: 

> Do people think there's any value at all in the existing ModifiedLog scale (maybe with an adjusted base point), i.e. would they want to see two different scale options? Or is the desire to just replace the current log scale button with a true log scale?

Good question. I for one will definitely not miss the modified logging if it goes away, but I am only I. One option might be to make the modified log scaling opt-in and to see if anybody notices/complains. Any decision in favour of one or the other could be based on usage statistics.

**Comment by yk5** [comment] 2018-04-19 18:54
Would it be hard to make the button with tri-state (linear/log/modified log) instead of toggling between the two? The Icon would need to be carefully designed though.

**Comment by shoyer** [comment] 2018-04-19 19:38
@yk5 do you have use cases for modified log scaling?

**Comment by yk5** [comment] 2018-04-19 19:49
No, I don't prefer modified log scaling.
I anticipate  true log-scaling, but my point was: if the decision is not
made because of some benefits of modified log scale, I wish to have true
log scaling earlier as a third option instead of later replacing modified
log scaling with it.

**Comment by shoyer** [comment] 2018-04-19 19:55
This issue is a duplicate of https://github.com/tensorflow/tensorboard/issues/938

**Comment by nfelt** [comment] 2018-04-24 23:00
Duplicate of #57 

@shoyer thanks for pointing that out.  Since that issue predates this one by a year, I'll close this one in favor of the pre-existing issue, so please follow along on #57 if interested.

**Closed by nfelt** 2018-04-24 23:00 UTC
Labels: plugin:custom-scalars, plugin:scalars, type:feature
