### ISSUE TITLE
Scalar roll-over boxes incorrectly display values

### ISSUE THREAD

**Issue by ro3c** [tensorflow/tensorboard#452] opened 2017-08-31 16:30 UTC
Attached screenshot shows that the values in the scalar roll-over box are shifted to the left.

![image](https://user-images.githubusercontent.com/14815348/29933574-204946e2-8e46-11e7-8239-62a4e3983437.png)

Problem occurs at all levels of zoom
1.3.0-rc2
OSX 10.12.6
Chrome Browser

**Comment by wchargin** [comment] 2017-08-31 17:26
Duplicate of #451; I responded to you there.

**Closed by wchargin** 2017-08-31 17:26 UTC
