### ISSUE TITLE
tensorboard profiler trace_viewer does not work on firefox

### ISSUE THREAD

**Issue by eyaler** [tensorflow/tensorboard#1291] opened 2018-07-16 10:38 UTC
i am using tensorboard profiler to profile tpus. on chrome everything works. on firefox 61, all tools works except trace_viewer which shows an empty pain after loading

**Comment by nfelt** [comment] 2018-07-16 18:05
cc @qiuminxu

**Comment by qiuminxu** [comment] 2018-07-17 17:32
hi @eyaler, thank you for using the tool. The trace viewer tool in profiler plugins calls [Chrome trace viewer](https://github.com/catapult-project/catapult/blob/master/tracing/README.md) to render the events timeline. Sorry, our trace viewer tool currently only supports Chrome.

**Comment by eyaler** [comment] 2018-07-17 17:35
i see. can this be added to the relevant docs?

**Comment by qiuminxu** [comment] 2018-07-17 17:38
We're adding this to the official [cloud tpu tool docs](https://cloud.google.com/tpu/docs/cloud-tpu-tools).  It should be updated in a few days.

**Comment by stephanwlee** [comment] 2020-05-11 05:58
The issue is now addressed in the [new plugin](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras). Please give the new plugin a try. Thanks!

**Closed by stephanwlee** 2020-05-11 05:58 UTC
Labels: plugin:profile, type:bug
