### ISSUE TITLE
Query the images at a particular step

### ISSUE THREAD

**Issue by szywise** [tensorflow/tensorboard#4074] opened 2020-08-23 17:54 UTC
Tensorboard subsamples images by default, with the subsampling rate controlled by `--samples_per_plugin`.

I would like to inspect any step that I want. This can happen when I find the loss at a particular step is high and want to look at the middle layer outputs to figure out why.

Specifying `--samples_per_plugin images=0` is a solution, but it seems to be loading a lot of data and the images never showed up in the panel.

I think it would be nice to have a query input box beside the slider so that that I can load only the image of one particular step.
![image](https://user-images.githubusercontent.com/19483628/90984764-284f2100-e545-11ea-9a66-cbd1d20a3384.png)

**Comment by bileschi** [comment] 2020-08-24 21:22
Hi @szywise, thank you for your  feature request!

I think I understand, but let me check.  The idea is that the front end will still only upload a subsample, but the user may specify interest in an out-of-sample image by specifically requesting it.  Is that the idea?

**Comment by szywise** [comment] 2020-08-25 17:31
Yes @bileschi, that is what I mean.

**Comment by nfelt** [comment] 2021-04-21 20:41
Duplicate of #1012

**Comment by nfelt** [comment] 2021-04-21 20:41
Belated but it looks like #1012 covers this, and it's older, so deduping to that one.

**Closed by nfelt** 2021-04-21 20:41 UTC
Labels: plugin:images, stat:awaiting response, type:feature
