### ISSUE TITLE
Binary histograms are smoothed when displayed

### ISSUE THREAD

**Issue by daganesh** [tensorflow/tensorboard#1015] opened 2018-03-05 14:28 UTC
When binary histograms (labels) are displayed, the graph shows several values, and not only 0 and 1.
This is true even if I move the values a little bit (e.g. to 0.1 and 0.9) and turn off smoothing in the Scalar page.
It seems as if there is some smoothing on the values, which creates a "hill" instead of a single peak.

I am using tensorboard 1.5.0 on FireFox

![image](https://user-images.githubusercontent.com/14297886/36979947-9f8eb29c-2091-11e8-9362-21b728f2b588.png)

**Comment by nfelt** [comment] 2018-05-18 02:39
Hmm, I agree this is weird, though it might be a bit tricky to fully fix.  For now, if you're still having this issue, you might try using `tb.summary.histogram` from TensorBoard itself.  I think as long as you stick to binary histograms, that should avoid this type of artifact (though I have not actually tried it).

**Comment by nfelt** [comment] 2019-12-17 22:21
Duplicate of #1803 - that issue is more general and I think covers this case as well as more general problems with the histogram binning and smoothing, please follow along there.

**Closed by nfelt** 2019-12-17 22:21 UTC
Labels: plugin:histogram, type:bug
