### ISSUE TITLE
Add visual indication that parsing isn't complete for some logs

### ISSUE THREAD

**Issue by yfarjoun** [tensorflow/tensorboard#668] opened 2017-10-21 10:21 UTC
When launching tensorflow with a logdir that contains logs from several runs, it reports their presence in the side-bar but until it has completed parsing the logs, data is still not presented. Since there is no indication of the parsing, this can lead to time lost trying to debug a problem that doesn't exists...if one resorts to restarting tensorflow this only exacerbates the problem, obviously.

A visual indication would go a long way in alleviating this problem. For example, the logs in the side-bar could be pale, or grayed out, until their data is loaded with hover-text explaining what's going on. 

Thanks for your work on this project. It makes using TensorFlow much more pleasant!

**Comment by nfelt** [comment] 2017-10-23 21:54
I agree that this would be very useful, and was actually thinking about this myself - whether maybe there should be a little loader gif or something to indicate that they aren't fully loaded yet.  Graying out the name would be an even easier solution, though.  I'll take a look at fixing this when I get a chance.

**Comment by nfelt** [comment] 2018-06-07 21:07
Duplicate of https://github.com/tensorflow/tensorboard/issues/65

**Comment by nfelt** [comment] 2018-06-07 21:07
Looks like this is mostly a duplicate of #65, so closing in favor of that existing issue.

**Closed by nfelt** 2018-06-07 21:07 UTC
