### ISSUE TITLE
Monitor tf placeholder using summary

### ISSUE THREAD

**Issue by Enigma-li** [tensorflow/tensorboard#217] opened 2017-07-11 13:12 UTC
Hi,

I encountered strange problems using tensorboard to monitor arbitrary variables, the code is simple like:
```py
import tensorflow as tf


def train():

    test_val = tf.placeholder(tf.float32, name='tmp1')
    tf.summary.scalar('tmp1', test_val)

    test_val2 = tf.placeholder(tf.float32, name='tmp2')
    tf.summary.scalar('tmp2', test_val2)

    sess = tf.InteractiveSession()

    merged = tf.summary.merge_all()
    train_writer = tf.summary.FileWriter('fuck', sess.graph)
    tf.global_variables_initializer().run()

    summary, val1 = sess.run([merged, test_val], feed_dict={'tmp1:0': 1.0})
    train_writer.add_summary(summary)
    print('Val1: %f' % val1)

    summary2, val2 = sess.run([merged, test_val2], feed_dict={'tmp2:0': 2.0})
    train_writer.add_summary(summary2)
    print('Val2: %f' % val2)


if __name__ == '__main__':
    train()
```
And the error message is:
```
Traceback (most recent call last):
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'tmp2' with dtype float
	 [[Node: tmp2 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/v/Desktop/CNN_test/tf_test.py", line 30, in <module>
    train()
  File "C:/Users/v/Desktop/CNN_test/tf_test.py", line 19, in train
    summary, val1 = sess.run([merged, test_val], feed1)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'tmp2' with dtype float
	 [[Node: tmp2 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'tmp2', defined at:
  File "C:/Users/v/Desktop/CNN_test/tf_test.py", line 30, in <module>
    train()
  File "C:/Users/v/Desktop/CNN_test/tf_test.py", line 9, in train
    test_val2 = tf.placeholder(tf.float32, name='tmp2')
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1530, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1954, in _placeholder
    name=name)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Dev\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'tmp2' with dtype float
	 [[Node: tmp2 = Placeholder[dtype=DT_FLOAT, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```
Could you please help?

Thanks

**Comment by wchargin** [comment] 2017-07-11 17:43
Look at the last line of the error. You will see the message:
> You must feed a value for placeholder tensor 'tmp2' with dtype float

This tells you precisely what the problem is.

I highly recommend using tensors instead of strings for your keys in the feed dict. For instance, your feed dict here should be `{test_val1: 1.0, test_val2: 2.0}`. This way, you don't have to worry about where the TensorFlow backend adds `:0` suffixes to deduplicate names.

**Comment by Enigma-li** [comment] 2017-07-12 02:04
Thanks.

I know what you mean and I tried that if I put the two together by feeding dict {test_val1: 1.0, test_val2: 2.0}, it works. But the question is that when I divided them into two parts, as what I write, it will tell me that the second one must feed a value. So I was wondering do it mean that we cannot add another free variable monitoring in tensorboard?

Thanks

**Comment by dandelionmane** [comment] 2017-07-12 04:02
You are trying to run the merged_summary at each step, which depends on both placeholders, but you are only feeding one value at a time. So it fails.

The following code would work:

```python
import tensorflow as tf


def train():

    test_val = tf.placeholder(tf.float32, name='tmp1')
    summary_1 = tf.summary.scalar('tmp1', test_val)

    test_val2 = tf.placeholder(tf.float32, name='tmp2')
    summary_2 = tf.summary.scalar('tmp2', test_val2)

    sess = tf.InteractiveSession()

    train_writer = tf.summary.FileWriter('be_polite', sess.graph)
    tf.global_variables_initializer().run()

    summary, val1 = sess.run([summary_1, test_val], feed_dict={'tmp1:0': 1.0})
    train_writer.add_summary(summary)
    print('Val1: %f' % val1)

    summary2, val2 = sess.run([summary_2, test_val2], feed_dict={'tmp2:0': 2.0})
    train_writer.add_summary(summary2)
    print('Val2: %f' % val2)


if __name__ == '__main__':
    train()
```

**Closed by dandelionmane** 2017-07-12 04:02 UTC

**Comment by Enigma-li** [comment] 2017-07-12 06:11
Thanks a lot. It works.

Sorry that I did not mind the folder name, very sorry about that.

Thanks again.
