### ISSUE TITLE
Data download for distributions/histograms

### ISSUE THREAD

**Issue by sebastienwood** [tensorflow/tensorboard#3543] opened 2020-04-23 15:52 UTC
Hi !
I've been finding the tool to visualize the histograms/distributions really handy to run a visual data analysis. However, when it comes to using these distributions plots outside of Tensorboard, there is no data download link as there could be for logged scalars.

A quick workaround is to log scalar at the same time as logging the histogram, but it is still a bit painful.

Is there a possibility to bring the data download feature to these other tabs ? Thanks ! :)

**Comment by psybuzz** [comment] 2020-04-23 17:15
Thank you for the report!  I agree, the workaround of logging a scalar each time is extremely non-ideal.

Since issue is a duplicate of https://github.com/tensorflow/tensorboard/issues/1275, closing this one.  Please follow the other for updates.  There's also an umbrella Github issue https://github.com/tensorflow/tensorboard/issues/2932 to cover the other dashboards which lack data download support.

Today, one workaround that I would not recommend relying upon, is to manually craft a URL (the same one TensorBoard would use to get the data), and use your browser to save the result to a file.
Template:
`http://<tb-host>/data/plugin/histograms/histograms?run=<run-name>&tag=<tag-name>`

For example, if your TensorBoard instance is on `localhost:6006`, your run name is `mnist/test` and the histogram tag is `layer1/Wx_plus_b/pre_activations`, 
Example URL:
`http://localhost:6006/data/plugin/histograms/histograms?run=mnist/test&tag=layer1/Wx_plus_b/pre_activations`

Note, this workaround isn't supported, and we still want to add some visual affordance to in the UI to download histogram data.

**Closed by psybuzz** 2020-04-23 17:15 UTC
Labels: type:feature

**Comment by DanielWicz** [comment] 2023-01-27 13:55
It doesn't work if the data are loaded after first run. It does load 50 and then stays at 50 points, even after the training is done
