### ISSUE TITLE
Feature request: "Include zero" option

### ISSUE THREAD

**Issue by Faur** [tensorflow/tensorboard#710] opened 2017-11-08 09:14 UTC
I think it would be useful to have a *Include zero* option for the scalar summaries that would force zero to be included in all graphs. (Similar to the *Show data download links* and *Ignore outliers in chart scaling*)

**Comment by wchargin** [comment] 2017-11-10 00:14
This seems reasonable to me. It would also be easy to implement.

@chihuahua, what do you think?

**Comment by wchargin** [comment] 2017-11-10 13:34
A couple thoughts:

  * It would perhaps make more sense to make this option a per-chart setting, such as the current log-scale toggle, because very often it will be the case that only certain charts should be forced to include zeros.
  * We could consider generalizing this slightly to a "custom window" option to allow manually specifying any subset of {xmin, xmax, ymin, ymax}; the feature as proposed here would correspond to setting ymin=0 only.

**Comment by Faur** [comment] 2017-11-14 09:54
Hmm I like the flexibility of having per graph settings, but especially if you have {xmin, xmax, ymin, ymax} for say 3 different graphs, for training and test runs it becomes a lot of settings one has to manually enter every time, especially as one would probably want to use the same values for many of the graphs.

This might be getting more complicated, but perhaps each graph can have a 'use custom scale' toggle, and then there is a global {xmin, xmax, ymin, ymax} that you can set. Otherwise an 'apply to selected graphs' feature would also work!

**Comment by lucasb-eyer** [comment] 2017-11-26 12:40
What will happen to log-scaled graphs that have "include zero" set? What should graphs with only negative values look like? This is way too special IMO, but I really wish to have a custom ylim option where one can enter numeric values. Then, maybe have a global "tie all axis limits" option. Just my .02€

**Comment by nfelt** [comment] 2017-12-06 02:01
Duplicate of #77 

This is pretty much the same feature request as the existing issue, so I'm opting to just close this one in favor of that one.

**Closed** 2017-12-06 03:40 UTC
Labels: plugin:scalars, type:feature
