### ISSUE TITLE
How can i deal with this?

### ISSUE THREAD

**Issue by vegaviazhang** [tensorflow/tensorboard#5228] opened 2021-08-11 13:01 UTC
step1:   I install tensorboardX and tensorflow
by using` pip install tensorboardX  && pip install tensorflow`
step2:   I generate some scalar data
```python
from tensorboardX import SummaryWriter
writer = SummaryWriter('runs/scalar_example')
for i in range(10):
    writer.add_scalar('quadratic', i**2, global_step=i)
    writer.add_scalar('exponential', 2**i, global_step=i)
```
step3: by using `tensorboard --logdir=/home/zhangx/z_trash/scalar_example --bind_all`
step4: i view http://localhost:6006/ , but there is nothing to show?

What is the problem? thanks very much
![image](https://user-images.githubusercontent.com/60467454/129032303-68854898-ab22-4629-9b00-46e642d9c774.png)

View Picture follow below.
![image](https://user-images.githubusercontent.com/60467454/129033467-9829f237-8425-4726-8576-9c04e1412f20.png)

**Comment by vegaviazhang** [comment] 2021-08-11 13:04
I confirm the scale data is correct!

**Comment by bileschi** [comment] 2021-08-11 15:13
Hi @vegaviazhang , unfortunately we're unable to help as TensorBoardX is an unaffiliated fork of TensorBoard.   Dos your project work with stock TensorBoard?  If not, you may want to re-file your issue with TensorBoardX?

https://github.com/lanpa/tensorboardX

**Comment by stephanwlee** [comment] 2021-08-11 16:11
I just ran the repo case in my local environment and was not able to reproduce it. 

![image](https://user-images.githubusercontent.com/2547313/129064651-e06f2193-e290-4f66-943c-1f897430c717.png)

The fact that you see Scalars and Time Series plugin mean that something is correct. Could you open up the developer tools on the browser and perhaps paste the error it is logging? Also, I would appreciate it if you can take a look at your terminal and perhaps look for errors our Python server might be reporting. Thanks!

**Comment by bileschi** [comment] 2021-08-12 14:57
Closing as not reproducible.    @vegaviazhang please re-open if there is something for TensorBoard to do here.  If you end up opening an issue in TensorBoardX, you may want to cross link it here.   Thanks!

**Closed by bileschi** 2021-08-12 14:57 UTC
Labels: type:bug, plugin:scalars, core:frontend, stat:awaiting response
