### ISSUE TITLE
Backslash-separated logdir paths have issues on Windows

### ISSUE THREAD

**Issue by wchargin** [tensorflow/tensorboard#51] opened 2017-06-16 19:18 UTC
Migrated from https://github.com/tensorflow/tensorflow/issues/9854.

@DarrellThomas says:

> [After running `tensorboard --logdir='D:\logs_dt'`] I'm not seeing anything on the tensorboard at all. I can see where the log director(ies) is/are created by the tutorial script, and the subdirectories /test and /train are there with the event data present. I point the tensorboard to the populated log directory with the following command, but it cannot see the event files. Nothing is present in tensorboard, and I'm redirected back to the tutorials.

**Comment by wahahajun** [comment] 2017-06-21 09:32
hi.
I meet the same problem. How can i use tensorboard correctly in windows before the next release. Thanks.

**Comment by wahahajun** [comment] 2017-06-21 09:38
o, i put my logfile in windows C directory and it seccess

**Comment by dandelionmane** [comment] 2017-06-21 18:35
Here's the workaround: (from https://github.com/tensorflow/tensorflow/issues/7856)

>Unfortunately TensorBoard uses a colon as the separator between the optional "run name" and the path in the --logdir flag. That means that --logdir=E:\tmp\tensorflow\mnist\logs is interpreted as a run named E with path \tmp\tensorflow\mnist\logs, which explains why it's sensitive to the current working directory.
>As a quick workaround, you could avoid this problem by always specifying an explicit run name as part of the --logdir flag, e.g.:

>`tensorboard --logdir=training:E:\tmp\tensorflow\mnist\logs`

**Comment by nfelt** [comment] 2017-12-06 03:28
Duplicate of #52

**Comment by nfelt** [comment] 2017-12-06 03:28
Duping to #52 since it's what all the other reports have been duped to, even though this issue was technically filed first.

**Closed** 2017-12-06 03:29 UTC
Labels: (╯°□°)╯windows, core:backend, type:bug/performance
