### ISSUE TITLE
Audio and scalar demos emit Windows-incompatible paths

### ISSUE THREAD

**Issue by LexusH** [tensorflow/tensorboard#3445] opened 2020-03-30 16:30 UTC
## Environment information (required)
Windows 10
Anaconda: Yes
Tensorflow version: 2.1.0
Tensorboard version: 2.1.0
Tensorflow estamator version: 2.1.0

## Issue description
I can't get audio_demo.py to run in my anaconda environment. The problems appear to be from Tensorflow V1 commands not being fully adapted to work in Tensorflow 2.0. I have found two places that need to be changed:

Needs to be added:
tf.compat.v1.disable_eager_execution()

Needs to be changed:
writer = tf.summary.FileWriter(os.path.join(logdir, run_name)) =>
writer = tf.compat.v1.summary.FileWriter(os.path.join(logdir, run_name))

I think that's all the problems, but I can't check because the naming of the output file is incompatible with windows. The problem lines appear to be:

writer = tf.compat.v1.summary.FileWriter(os.path.join(logdir, run_name))
run_name = "wave:%02d,%s" % (i + 1, wave_name)

for the first, if you change logdir to "logs" that seems to fix it, but the inclusion of the colon in the second line makes the file produced incompatible with windows. I've tried changing the colon to other special characters but that just seems to break it more. 

The error I'm getting after all my suggested changes is:
Traceback (most recent call last):
  File "audio_demo.py", line 285, in <module>
    app.run(main)
  File "C:\Users\Public\Anaconda\envs\tf-gpu\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Public\Anaconda\envs\tf-gpu\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "audio_demo.py", line 280, in main
    run_all(FLAGS.logdir, verbose=True)
  File "audio_demo.py", line 275, in run_all
    run(logdir, run_name, wave_name, wave_constructor)
  File "audio_demo.py", line 147, in run
    writer = tf.compat.v1.summary.FileWriter(os.path.join("logs",run_name))
  File "C:\Users\Public\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\summary\writer\writer.py", line 367, in __init__
    filename_suffix)
  File "C:\Users\Public\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\summary\writer\event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "C:\Users\Public\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 440, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Users\Public\Anaconda\envs\tf-gpu\lib\site-packages\tensorflow_core\python\lib\io\file_io.py", line 455, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to create a directory: logs/wave:01,sine_wave; Invalid argument

**Comment by wchargin** [comment] 2020-03-30 16:38
Hi @LexusH—thanks for the report! The demos indeed only currently work
with TensorFlow 1.x, so that part of the issue is a duplicate of #3058.
That the paths are invalid on Windows is new to me, but you’re certainly
right that `:` is a prohibited character, so that makes sense. The
scalars demo also has colons in its output.

I’ll see if I can just fix up the pathnames to be valid on Windows,
which should be a simple fix. Making the demos work on TF 2.x isn’t a
super high priority issue for us right now (generally each person
working on TensorBoard just runs the demos once and saves the output),
but we’d welcome any PRs if you want to contribute something. :-)

**Comment by LexusH** [comment] 2020-03-30 16:46
Thank you for getting back to me so promptly! I was hoping to write a tutorial for the audio plugin as per #742, but i'd be happy to convert its demos to work on tensorflow 2.0 as well

**Closed** 2020-03-30 18:11 UTC
Labels: os:windows
