### ISSUE TITLE
Graph visualization failed when follows the official doc

### ISSUE THREAD

**Issue by Harrypotterrrr** [tensorflow/tensorboard#4230] opened 2020-10-10 15:32 UTC
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 724b56cee52e7d8eb89bbeec1f0d5ce3e38c9682

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=8, micro=5, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='lz', release='5.4.0-48-generic', version='#52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.3.0
INFO: installed: tensorflow-gpu==2.3.0
INFO: installed: tensorflow-estimator==2.3.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.3.0'

--- check: tensorflow_python_version
2020-10-10 23:22:50.896203: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
INFO: tensorflow.__version__: '2.3.0'
INFO: tensorflow.__git_version__: 'v2.3.0-rc2-23-gb36436b087'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/lz/anaconda3/envs/tf2/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'lz'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=18087993, st_dev=2050, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1601583034, st_mtime=1601699198, st_ctime=1601699198)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/lz/anaconda3/envs/tf2/lib/python3.8/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.10.0
astunparse==1.6.3
attrs==20.2.0
bunch==1.0.1
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
dill==0.3.2
future==0.18.2
gast==0.3.3
google-auth==1.21.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
googleapis-common-protos==1.52.0
grpcio==1.32.0
h5py==2.10.0
idna==2.10
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib @ file:///tmp/build/80754af9/matplotlib-base_1597876319132/work
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
numpy @ file:///tmp/build/80754af9/numpy_and_numpy_base_1596233721170/work
oauthlib==3.1.0
olefile==0.46
opt-einsum==3.3.0
Pillow @ file:///tmp/build/80754af9/pillow_1594307295532/work
pip==20.2.3
promise==2.3
protobuf==3.13.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
python-dateutil==2.8.1
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scipy==1.4.1
setuptools==49.6.0.post20200925
sip==4.19.13
six==1.15.0
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorflow-datasets==3.0.0
tensorflow-estimator==2.3.0
tensorflow-gpu==2.3.0
tensorflow-metadata==0.24.0
termcolor==1.1.0
tornado==6.0.4
tqdm==4.49.0
urllib3==1.25.10
Werkzeug==1.0.1
wheel==0.35.1
wrapt==1.12.1

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

- Screenshot
![image](https://user-images.githubusercontent.com/28552583/95658889-405c1d80-0b50-11eb-8e2c-33b39c23cb13.png)

## Issue description

Here is some part of my code. I wanna check the architecture and flow of my graph. Though the function of SCALAR, IMAGES and TEXT are all fine, I could not print out the graph of my model. 
Thanks for your help in advance.

``` python
    @tf.function
    def train_step(self, x, y):
        with tf.GradientTape() as tape:
            predictions, _ = self.model(x)
            loss = self.model.loss_object(y, predictions)

        gradients = tape.gradient(loss, self.model.trainable_variables)
        self.optimizer.apply_gradients(zip(gradients, self.model.trainable_variables))

        psnr = self.calc_psnr(y, predictions)
        return loss, psnr

    @tf.function
    def multi_train_step(self, x, y):
        loss, psnr = self.mirrored_strategy.run(self.train_step, args=(x, y))
        mean_loss = self.mirrored_strategy.reduce(tf.distribute.ReduceOp.MEAN, loss, axis=None)
        mean_psnr = self.mirrored_strategy.reduce(tf.distribute.ReduceOp.MEAN, psnr, axis=None)
        return mean_loss, mean_psnr

    def train_epoch(self, epoch):
        self.start_time = time.time()

        with self.mirrored_strategy.scope():
            for step, (batch_x, batch_y) in enumerate(self.train_dataset):

                if step == 1 and epoch == 1: # turn the trace_on to record graph
                    with self.image_writer.as_default():
                        tf.summary.trace_on()

                loss, psnr = self.multi_train_step(batch_x, batch_y)

                if step == 1 and epoch == 1: # close and export the recorded graph only once when step and epoch == 1
                    with self.image_writer.as_default():
                        tf.summary.trace_export(
                            f"Graph/{self.version}", step=1
                        )

                self.total_step += 1
```

**Comment by Harrypotterrrr** [comment] 2020-10-11 06:33
This part of the code will also cause `Graph visualization failed` error. Could you please use the following code to check the reason why this error comes out? 
I just wanna test if my 5 ResidualBlocks has been added into keras.Sequential.
``` python
import tensorflow as tf
import tensorflow.keras as keras

class ResidualBlock_noBN(tf.keras.layers.Layer):
    def __init__(self, nf=64, name=""):
        super(ResidualBlock_noBN, self).__init__()

        self.conv1 = keras.layers.Conv2D(nf, (3, 3), (1, 1), "same",
                            kernel_initializer=tf.keras.initializers.HeNormal(), name=f'No.{name}_conv1')
        self.conv2 = keras.layers.Conv2D(nf, (3, 3), (1, 1), "same",
                            kernel_initializer=tf.keras.initializers.HeNormal(), name=f'No.{name}_conv2')
        self.relu = keras.layers.ReLU()

    def __call__(self, x):
        # for i in module_list.trainable_variables:
        #     print("trainable variables:", i.name)
        identify = x
        out = self.relu(self.conv1(x))
        out = self.conv2(out)
        return identify + out

class Module(tf.keras.Model):
    def __init__(self, block, n_layers):
        super(Module, self).__init__()
        self.n_layers = n_layers

        self.module_list = []
        for i in range(n_layers):
            self.module_list.append(block(name=str(i)))
        self.module_list = tf.keras.models.Sequential(self.module_list)
        # for i in range(self.n_layers):
        #     self.module_list.add(block(name=str(i)))

    def __call__(self, x):
        out = self.module_list(x)
        return out

import functools
ResidualBlock_noBN_f = functools.partial(ResidualBlock_noBN, nf=64)
module_list = Module(ResidualBlock_noBN_f, n_layers=5)
x = tf.ones([5,8,8,64])
writer = tf.summary.create_file_writer("./logs")
tf.summary.trace_on(graph=True, profiler=True)
out = module_list(x)
with writer.as_default():
  tf.summary.trace_export(
      name="my_func_trace",
      step=0,
      profiler_outdir="./logs")
print(out.shape)
for i in module_list.variables:
    print("variables:", i.name)
for i in module_list.trainable_variables:
    print("trainable variables:", i.name)
```
The output of the above code is here:
```
variables: No.0_conv1/kernel:0
variables: No.0_conv1/bias:0
variables: No.0_conv2/kernel:0
variables: No.0_conv2/bias:0
trainable variables: No.0_conv1/kernel:0
trainable variables: No.0_conv1/bias:0
trainable variables: No.0_conv2/kernel:0
trainable variables: No.0_conv2/bias:0
```
It seems that only one ResidualBlock has been added into the `tf.keras.Sequential`

**Comment by rmothukuru** [comment] 2020-10-12 08:28
@Harrypotterrrr,
Thank you for the issue. You have mentioned 

> when follows the official doc 

Can you please provide the reference of the Official Doc as well. Thanks!

**Comment by Harrypotterrrr** [comment] 2020-10-12 09:22
@rmothukuru 
Hi, thanks for your reply!
Here is the link of the [Official Doc] to instruct how to build tensorboard graph(https://www.tensorflow.org/tensorboard/graphs)

**Comment by bileschi** [comment] 2020-10-14 14:48
Thanks for your issue report, @Harrypotterrrr .  We are looking into making a minimal reproduction.

**Comment by stephanwlee** [comment] 2020-11-05 21:56
@Harrypotterrrr thanks for the report. AFAICT, this is a variant of #1961. If you remove `@tf.function` in `train_step` (in your original example; more complete example would have been nice), then you should not have any issue.

For example (I would like to use Colab but it seems tricky to share it with the public):
```py
# -*- coding: utf-8 -*-
"""https://github.com/tensorflow/tensorboard/issues/4230

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TouX4Y5_hwxaAeQ4QRS97keZkUqZN9De
"""

# Commented out IPython magic to ensure Python compatibility.
import tensorflow as tf
import time
# %load_ext tensorboard

"""Example 1: multiple tf.function; one tf.func calling another"""

class Foo:

  def __init__(self):
    self.mirrored_strategy = tf.distribute.MirroredStrategy()
    self.writer = tf.summary.create_file_writer('./bar')

  @tf.function
  def train_step(self, x):
      return x + 100

  @tf.function
  def multi_train_step(self, x):
      return self.train_step(x)

  def train_epoch(self, epoch):
      with self.writer.as_default():
          tf.summary.trace_on()

      self.multi_train_step(30)

      with self.writer.as_default():
          tf.summary.trace_export("test", step=1)

f = Foo()
f.train_epoch(1)

# Commented out IPython magic to ensure Python compatibility.

# Graph reconciliation failure
# %tensorboard --logdir foo

"""Example 2: removed one @tf.function and only have one at the top"""

import tensorflow as tf
import time

class Bar:

  def __init__(self):
    self.mirrored_strategy = tf.distribute.MirroredStrategy()
    self.writer = tf.summary.create_file_writer('./bar')

  def train_step(self, x):
      return x + 100

  @tf.function
  def multi_train_step(self, x):
      return self.train_step(x)

  def train_epoch(self, epoch):
      with self.writer.as_default():
          tf.summary.trace_on()

      self.multi_train_step(30)

      with self.writer.as_default():
          tf.summary.trace_export("test", step=1)

b = Bar()
b.train_epoch(1)

# Commented out IPython magic to ensure Python compatibility.
# No error in this case
# %tensorboard --logdir bar
```

If removing `@tf.function` does not help, please let us know.

**Comment by rmothukuru** [comment] 2020-11-10 11:45
@Harrypotterrrr,
Can you please respond to @stephanwlee's comment. Thanks!

**Comment by rmothukuru** [comment] 2020-11-17 07:57
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-11-17 07:57 UTC
Labels: plugin:graph, stat:awaiting response, type:bug

**Comment by alexkreimer** [comment] 2022-04-28 09:56
@stephanwlee Why removing the tf.function works ?
