### ISSUE TITLE
Upload button for bookmarks is broken.

### ISSUE THREAD

**Issue by nsthorat** [tensorflow/tensorboard#835] opened 2017-12-21 16:34 UTC
Steps to repro:

1) Open the bookmark tray.
2) Press the Upload icon.

You will see this:
![image](https://user-images.githubusercontent.com/1100749/34265061-dab30118-e642-11e7-9d77-70f085eb3ec0.png)

FYI @francoisluus

**Comment by francoisluus** [comment] 2017-12-21 16:50
Thanks for discovering this. Looking into this now, will try and figure out where it breaks.

**Comment by francoisluus** [comment] 2017-12-21 18:26
Further polymerization of *vz-projector-bookmark-panel* will likely resolve the issue, and streamline the implementation in a similar way we did for the Metadata-card toggle bug fix. Unless the bug is related to a state conditionality captured by bookmarking, this is likely some browser quirk (for lack of a better description atm) that I've seen fixed by polymerization.

I'll make a pull request for the above approach in a couple of days, if the problem is something else hopefully we can trace it to its root with more info.

vz-projector-bookmark-panel.ts:
```javascript
  /** Handles a click on the upload bookmarks button. */
  _uploadFile() {
    let fileInput = this.querySelector('#state-file');
    (fileInput as HTMLInputElement).click();
  }

  private setupUploadButton() {
    // Show and setup the load view button.
    const fileInput = this.querySelector('#state-file') as HTMLInputElement;
    fileInput.onchange = () => {
      const file: File = fileInput.files[0];
      // Clear out the value of the file chooser. This ensures that if the user
      // selects the same file, we'll re-read it.
```

**Comment by chihuahua** [comment] 2017-12-21 22:04
Thank you, francoisluus@! @nsthorat, could this issue pertain to the standalone projector? Maybe it's not in TensorBoard?

**Comment by jart** [comment] 2017-12-22 22:00
It'd be interesting to know if it's only with standalone, in which case something might have gone wrong on the build end internally.

**Comment by Loofort** [comment] 2018-08-27 20:36
I'd like to report this issue as well.
at https://projector.tensorflow.org/ bookmark upload doesn't work, producing:

THREE.WebGLRenderer 77
(index):10152 Uncaught TypeError: Cannot read property 'select' of undefined
    at HTMLElement.b._uploadFile ((index):10152)
    at HTMLElement.d ((index):4668)
    at HTMLElement.fire ((index):4690)
    at Object.fire ((index):4678)
    at Object.forward ((index):4685)
    at Object.click ((index):4684)
    at HTMLElement.handleNative ((index):4674)

I've tested on ubuntu 18.04 with 
 - Google Chrome Version 66.0.3359.181 (Official Build) (64-bit)
 - Firefox Quantum 61.0.1 
Also, I've asked to check a friend of mine, he got the same on macbook.

**Comment by bileschi** [comment] 2020-01-02 15:50
This appears to be working now?

**Closed by bileschi** 2020-01-02 15:50 UTC
Labels: plugin:projector
