### ISSUE TITLE
[TensorBoard] Charts in TensorBoard in Safari don't display correctly

### ISSUE THREAD

**Issue by chihuahua** [tensorflow/tensorboard#60] opened 2017-06-16 19:32 UTC
Scalars charts in TensorBoard do not work for macOS Sierra, latest Safari (Version 10.0.1).

This issue had been migrated from tensorflow/tensorflow#6108.

**Comment by episodeyang** [comment] 2017-09-12 19:20
@chihuahua is this still an issue? I think now this is fixed.

**Comment by psybuzz** [comment] 2021-01-23 02:28
Closing as the issue is no longer reproducible.
Manually opened https://tensorboard.dev/experiment/EDZb7XgKSBKo6Gznh3i8hg/#scalars in Safari 14.0.2 on Mac OS 11.1.

**Closed by psybuzz** 2021-01-23 02:28 UTC
Labels: stat:contributions welcome, type:bug
