### ISSUE TITLE
TB doesn't update graphs

### ISSUE THREAD

**Issue by vakker** [tensorflow/tensorboard#4164] opened 2020-09-14 22:59 UTC
## Environment information (required)

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:

### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version 724b56cee52e7d8eb89bbeec1f0d5ce3e38c9682

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=8, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='chupacabra', release='5.4.0-47-generic', version='#51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: True
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.3.0
INFO: installed: tensorflow==2.3.0
INFO: installed: tensorflow-estimator==2.3.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.3.0'

--- check: tensorflow_python_version
INFO: tensorflow.__version__: '2.3.0'
INFO: tensorflow.__git_version__: 'v2.3.0-rc2-23-gb36436b087'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/home/vince/miniconda3/envs/r2g/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'chupacabra'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=6029361, st_dev=64769, st_nlink=2, st_uid=1000, st_gid=1000, st_size=4096, st_atime=1600123873, st_mtime=1600124151, st_ctime=1600124151)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/home/vince/miniconda3/envs/r2g/lib/python3.7/site-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.10.0
aiohttp==3.6.2
aioredis==1.3.1
alembic==1.4.1
appdirs==1.4.3
ase==3.20.1
asn1crypto @ file:///home/conda/feedstock_root/build_artifacts/asn1crypto_1595949944546/work
astunparse==1.6.3
async-timeout==3.0.1
atari-py==0.2.6
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1599308529326/work
ax-platform==0.1.14
azure-core @ file:///home/conda/feedstock_root/build_artifacts/azure-core_1597089821726/work
azure-storage-blob @ file:///home/conda/feedstock_root/build_artifacts/azure-storage-blob_1599697492384/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache==1.6.1
beautifulsoup4==4.9.1
blessings==1.7
blinker==1.4
blist==1.3.6
botorch==0.3.0
brotlipy==0.7.0
cachetools==4.1.1
certifi==2020.6.20
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1595805535531/work
chardet==3.0.4
click==7.1.2
cloudpickle==1.3.0
colorama==0.4.3
colorful==0.5.4
conda==4.8.4
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling-build_1597341279120/work/cph
configparser==5.0.0
coverage @ file:///home/conda/feedstock_root/build_artifacts/coverage_1595592456525/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1598621005849/work
cycler==0.10.0
Cython @ file:///home/conda/feedstock_root/build_artifacts/cython_1594253470382/work
databricks-cli==0.9.1
decorator==4.4.2
dm-tree==0.1.5
docker @ file:///home/conda/feedstock_root/build_artifacts/docker-py_1598002850473/work
docker-pycreds==0.4.0
entrypoints==0.3
filelock==3.0.12
Flask==1.1.2
future==0.18.2
gast==0.3.3
gitdb @ file:///home/conda/feedstock_root/build_artifacts/gitdb_1588651542737/work
GitPython @ file:///home/conda/feedstock_root/build_artifacts/gitpython_1599191045865/work
google==3.0.0
google-api-core==1.22.2
google-auth==1.21.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
googleapis-common-protos==1.52.0
googledrivedownloader==0.4
gorilla==0.3.0
gpustat==0.6.0
GPUtil==1.4.0
gpytorch==1.2.0
grpcio==1.32.0
gunicorn==20.0.4
gym==0.17.2
h11==0.9.0
h5py==2.10.0
hiredis==1.1.0
httptools==0.1.1
hyperopt==0.2.4
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1593211369179/work
iniconfig @ file:///home/conda/feedstock_root/build_artifacts/iniconfig_1596221474428/work
ipdb @ file:///home/conda/feedstock_root/build_artifacts/ipdb_1595950402795/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1598749946943/work
ipython-genutils==0.2.0
isodate==0.6.0
itsdangerous==1.1.0
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1595018882455/work
Jinja2==2.11.2
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1593624380152/work
jsonschema==3.2.0
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
llvmlite==0.34.0
lz4==3.1.0
Mako @ file:///home/conda/feedstock_root/build_artifacts/mako_1595925083607/work
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-base_1597952254444/work
more-itertools @ file:///home/conda/feedstock_root/build_artifacts/more-itertools_1598643641143/work
msgpack==1.0.0
msrest @ file:///home/conda/feedstock_root/build_artifacts/msrest_1599590147834/work
multidict==4.7.6
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1598210780226/work
numba==0.51.2
numpy==1.18.5
nvidia-ml-py3==7.352.0
oauthlib==3.0.1
olefile==0.46
opencensus==0.7.10
opencensus-context==0.1.1
opencv-python==4.4.0.42
opencv-python-headless==4.3.0.36
opt-einsum==3.3.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1589925210001/work
pandas @ file:///home/conda/feedstock_root/build_artifacts/pandas_1599600961279/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1595548966091/work
pexpect==4.8.0
pickleshare==0.7.5
Pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1594213010297/work
pip==20.2.3
plotly==4.9.0
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1592827471208/work
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1590412252446/work
prometheus-flask-exporter @ file:///home/conda/feedstock_root/build_artifacts/prometheus_flask_exporter_1599151657044/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1598885455507/work
protobuf==3.13.0
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1594826921622/work
ptyprocess==0.6.0
py @ file:///home/conda/feedstock_root/build_artifacts/py_1593088446458/work
py-spy==0.3.3
pyaml==20.4.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat==0.6.3
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
pyglet==1.5.0
Pygments==2.6.1
PyJWT==1.7.1
pymongo==3.11.0
PyMySQL @ file:///home/conda/feedstock_root/build_artifacts/pymysql_1595447440673/work
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyrsistent==0.16.0
PySocks==1.7.1
pyswip==0.2.10
pytest==6.0.1
pytest-cov @ file:///home/conda/feedstock_root/build_artifacts/pytest-cov_1597431289864/work
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2020.1
PyYAML==5.3.1
querystring-parser==1.2.4
ray==0.8.7
rdflib==5.0.0
redis==3.4.1
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1592425495151/work
requests-oauthlib @ file:///home/conda/feedstock_root/build_artifacts/requests-oauthlib_1595492159598/work
retrying==1.3.3
rsa==4.6
ruamel-yaml-conda @ file:///home/conda/feedstock_root/build_artifacts/ruamel_yaml_1598972306942/work
scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1596546074663/work
scikit-optimize @ file:///home/conda/feedstock_root/build_artifacts/scikit-optimize_1599212891685/work
scipy==1.4.1
setproctitle==1.1.10
setuptools==49.6.0.post20200814
six @ file:///home/conda/feedstock_root/build_artifacts/six_1590081179328/work
smmap @ file:///home/conda/feedstock_root/build_artifacts/smmap_1588651577140/work
soupsieve==2.0.1
SQLAlchemy==1.3.13
sqlparse==0.3.1
tabulate==0.8.7
tensorboard==2.3.0
tensorboard-plugin-wit==1.7.0
tensorboardX==2.1
tensorflow==2.3.0
tensorflow-estimator==2.3.0
termcolor==1.1.0
threadpoolctl @ file:///tmp/tmp79xdzxkt/threadpoolctl-2.1.0-py3-none-any.whl
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1589469402899/work
torch==1.6.0
torch-cluster @ https://pytorch-geometric.com/whl/torch-1.6.0/torch_cluster-latest%2Bcu102-cp37-cp37m-linux_x86_64.whl
torch-geometric==1.6.1
torch-scatter @ https://pytorch-geometric.com/whl/torch-1.6.0/torch_scatter-latest%2Bcu102-cp37-cp37m-linux_x86_64.whl
torch-sparse @ https://pytorch-geometric.com/whl/torch-1.6.0/torch_sparse-latest%2Bcu102-cp37-cp37m-linux_x86_64.whl
torch-spline-conv @ https://pytorch-geometric.com/whl/torch-1.6.0/torch_spline_conv-latest%2Bcu102-cp37-cp37m-linux_x86_64.whl
torchvision==0.7.0
tornado==6.0.4
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1596476591553/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1599471676085/work
typing-extensions==3.7.4.3
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1595434816409/work
uvicorn==0.11.8
uvloop==0.14.0
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1595859607677/work
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1598373690950/work
websockets==8.1
Werkzeug==1.0.1
wheel==0.35.1
wrapt==1.12.1
yarl==1.5.1
zipp==3.1.0

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

For browser-related issues, please additionally specify:

  - Browser type and version: Firefox 80.0.1

## Issue description

I'm running experiments with scalar logging but Tensorboard only reads the files when I launch it (`tensorboard --logdir=.`). I know that auto reload was removed, but even if I press reload or reload the page (F5 or CTRL+F5) it doesn't pick up the new values.

**Comment by rmothukuru** [comment] 2020-09-15 09:31
@vakker,
Can you please refresh the Tensorboard using the Refresh Option from Tensorboard (Arrow on the Top Right, shown below) and let us know how it goes. Thanks!

![image](https://user-images.githubusercontent.com/48206667/93193189-281cfc80-f764-11ea-81b7-87fa38a1ddb6.png)

**Comment by vakker** [comment] 2020-09-15 09:54
@rmothukuru that's what I meant by reload. So to be clear, neither the Refresh Option (top right corner) nor the reload page (F5) does anything. Also, I can see that the backend doesn't pick up the new logs, so I'm not sure if this is a frontend issue.

**Comment by rmothukuru** [comment] 2020-09-15 14:34
@vakker,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment] 2020-10-12 08:32
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-10-12 08:32 UTC
Labels: core:backend, core:frontend, plugin:graph, stat:awaiting response, type:support
