### ISSUE TITLE
What-if-tool demo missing values in binning by 'occupation'

### ISSUE THREAD

**Issue by pazzam** [tensorflow/tensorboard#1759] opened 2019-01-14 19:49 UTC
Bug on what-if-tool demo, here: https://pair-code.github.io/what-if-tool/uci.html

When binning by the feature 'occupation', many valid values are missing.  See screenshot.  Notice that it's missing values such as 'Tech-support', 'Protective-serv', 'Armed-Forces', etc.

![screenshot from 2019-01-14 11-46-20](https://user-images.githubusercontent.com/46689693/51136818-45acfc80-17f2-11e9-9410-e0a5de1ab77a.png)

**Comment by jameswex** [comment] 2019-01-14 19:53
Thanks for the report.

These values are being automatically binned into the "other" category as by default the binning only shows 10 bins. We are in the process of changing this code as part of a redesign to not default the bin number to 10 (instead to show enough bins for all values, and allow you to turn that down to a lower number if you want). For now you can just select the "count" dropdown next to the "binning | x-axis" one and change 10 to a higher number to see the other categories.

**Comment by pazzam** [comment] 2019-01-14 20:12
Ohhh, I see.  I think the confusion comes from the fact that the census dataset has missing values which is also denoted by '?'.  Can the 'other' category be separated from the missing value bin?  Otherwise, there's no visual indication that there's any hidden categories.

**Comment by sanatmpa1** [comment] 2022-01-20 08:25
@pazzam,

As explained by @jameswex, `The count dropdown specifies the number of buckets to create`. When I changed `count` to 15, I got the missing occupation categories('Tech-support', 'Protective-serv', 'Armed-Forces', etc) displayed and also the `other` category got removed, which works as intended. Also to answer your second question, already other category is separated from missing value bin, if you can refer the screenshot attached. I am closing this issue now and you can feel free to reopen if you still have any questions. Thanks!

![image](https://user-images.githubusercontent.com/87846724/150300725-0f88a842-6267-4d9b-a816-b02e0515a437.png)

**Closed by sanatmpa1** 2022-01-20 08:25 UTC
Labels: type:bug, stat:awaiting tensorflower, plugin:what-if-tool
