### ISSUE TITLE
Toggle all runs duplicates images

### ISSUE THREAD

**Issue by xivh** [tensorflow/tensorboard#3777] opened 2020-07-01 03:55 UTC
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````

--- check: autoidentify
INFO: diagnose_tensorboard.py version a511de7ece215f0cfb622f2672563beee93515a9
--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='cs-6000-devshell-vm-fedb3ace-9229-421e-a589-59bc6fde584e', release='4.19.112+', version='#1 SMP Sat J
un 13 11:04:33 PDT 2020', machine='x86_64')
INFO: sys.getwindowsversion(): N/A
--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None
--- check: installed_packages
INFO: installed: tensorboard==1.14.0
INFO: installed: tensorflow==1.14.0
INFO: installed: tensorflow-estimator==1.14.0

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '1.14.0'
--- check: tensorflow_python_version
INFO: tensorflow.__version__: '1.14.0'
INFO: tensorflow.__git_version__: 'v1.14.0-rc1-22-gaf24dc9'
--- check: tensorboard_binary_path
INFO: which tensorboard: b'/usr/local/bin/tensorboard\n'
--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '',
 ('::', 0, 0, 0))]
--- check: readable_fqdn
INFO: socket.getfqdn(): 'cs-6000-devshell-vm-fedb3ace-9229-421e-a589-59bc6fde584e'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=2439997, st_dev=90, st_nlink=2, st_uid=1000, st_gid=1001, st_size=4096, st_atime=1593575025, st_mtime=159357
4994, st_ctime=1593574994)
INFO: mode: 0o40777
--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/usr/local/lib/python3.7/dist-packages']; bad_roots (0): []
--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.9.0
appdirs==1.4.4
applicationinsights==0.11.9
asgiref==3.2.10
astor==0.8.1
astroid==2.4.2
autopep8==1.5.3
backcall==0.2.0
backports.csv==1.0.7
bleach==3.1.5
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
cli-helpers==0.2.3
Click==7.0
configobj==5.0.6
decorator==4.4.2
distlib==0.3.1
Django==3.0.7
enum34==1.1.10
filelock==3.0.12
flake8==3.8.3
Flask==1.1.2
Flask-PyMongo==2.3.0
future==0.18.2
gast==0.3.3
google-api-core==1.21.0
google-api-python-client==1.9.3
google-auth==1.18.0
google-auth-httplib2==0.0.3
google-cloud-bigquery==1.25.0
google-cloud-core==1.3.0
google-cloud-datastore==1.12.0
google-cloud-language==1.3.0
google-cloud-logging==1.15.0
google-cloud-spanner==1.17.1
google-cloud-storage==1.29.0
google-cloud-translate==2.0.1
google-cloud-videointelligence==1.15.0
google-cloud-vision==1.0.0
google-pasta==0.2.0
google-resumable-media==0.5.1
grpc-google-iam-v1==0.12.3
grpcio==1.30.0
h5py==2.10.0
httplib2==0.18.1
humanize==2.4.1
idna==2.10
importlib-metadata==1.7.0
ipython==7.16.1
ipython-genutils==0.2.0
isort==4.3.21
itsdangerous==1.1.0
jedi==0.17.1
Jinja2==2.11.2
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
lazy-object-proxy==1.4.3
Markdown==3.2.2
MarkupSafe==1.1.1
mccabe==0.6.1
mssql-cli==1.0.0
mypy==0.782
mypy-extensions==0.4.3
numpy==1.19.0
oauth2client==4.1.3
packaging==20.4
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
pip==18.1
pluggy==0.13.1
prompt-toolkit==3.0.5
protobuf==3.12.2
psycopg2==2.8.5
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycurl==7.43.0.2
pydocstyle==5.0.2
pyflakes==2.2.0
Pygments==2.6.1
PyGObject==3.30.4
pylint==2.5.3
pyls-mypy==0.1.8
pymongo==3.10.1
pyparsing==2.4.7
python-apt==1.8.4.1
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.33.3
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
rope==0.17.0
rsa==4.6
setuptools==47.3.1
six==1.15.0
snowballstemmer==2.0.0
sqlparse==0.2.4
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
terminaltables==3.1.0
toml==0.10.1
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions==3.7.4.2
ujson==1.35
uritemplate==3.0.1
urllib3==1.25.9
virtualenv==20.0.25
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==1.0.1
wheel==0.34.2
wrapt==1.12.1
yapf==0.30.0
zipp==3.1.0
``````

</details>

### Next steps
No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

  - Browser type and version (e.g., Chrome 64.0.3282.140): Firefox 77.0.1
  - Screenshot, if it’s a visual issue: https://imgur.com/a/KnnYviQ

## Issue description

Toggling all runs duplicates images. Images that are not collapsed are not duplicated. See linked video for an example.

I am using GCP and running tensorboard from a new cloud shell.

**Comment by rmothukuru** [comment] 2020-07-01 07:11
@xivh,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by nfelt** [comment] 2020-07-01 18:02
This looks similar to an old issue https://github.com/tensorflow/tensorboard/issues/884.

It looks like you're using TensorBoard 1.14 which is fairly old at this point.  Are you able to reproduce the problem against the most recent version of TensorBoard?

**Comment by xivh** [comment] 2020-07-01 22:46
I upgraded to 2.2.2 and I am not having the error.

**Comment by nfelt** [comment] 2020-07-02 00:20
Great, glad that worked for you.  In that case I'll mark this as a duplicate and close it.

**Comment by nfelt** [comment] 2020-07-02 00:21
Duplicate of #884

**Closed by nfelt** 2020-07-02 00:21 UTC
Labels: core:frontend, stat:awaiting response, type:bug
