### ISSUE TITLE
Support download of all scalars

### ISSUE THREAD

**Issue by lochbrunner** [tensorflow/tensorboard#4925] opened 2021-05-01 07:38 UTC
When using the `add_scalars` method of the `SummaryWriter` (PyTorch), you can draw multiple scalars in one plot.

But downloading these scalars is very time consuming: You have to download each graph individually.

It would be nice, if there would be the option to download all graphs at once in a csv or json file.

The resulted csv may look as follow

Wall time | Step | <tag of scalar 1> | <tag of scalar 2> | <tag of scalar 3>
---  | ---  | ---  | ---  | ---
1619761818.90404 | 0 | 1.2 | 2.2 | 3.2
1619761914.10188 | 5 | 1.3 | 2.3 | 3.3
1619762009.43932 | 10 | 1.4 | 2.4 | 3.4
1619762105.73179 | 15 | 1.5 | 2.5 | 3.5
1619762200.92274 | 20 | 1.6 | 2.6 | 3.6
1619762295.98607 | 25 | 1.7 | 2.7 | 3.7
1619762391.56858 | 30 | 1.8 | 2.8 | 3.8

**Comment by wchargin** [comment] 2021-05-04 21:10
Hi @lochbrunner! Thanks for the request. This looks like a duplicate of
#1232 to me, but feel free to holler if you think that that's not
accurate.

**Comment by wchargin** [comment] 2021-05-04 21:10
Duplicate of #1232

**Closed by wchargin** 2021-05-04 21:10 UTC
Labels: core:frontend, plugin:scalars, stat:awaiting tensorflower, theme:ui-polish, type:feature
