### ISSUE TITLE
can't upload log to Tensorboard.dev with google colab :EOFError: EOF when reading a line

### ISSUE THREAD

**Issue by IIIBlueberry** [tensorflow/tensorboard#3409] opened 2020-03-21 14:22 UTC
## Environment information (required)

Please run `diagnose_tensorboard.py` (link below) in the same
environment from which you normally run TensorFlow/TensorBoard, and
paste the output here:

https://raw.githubusercontent.com/tensorflow/tensorboard/master/tensorboard/tools/diagnose_tensorboard.py

For browser-related issues, please additionally specify:

  - Browser type and version (e.g., Chrome 64.0.3282.140):
  - Screenshot, if it’s a visual issue:

Environment information log: https://pastebin.com/qRneuxFq
## Issue description

Please describe the bug as clearly as possible. How can we reproduce the
problem without additional resources (including external data files and
proprietary Python modules)?
i cant upload log to tensorboard.dev then using colab, executing tensorboard with '%' symbol will give you "EOF when reading a line error", while running tensorboard with '!' symbol wont allow you to run python script,
example code:
```
%tensorflow_version 2.x

%load_ext tensorboard

%tensorboard dev upload --logdir logs/gradient_tape --name "wgan-weightclipiing-1" --description "just testting tensorboard.dev"
```
error log:
```
ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
***** TensorBoard Uploader *****

This will upload your TensorBoard logs to https://tensorboard.dev/ from
the following directory:

logs/gradient_tape

This TensorBoard will be visible to everyone. Do not upload sensitive
data.

Your use of this service is subject to Google's Terms of Service
<https://policies.google.com/terms> and Privacy Policy
<https://policies.google.com/privacy>, and TensorBoard.dev's Terms of Service
<https://tensorboard.dev/policy/terms/>.

This notice will not be shown again while you are logged into the uploader.
To log out, run `tensorboard dev auth revoke`.

Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 66, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 268, in main
    return runner(self.flags) or 0
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/uploader/uploader_main.py", line 788, in run
    return _run(flags)
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/uploader/uploader_main.py", line 282, in _run
    _prompt_for_user_ack(intent)
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/uploader/uploader_main.py", line 89, in _prompt_for_user_ack
    response = six.moves.input("Continue? (yes/NO) ")
EOFError: EOF when reading a line
Contents of stdout:
Continue? (yes/NO)
```

**Comment by rmothukuru** [comment] 2020-03-23 07:04
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here (code for generating the LogDir). Thanks!

**Comment by GalOshri** [comment] 2020-03-24 03:25
Thank you for opening this issue! The `tensorboard dev upload ...` command cannot currently be run as a magic (i.e. `%tensorboard`). Instead, it should be run as `!tensorboard dev upload ...`. 

As you pointed out, python code after `!tensorboard dev upload ...` won't run because the command continues running until the cell is stopped (in case new logs are added). 

We want to improve the Python logging experience (which would help solve this). For now, is it possible for you to run the Python script before the `!tensorboard dev upload ...` command?

**Comment by IIIBlueberry** [comment] 2020-03-26 19:16
@GalOshri Hi sorry for late reply, yes i can upload log to tensorboard.dev with `!tensorboard dev upload, @rmothukuru i dont think it's related with my tensorboard log since !tensorboard dev upload is working here some tensorboard.dev link : https://tensorboard.dev/experiment/p2xVqq7CRAWEquX9bOjUGg/

**Comment by GalOshri** [comment] 2020-03-26 21:19
Glad to hear that works! We definitely want to improve this experience in the future, but let us know if you run into any other issues.

**Comment by emmanuelol** [comment] 2020-03-27 02:34
Hi I'm start using Tensorboard Dev, but I'm not using Collab, I did what @GalOshri  propose and seems to work but the cell now is freeze because continues running because is waiting for a "yes/no"  to continue, any idea on how to solve this? I'm working locally with Docker Containers and Jupyter Lab.
`2020-03-27 02:27:41.813833: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-03-27 02:27:41.814968: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6

***** TensorBoard Uploader *****

This will upload your TensorBoard logs to https://tensorboard.dev/ from
the following directory:

/tmp/tmpwj0tm67_

This TensorBoard will be visible to everyone. Do not upload sensitive
data.

Your use of this service is subject to Google's Terms of Service
<https://policies.google.com/terms> and Privacy Policy
<https://policies.google.com/privacy>, and TensorBoard.dev's Terms of Service
<https://tensorboard.dev/policy/terms/>.

This notice will not be shown again while you are logged into the uploader.
To log out, run `tensorboard dev auth revoke`.

Continue? (yes/NO) `

**Comment by pidefrem** [comment] 2020-05-16 20:06
@emmanuelol If you're in a notebook, you can click on the dialogue box and type "yes" then enter to continue.

**Comment by bileschi** [comment] 2021-04-07 17:11
I'm going to close this issue : it is currently possible to upload to TensorBoard.dev from Colab.  See, e.g., https://www.tensorflow.org/tensorboard/get_started

**Closed by bileschi** 2021-04-07 17:11 UTC
Labels: core:backend, stat:awaiting tensorflower, tbdev, type:support

**Comment by rienath** [comment] 2021-08-15 14:57
@bileschi I have the same issue as @emmanuelol in a docker container notebook too. Clicking on the dialogue box does not do anything

**Comment by bileschi** [comment] 2021-08-16 15:04
TensorBoard will ask for credentials if it can't find them in the place it expects to find them.   If the Jupyter dialog is not working, you may be able to get around it by forming credentials locally and moving them into the container with the jupyter notebook.

On my machine, my credentials are stored at `.config/tensorboard/credentials/uploader-creds.json `
