### ISSUE TITLE
Tensorboard: downloading the eval data in csv/json format runs into error

### ISSUE THREAD

**Issue by mainakmanna** [tensorflow/tensorboard#4243] opened 2020-10-16 00:06 UTC
Environment: Using Colab. 
Tensorboard version 2.3.0

Problem description: The events files are stored in google cloud storage. I can read those files and plot the graph. But when we try to download the graph data as CSV it shows "Failed - No File". 

![image](https://user-images.githubusercontent.com/28564860/96198010-dc709500-0f53-11eb-8df3-718d33211803.png)

When I click the hyperlinks - a file download dialog appears. But when saved it showed the error,

"Failed - No file" in the browser download tab. (Browser is chrome Version 86.0.4240.75 (Official Build) (64-bit))

**Comment by nfelt** [comment] 2020-10-16 17:10
Duplicate of #1845

**Comment by nfelt** [comment] 2020-10-16 17:12
This is a known issue with TensorBoard when embedded in Colab - restrictions in the Colab environment prevent this from working normally. We're tracking it in #1845.

For now the best workaround we can recommend is to run TensorBoard locally instead if you need to use the CSV/JSON download options.

**Closed by nfelt** 2020-10-16 17:12 UTC
Labels: core:backend, core:frontend, stat:awaiting tensorflower, type:bug

**Comment by lauritowal** [comment] 2021-05-24 21:08
I have the same problem in Chrome, however it is working normally when using Colab with **Firefox**, by the way. Maybe this is helpful to someone finding this issue until it gets resolved :)

**Comment by daysofthunder98** [comment] 2021-06-18 18:32
> I have the same problem in Chrome, however strangely it is working normally when using Colab with Firefox, by the way. Maybe this is helpful to someone finding this issue until it gets resolved :)

That is strange, I can't seem to download from Firefox. I am running Windows 10 if that matters

**Comment by lauritowal** [comment] 2021-06-18 19:33
@daysofthunder98 did you check the checkbox on the left (See image)
![Screenshot 2021-06-18 at 21 32 06](https://user-images.githubusercontent.com/3471924/122608602-ce43bd00-d07c-11eb-91ff-e63498fe2f84.png)

**Comment by daysofthunder98** [comment] 2021-06-18 20:37
Nope, I can seem to download the image but the csv file leads to a "not found" link. For now, I am downloading the entire folder and then running tensorboard locally to get the download links.

**Comment by talhaanwarch** [comment] 2021-07-19 22:46
it work in colab in firefox

**Comment by biswas62** [comment] 2021-07-28 12:49
> I have the same problem in Chrome, however strangely it is working normally when using Colab with Firefox, by the way. Maybe this is helpful to someone finding this issue until it gets resolved :)

tnx man. it worked!

**Comment by dralmadani** [comment] 2023-01-06 16:11
That seem strange,
X:  I tried Chrome, and Edge couldn't download CVS or JSON files. OS: Windows 11 Education
but it works with Firefox.  ( [https://www.mozilla.org/en-US/](https://www.mozilla.org/en-US/) )
