### ISSUE TITLE
Text data shown incomplete?

### ISSUE THREAD

**Issue by linzhiqiu** [tensorflow/tensorboard#1258] opened 2018-06-24 21:32 UTC
I used tensorboard add_text() function to store the accuracy for every epoch; however in the end, only a limited number of texts are shown (for example, epoch 1->2->3->10->13->19->28 are shown, everything else is missing). How do I get all the data back? Is there a setting or anything that control the amount of text data to be shown?

**Comment by nfelt** [comment] 2018-06-25 09:01
Duplicate of #83

**Comment by nfelt** [comment] 2018-06-25 09:03
This is a result of the automatic reservoir sampling behavior in TensorBoard which only keeps 10 text summaries by default.  With TensorBoard 1.9 you can customize the number of summaries kept for the text plugin using the `--samples_per_plugin` flag introduced in #1138, e.g. `--samples_per_plugin=text=100` should set the text dashboard to retain 100 samples for each series.

**Closed by nfelt** 2018-06-25 09:03 UTC

**Comment by Harrypotterrrr** [comment] 2020-10-03 04:22
@nfelt hi, I wonder if there is a way to keep indefinite number of the summary text, since I wish to store the model logging output, like the template `Epoch: [%d/%d], Step: [%d/%d], time: %s/%s, loss: %.7f, psnr: %.4f, lr: %.2e` for each step.
Thanks for your help.

**Comment by nfelt** [comment] 2020-10-06 18:19
You can set the value to `0` to instruct TensorBoard to retain all steps; just be cautious since this means memory usage may be unbounded.

**Comment by Harrypotterrrr** [comment] 2020-10-15 16:46
@nfelt Hi, Thanks for your reply. I have just modified my commands starting up the tensorboard as follows:
``` bash
tensorboard --logdir ~/xxx/logs/ --samples_per_plugin='text=0,images=0,scalars=0'
```
but None of the text or images or scalars will show on the board, so I am wondering if there is something wrong with my understanding of the `value 0` of these arguments.
My goal is just to set the tensorboard to show as much as the data it has.
