### ISSUE TITLE
Tensorboard X-axis values are not shown

### ISSUE THREAD

**Issue by ahmedezzat85** [tensorflow/tensorboard#905] opened 2018-01-25 17:47 UTC
TensorFlow version: 1.4.
Python 3.5 Anaconda
Install method: Pip
OS: Seen on both Windows 10 and Ubuntu 16.04
![2018-01-25](https://user-images.githubusercontent.com/12133512/35403310-fbb8ddb6-0207-11e8-8637-dc454767182c.png)

**Comment by chihuahua** [comment] 2018-01-26 05:52
Interesting ... I am having some issues reproducing this issue. What is the x axis set to? Wall time? Relative? Or steps?

**Comment by ahmedezzat85** [comment] 2018-01-26 11:09
It is set to steps.

**Comment by ahmedezzat85** [comment] 2018-01-26 11:14
There is another guy has the same issue on [Stackoverflow](https://stackoverflow.com/questions/47402152/tensorboard-x-axis-values-arent-shown)

**Comment by nfelt** [comment] 2018-01-26 22:11
What browser were you using, on Windows 10 and Ubuntu 16.04?

**Comment by ahmedezzat85** [comment] 2018-01-27 05:11
The problem seems to happen only with firefox Web Browser.
I tried on both Microsoft Edge and google chrome and the problem does not happen.
Not sure what is wrong with firefox.

**Comment by nfelt** [comment] 2018-01-27 05:27
What version of Firefox is this, exactly?  And can you confirm your TensorBoard version as well?  It should print out the version number when it starts up.

**Comment by ahmedezzat85** [comment] 2018-01-27 05:32
WINDOWS
Firefox Version: 58.0 (64-bit)
Tensorboard Version: 0.4.0rc3

Ubuntu
Firefox Version: 57.04 (64-bit)
Tensorboard Version: 0.4.0rc2

**Comment by hermansje** [comment] 2018-04-10 21:06
I also noticed the missing x-axis ticks using the latest versions of Tensorboard and Firefox on Windows 10.
(Tensorboard 1.7.0, Firefox 59.0.2 64 bit)

**Comment by hermansje** [comment] 2018-04-10 21:14
The Plottable repo has some issues about Firefox font rendering that look similar to this one, e.g. https://github.com/palantir/plottable/issues/2211

After decreasing the label font-size a little bit, the labels showed up after the next rerender (at least on my 1080p screen).

**Comment by cindycatrosa** [comment] 2018-05-27 22:08
I have also noticed the missing x-axis labels on Windows 10, Firefox 60.0.1 64-bit with Tensorboard 1.7.0

**Comment by skaematik** [comment] 2018-05-27 22:08
I have also noticed the missing x-axis labels on Windows 10, Firefox 60.0.1 64-bit with Tensorboard 1.7.0

**Comment by melissadale** [comment] 2018-06-20 16:41
I am using Chrome and not seeing x-axis labels, (the tick marks do show however). Should there be labels (e.g. steps)? Can we get labels? 
---
Windows 10
Chrome Version 67.0.3396.79 (Official Build) (64-bit)
TensorBoard: 1.8.0

**Comment by nfelt** [comment] 2018-06-21 17:59
There should be labels on the X-axis, but it seems like something in Plottable isn't consistently rendering them in all cases.

Those of you reporting the issue, could you include 1) a screenshot and ideally 2) attach an events file that when loaded in TensorBoard results in this issue, as well as the browser, OS, and TensorBoard versions.  (In order to fix this we'll need to first be able to consistently reproduce it.)

**Comment by melissadale** [comment] 2018-06-21 20:34
I am hesitant to publicly share the events file. If you can email me, I can share these files with you privately: melissa.r.dale@gmail.com 

**Details**: 
Windows 10
TensorBoard: 1.8.0

**Chrome** Version 67.0.3396.79 (Official Build) (64-bit)
![plots](https://user-images.githubusercontent.com/1429496/41743970-619103d0-7570-11e8-93c9-97aad7fafb67.png)

--- 

I mainly use chrome, but I do have firefox and IE installed on my machine, so I am also including screenshots of the exact same tensorboard. Note, these browsers are likely exceedingly outdated, and I do not have sufficient administrative powers to update these. 

**Firefox**: 45.7.0
![firefox](https://user-images.githubusercontent.com/1429496/41743947-533d587e-7570-11e8-809e-0d32cbf9462d.png)


**IE**: 11.2248.14393.0
![ie](https://user-images.githubusercontent.com/1429496/41743964-5bc0e902-7570-11e8-8833-7e4ba8fe864c.png)

**Comment by nfelt** [comment] 2018-06-21 21:33
@melissadale no problem if the event file is sensitive, my intent wasn't to ask for anything of that nature.  (If anyone on this thread has a non-sensitive reproduction however, that would be very helpful.)  In the Chrome screenshot I'm seeing x-axis labels - did the issue go away?  Or were there other charts that were missing them off-screen?  A screenshot of the affected plots is what would be most helpful (though again, only if it's not too sensitive to share).

**Comment by melissadale** [comment] 2018-06-21 22:32
I see my confusion - My question about whether to expect to see a label or not, I was referring to explaining what the numbers represent, not the actual numbers associated with the ticks. So in this case, I was expecting the label "Steps".  This is clearly a separate issue - would you like me to remove my previous comment to save screen real estate in this thread?

**Comment by nfelt** [comment] 2018-06-21 22:36
@melissadale Ah okay I understand now.  Yes, we don't label the horizontal axis as a whole, though the meaning of the horizontal axis is shown in the selector in the menu bar (step vs wall time vs relative wall time).  Up to you if you'd like to edit your previous comment or not.

**Comment by mpekalski** [comment] 2018-07-11 21:46
I am experiencing the same in Firefox 61.0b9 (64-bit) on Ubuntu. No labels on x axis. It is not visible for steps, relative and wall. The only thing in relative in wall I see name of months and days, but not hours. In case of steps I see nothing. In Chrome it works.

**Comment by x1155665** [comment] 2019-01-15 14:57
I have this issue on Chrome and Firefox. 
On chrome, i found that it was related with the Sans-serif font: setting the sans-serif font back to default solved the issue.

**Comment by theevann** [comment] 2019-05-17 12:26
Is there still no fix to this issue ? I am experiencing the same bug for quite a while now.

**Comment by stephanwlee** [comment] 2019-05-17 14:53
@theevann I have tried to address it last year. Which version of TensorBoard are you using?

**Comment by viniciusguigo** [comment] 2019-05-18 01:11
Same here with TensorBoard 1.12.0. It does not work on Firefox (Quantum, 66.0.5, 64-bit) but it does work on Google Chrome (Version 74.0.3729.131, Official Build, 64-bit). I'm on Ubuntu 16.04 LTS.

**Comment by theevann** [comment] 2019-05-18 11:32
@stephanwlee I am using 1.13.1 on Ubuntu 16 with firefox 66

**Comment by celynwalters** [comment] 2019-09-27 15:21
I found in Firefox, the labels exist, but the CSS style for these has the `visibility: hidden` attribute for some reason.
By overriding the CSS (I use Dark Reader extension to do this they are shown correctly in all plots.
Here's the override I'm using.
```css
.tick-label {
    visibility: visible !important;
}
```
Tested on Firefox 69.0.1 on Ubuntu 16.04.
I can test on Windows and Mac (which are exhibiting the same issue for me, I had no idea there even *were* x axis labels until now) if it would help.

**Comment by celynwalters** [comment] 2019-10-10 13:23
Seems to be fixed in the 2.0 release

**Comment by nfelt** [comment] 2019-12-17 22:30
@celynwalters thanks for the update - I'm going to close in hopes that the 2.0 release fixed this, but if anyone sees this issue with TensorBoard 2.0+ please comment here and we'll re-open.

**Closed by nfelt** 2019-12-17 22:30 UTC
Labels: plugin:scalars, type:browser

**Comment by Zinoex** [comment] 2020-10-21 08:49
Hey, I'm using Tensorboard 2.2.1 and I'm having this exact issue unfortunately. As @celynwalters mentionen, the labels exist, but each text-tag in the SVG has a `style="text-anchor: middle; visibility: hidden;"` attribute. 

My versions:
- Tensorboard: 2.2.1
- Firefox: 81.0
- OS: Manjaro 20.1.1

I'm also attaching the x-axis SVG to showcase where the visibility hidden style is defined. If I remove said style, The labels work perfectly.

```
<g class="tick-label-container" transform="translate(0, 8)">
    <text class="tick-label" style="text-anchor: middle; visibility: hidden;" x="0" y="0" dx="0em" dy="0.95em">-500</text>
    <text class="tick-label" style="text-anchor: middle; visibility: hidden;" x="298.71657126290455" y="0" dx="0em" dy="0.95em">0</text>
    <text class="tick-label" style="text-anchor: middle; visibility: hidden;" x="597.4331425258091" y="0" dx="0em" dy="0.95em">500</text>
    <text class="tick-label" style="text-anchor: middle; visibility: hidden;" x="896.1497137887137" y="0" dx="0em" dy="0.95em">1k</text>
    <text class="tick-label" style="text-anchor: middle; visibility: hidden;" x="1194.8662850516182" y="0" dx="0em" dy="0.95em">1.5k</text>
    <text class="tick-label" style="text-anchor: middle; visibility: hidden;" x="1493.5828563145228" y="0" dx="0em" dy="0.95em">2k</text>
    <text class="tick-label" style="text-anchor: middle; visibility: hidden;" x="1792.2994275774274" y="0" dx="0em" dy="0.95em">2.5k</text>
    <text class="tick-label" style="text-anchor: middle; visibility: hidden;" x="2091.015998840332" y="0" dx="0em" dy="0.95em">3k</text>
</g>
```
