### ISSUE TITLE
Embedding projector's Help icon link is broken

### ISSUE THREAD

**Issue by atn832** [tensorflow/tensorboard#4896] opened 2021-03-30 02:04 UTC
**Describe the current behavior**
1. Go to https://projector.tensorflow.org/
2. Click the Help icon in the upper right corner
3. Opens a new tab that loads https://www.tensorflow.org/get_started/embedding_viz and shows Error 404

**Describe the expected behavior**
It should show me the documentation for the Embedding projector.

**Comment by ymodak** [comment] 2021-08-04 21:25
This is now fixed, clicking on help icon lands you to https://www.tensorflow.org/tensorboard/tensorboard_projector_plugin
Thanks!

**Comment by arghyaganguly** [comment] 2021-08-13 14:55
Closing this ticket as the issue is fixed.Thanks.

**Closed by arghyaganguly** 2021-08-13 14:55 UTC
Labels: plugin:projector, type:docs, stat:awaiting response
