### ISSUE TITLE
TensorBoard has bad graphs after deleting the model directory and retraining

### ISSUE THREAD

**Issue by nealwu** [tensorflow/tensorboard#652] opened 2017-10-18 02:02 UTC
If I have TensorBoard running on a model directory, but then I re-run the model code which deletes the directory and restarts training, TensorBoard ends up with a messy set of graphs with extra data like this:

![screenshot from 2017-10-17 18 49 52](https://user-images.githubusercontent.com/726075/31697538-1299bcc4-b36d-11e7-983d-b391279bb3da.png)

Once I interrupt and restart the `tensorboard` process, it looks fine again:

![screenshot from 2017-10-17 18 56 26](https://user-images.githubusercontent.com/726075/31697548-1fbfe91e-b36d-11e7-9a77-0b3578703350.png)

@jart @chihuahua

**Comment by nfelt** [comment] 2017-12-06 23:26
@nealwu I realize it's been a while, but do you have / could you share the tensorflow model code that you used which resulted in these artifacts?  Also, did you click "refresh" manually from the TensorBoard UI or was it just a result of auto-refreshing?  Useful to know the sequence of refreshes versus model code restarting that produced this.

It looks like this might be a bug in the scalar chart rendering where the leftmost and rightmost points get a line segment mistakenly connecting them, but it's hard to diagnose exactly why that's happening without being able to drill down into the actual data being passed around.

**Comment by nealwu** [comment] 2017-12-07 00:58
Hi @nfelt, I was running the wide_deep model from here: https://github.com/tensorflow/models/tree/master/official/wide_deep. I think it would happen either if I manually refreshed or if TensorBoard auto-refreshed.

If you want to get that model up and running quickly, just follow the commands from this section: https://github.com/tensorflow/models/tree/master/official/wide_deep#running-the-code.

**Comment by nfelt** [comment] 2017-12-12 01:30
Duplicate of #803

**Comment by nfelt** [comment] 2017-12-12 01:43
Looking into this more, I think it's best resolved by making event purging for out-of-order steps work again, which was reported separately in #803 and which I have a PR out to implement.  The graphs look weird because when the model script re-evaluates, the new data gets picked up as a continuation of the old data, even though they're using the same step sequence, resulting in the data series "zig-zagging" back to 0 on the horizontal axis and then appearing to overlay over the old data.  If you change the horizontal axis setting to relative or wall time instead of "step" then the issue is much more apparent.  Adding event purging logic should cause the old data to be purged when the new "step 1" arrives.

Note that strictly speaking this is a different condition because we're actually redoing the whole dataset from scratch, so it would be more correct to dump the entire set of data TensorBoard has loaded, not just data at a higher step count (since in theory, the new run might not start at step 1).  And that is in fact supposed to work, where the background reload process detects directory deletion and purges all the data from that directory.  However, the reload process only runs so often and so if the directory is only gone very briefly, it might not observe that happening.  This appears to be the typical case with running `python wide_deep.py` - the script deletes the `/tmp/census_model` directory but then calls logic that must recreate it very soon after, and TensorBoard usually doesn't notice.  In my testing, it did generally pick up on the `eval` subdirectory deletion, just not the `.` directory run itself.

I'm not aware of an easy way for TensorBoard to detect directory deletion even when it's very brief (if a permanent directory creation time were available, that might work, but I'm not sure that would work cross-platform), so I think it's best to just let the event purging logic handle this in your case.

Note that this could also be worked around on the user end by inserting a delay at least as long as the reload interval (by default 5 seconds, settable with `--reload_interval`) between deleting the directory and recreating it.

**Closed by nfelt** 2017-12-12 01:43 UTC
Labels: plugin:scalars, type:bug/performance

**Comment by nealwu** [comment] 2017-12-12 02:54
Thanks Nick. So to clarify, it sounds like your pull request will help handle most cases, including mine?

**Comment by nfelt** [comment] 2017-12-12 21:39
Yes, re-enabling purging should fix your case, as long as you're always starting over from the same step count.

**Comment by nfelt** [comment] 2017-12-19 01:36
This should be addressed by https://github.com/tensorflow/tensorboard/pull/807 now.

**Comment by nealwu** [comment] 2017-12-19 02:31
Thanks Nick! If the issue comes up again I'll let you know. (Though I assume I'll need to wait until TF 1.5 to check.)
