### ISSUE TITLE
Sawtooth visualization of constant value

### ISSUE THREAD

**Issue by galeone** [tensorflow/tensorboard#1041] opened 2018-03-13 09:10 UTC
I'm logging at each time step a float value, that's always equal to 1 (as expected).
Although the logged value is constant (1.00) sometimes the visualization flips from high to low in a sawtooth fashion (see attached screenshots).
Also, there's no scale along the Y-axis.

 - TensorBoard version: 1.6.0
 - TensorFlow version: 1.6.0
 - OS Platform and version: Archlinux
 - Python version: 3.6
 - For browser-related issues:
   - Browser type and version: tested with Firefox 58 and Chromium 65
   - Screenshots:

![screenshot_20180313_100619](https://user-images.githubusercontent.com/8427788/37332245-66ffc43c-26a6-11e8-884e-d25d8f6d75dd.png)
![screenshot_20180313_100559](https://user-images.githubusercontent.com/8427788/37332246-671aef3c-26a6-11e8-8ffa-76361e5396eb.png)

**Comment by galeone** [comment] 2018-03-13 09:13
![screenshot_20180313_101236](https://user-images.githubusercontent.com/8427788/37332462-12e7acc4-26a7-11e8-8cf0-344f35de849d.png)

Things are getting worse as the training goes on. The scale has appeared along the Y-axis. The value is now constant but it's completely wrong.

**Comment by nfelt** [comment] 2018-03-13 19:37
Duplicate of #786

**Comment by nfelt** [comment] 2018-03-13 19:38
Thank you for the report!  Assuming this only happens when smoothing is enabled, then I think this is already tracked in #786.

**Closed by nfelt** 2018-03-13 19:38 UTC
