### ISSUE TITLE
Bug: tensorboard logdir can't contain escaped colon

### ISSUE THREAD

**Issue by benjamin9555** [tensorflow/tensorboard#2229] opened 2019-05-14 02:06 UTC
- TensorBoard version: 1.13.1
 - TensorFlow version: 1.13.1
 - OS Platform and version: MacOS 10.13.6
 - Python version: 3.7.3
 
When I run e.g. the command
``` 
tensorboard --logdir runs/2019-05-13T21\:15\:44.638426/summary/
```
tensorboard does not detect the summary and shows an empty board:

<img width="1427" alt="Screen Shot 2019-05-13 at 21 59 05" src="https://user-images.githubusercontent.com/8866751/57665597-78ada400-75ca-11e9-8876-3dddd32b4ecf.png">

However, if I `cd` into the directory from above and then run `tensorboard --logdir=./`, it works fine.
I know, it's not recommended to use colons in unix filenames, but it would be nice if you could throw a warning to make the user aware that this is the issue.

**Comment by nfelt** [comment] 2019-05-16 22:10
Duplicate of #1220

**Comment by nfelt** [comment] 2019-05-16 22:12
Thanks for the report.  Yes, this is because a feature (or perhaps misfeature) of the logdir parsing is that you can specify multiple logdirs separated by commas and optionally named with colon-terminated prefixes.  It's not a great implementation because 1) it's hard to understand that it's doing this in the first place and 2) there's no way to escape it.

Deduped with #1220 which already exists for commas, since it's fundamentally the same problem.

**Closed by nfelt** 2019-05-16 22:12 UTC
Labels: core:backend, stat:awaiting tensorflower, type:bug/performance
