### ISSUE TITLE
Tensorboard 1.7.0 windows 10  application.py:272] path /[[_dataImageSrc]] not found, sending 404 issue

### ISSUE THREAD

**Issue by sdk21** [tensorflow/tensorboard#1134] opened 2018-04-15 22:35 UTC
- TensorBoard version (from pip package, also printed out when running `tensorboard`)
 1.7.0
 - TensorFlow version if different from TensorBoard
1.7.0
 - OS Platform and version (e.g., Linux Ubuntu 16.04)
Windows 10
 - Python version (e.g. 2.7, 3.5)
3.6
 - For browser-related issues:
   - Browser type and version (e.g. Chrome 64.0.3282.140)
   - Screenshot if it's a visual issue
 
I ran word2vec tutorial https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/tutorials/word2vec on the system described above. However, when I start tensorboard with the following cmd from the folder where log is present and open the url on browser (firefox) I get the 404 error
tensorboard --logdir=log
**W0415 18:24:40.218479 Thread-2 application.py:272] path /[[_imageURL]] not found, sending 404
W0415 18:24:40.218479 Thread-1 application.py:272] path /[[_dataImageSrc]] not found, sending 404**

I have tried different variation of the log path including
--logdir=word2vec:C:\Users\xxxxx\tensorflow\word2vec\log
--logdir="C:\Users\xxxxx\tensorflow\word2vec\log"
--logdir=C:/Users/xxxxx/tensorflow/word2vec/log

On inspect, I get following.
tensorboard --logdir=log --inspect

Found event files in:
log

These tags are in log:
audio -
histograms -
images -
scalars
   loss_1
tensor -

Event statistics for log:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms -
images -
scalars
   first_step           0
   last_step            100000
   max_step             100000
   min_step             0
   num_steps            100001
   outoforder_steps     [(100000, 0)]
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -
tensor -

**I ran same set of command on my macbook, there I had no problem using tensorboard and was able to visualize graphs, embedding, etc.**

**Comment by jart** [comment] 2018-04-20 05:35
It seems strange that TensorBoard is sending those requests, since you probably didn't open the Debugger or Beholder dashboards. I'd like to know why that's happening and contributions are welcome. Although I can't tell for certain if that's the root cause of the issue you're experiencing.

**Comment by draliii** [comment] 2018-04-26 12:00
I had the same issue when visualising my learning with tensorflow 1.7 on python 3.5.3 running on debian. Some runs wouldn't show at all, even those that were there the day before. It was caused by low disk space, deleting some old models and restarting tensorboard worked for me.

**Comment by nfelt** [comment] 2018-05-02 19:45
Duplicate of #982

**Comment by nfelt** [comment] 2018-05-02 19:47
Thanks @humphd, I agree the 404 issue is a dupe of #982.  I don't think it's actually relevant to the original issue that @sdk21 was having, which sounds like TensorBoard wasn't showing any data?

@sdk21 if you're still having that issue, it'd be helpful if you could provides screenshots and described in a little more detail what isn't working.

**Comment by sdk21** [comment] 2018-05-05 02:36
Hi all,
It turns out the problem was with my version of firefox (45.x). I upgraded it to 52.x and it worked for me. 404 is still persistent and is not relevant to the issue I was having. 
Thanks.

**Comment by stephanwlee** [comment] 2019-05-03 23:17
Very late spring clean: I believe this is closed like #982. Thanks for sending us the issue!

**Closed by stephanwlee** 2019-05-03 23:17 UTC
Labels: (╯°□°)╯windows, stat:contributions welcome
