### ISSUE TITLE
Tensorboard callback: File size is huge when write_graph=true.

### ISSUE THREAD

**Issue by adityaiitb** [tensorflow/tensorboard#3188] opened 2020-01-28 21:15 UTC
Using the API on this page https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard, when we set write_graph = True, we get a very big file (~ 500 MB for Resnet50). The documentation actually mentions this fact. Upon inspection, I realized that the size is big because for some nodes the graph contains the actual tensor values (tensor_content).

Is it possible to add a flag so that the tensor values are not dumped.

**Comment by wchargin** [comment] 2020-01-28 22:26
Hi @adityaiitb! Thanks for the feature request. There’s indeed not a
trivial way to do this, as the graph collection is done by the TF eager
runtime itself. I’m not an expert here, but I think that to accommodate
this we’d want to change either the [initialization code here][1] or the
[collection code here][2] to take into account a new property on the
execution context (like the existing [`ShouldStoreGraphs`][3]), and then
modify `tf.summary.trace_on` to allow configuring that new property.

To clarify, this issue shouldn’t be a big problem if you’re trying to
view these graphs in TensorBoard, because we don’t send large attributes
down to the frontend, but this will crop up if you’re inspecting the
event files yourself.

For transparency, this probably won’t be on our short-term priorities,
but I’ll keep it open as a feature request.

[1]: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/process_function_library_runtime.cc#L643-L648
[2]: https://github.com/tensorflow/tensorflow/blob/ef6080ee219c875d15c5a4dc6dc3d58e89c2fb0b/tensorflow/core/framework/op_kernel.h#L606-L622
[3]: https://github.com/tensorflow/tensorflow/blob/ef6080ee219c875d15c5a4dc6dc3d58e89c2fb0b/tensorflow/core/common_runtime/eager/context.h#L249-L250

**Comment by nfelt** [comment] 2020-01-29 22:26
Duplicate of #1252

**Closed by nfelt** 2020-01-29 22:26 UTC
Labels: core:summaries, plugin:graph, type:feature
