### ISSUE TITLE
not find log file in Windows

### ISSUE THREAD

**Issue by pangbochen** [tensorflow/tensorboard#614] opened 2017-10-04 08:02 UTC
I use Windows 10,
python is in C;, I run the sample python minist code and store the log file in f:\log\minist
I open the cmd shall and inputs  tensorboard --logdir=f:\log\minist
and it shows "Not find log" on the chrome webpage.

update I finally make it after 1 hour
1.
because of windows file system and tensorboard itself I guess, you should change the dir first
that is,
cd f:
cd f:\log\minist
 tensorboard --logdir=f:\log\minist

wish it helps you all
have a nice moon day!

**Comment by wchargin** [comment] 2017-10-04 23:00
Duplicate of #52.

**Closed by wchargin** 2017-10-04 23:00 UTC
