### ISSUE TITLE
Why --logdir_spec is discouraged and what explicit features not supported when this flag is used?

### ISSUE THREAD

**Issue by LuoXin-s** [tensorflow/tensorboard#5438] opened 2021-11-29 13:19 UTC
I think running tensorboard on multiple custom folds is a normal and frequent operation, why there is no full support for this feature?

**Comment by bileschi** [comment] 2021-11-29 21:40
TensorBoard does not support `--logdir_spec` internally very well because some plugins and features were designed on the assumption that there is exactly one root logdir.  For instance, `projector`, `--load_fast`, and `tf2-debugger` are known not to work. 

As a workaround, the user can create a symlink tree on their root filesystem, and hand that to tensorboard.

For example, in Unix instead of:
```
$ tensorboard --logdir_spec name1:/path/to/logs/1,name2:/path/to/logs/2
```

do:
```
$ mkdir /tmp/tmp-root
$ ln -s /path/to/logs/1 /tmp/tmp-root/name1
$ ln -s /path/to/logs/3 /tmp/tmp-root/name2
$ tensorboard --logdir /tmp/tmp-root
```

Does this solve your issue?

**Comment by LuoXin-s** [comment] 2021-11-30 01:46
@bileschi 
Okay, it appears feasible for most cases. But if one folder is involved in multiple TensorBoard running, we have to create many different temporary root directories, it seems some kinds of inconvenient

**Comment by LuoXin-s** [comment] 2021-11-30 02:04
@bileschi  I also have a question, how tag of `--load_fast` is used for? I can not find any explanation in README.

**Comment by bileschi** [comment] 2021-11-30 14:00
Re. "one-folder-multi-tb":  Is it the case that you are running many instances of TensorBoard simultaneously on the same machine?  We're curious about this use case.  How often do you need to start / stop TensorBoard instances and how do you manage to keep them straight which is which?

Re "load_fast": more details here : https://github.com/tensorflow/tensorboard/issues/4784

**Comment by LuoXin-s** [comment] 2021-12-01 01:31
@bileschi  For "one-folder-multi-tb", I mean I may need to compare results of configuration, and one configuration can be involved in multiple compare, also I usually will run one compare again. If I use "symlink tree" method, the temporary direction will be kept for future use, is this the expected result?

**Comment by bileschi** [comment] 2021-12-01 15:09
I'm sorry, I don't totally understand the question. Can you try asking again in a different way?

It sounds like maybe you're asking about the permanence of symlinks?  Or are you maybe asking about having the same directory included multiple times with different names in the same TensorBoard?

**Comment by LuoXin-s** [comment] 2021-12-02 01:13
@bileschi It's more like the permanence of symlinks, but if I do need to generate symlinks and use a temporary folder, In long-tern, there are many of these folders, and how to reuse them is a problem. For example, I have a command "tensorboard --logdir A:folder1, B:folder2, C:folder", I can also delete part of this command and get "tensorboard --logdir A:folder1, B:folder2" conveniently.

**Comment by bileschi** [comment] 2021-12-02 15:48
I see.  The effect of removing `C:folder` from the --logdir_spec can be reproduced by turning on and off specific subdirectories by filtering on the run name, right?

This leaves the problem of "too many subdirectories."  Is this also a problem for you?

![image](https://user-images.githubusercontent.com/547150/144455182-dd4f6790-3ce6-41bc-a6c2-a42340a43499.png)
![image](https://user-images.githubusercontent.com/547150/144455351-d406255c-f085-4b08-ac3e-94b95fb12374.png)

**Comment by bileschi** [comment] 2021-12-09 15:42
@LuoXin-s does the symlink & filter workaround work for you?  If no, can you please explain the remaining friction?

**Comment by bileschi** [comment] 2021-12-13 18:43
Marking as closed.  @LuoXin-s please re-open if this remains an issue for you.  Thanks!

**Closed by bileschi** 2021-12-13 18:43 UTC

**Comment by yodahuang** [comment] 2022-01-13 02:24
Another problem with symlink + filter is that it doesn't work well with cloud storage, e.g. S3. 
You can't really create a symbolic link to a S3 prefix in local file system. Alternatively, you can copy the event file from cloud storage to local, but then you lose the real-time refresh functionality.

**Comment by Robotatron** [comment] 2022-12-29 21:16
> TensorBoard does not support `--logdir_spec` internally very well because some plugins and features were designed on the assumption that there is exactly one root logdir. For instance, `projector`, `--load_fast`, and `tf2-debugger` are known not to work.
> 
> As a workaround, the user can create a symlink tree on their root filesystem, and hand that to tensorboard.
> 
> For example, in Unix instead of:
> 
> ```
> $ tensorboard --logdir_spec name1:/path/to/logs/1,name2:/path/to/logs/2
> ```
> 
> do:
> 
> ```
> $ mkdir /tmp/tmp-root
> $ ln -s /path/to/logs/1 /tmp/tmp-root/name1
> $ ln -s /path/to/logs/3 /tmp/tmp-root/name2
> $ tensorboard --logdir /tmp/tmp-root
> ```
> 
> Does this solve your issue?

Does not work, Tensorboard "does not see" runs inside the symlinks. If I hard copy a folder it works.
