### ISSUE TITLE
The "upload" button doesn't work in the online embedding projector

### ISSUE THREAD

**Issue by Fanchao-Qi** [tensorflow/tensorboard#911] opened 2018-01-26 13:46 UTC
I find that the "upload bookmark file" button doesn't work in the [projector.tensorflow.org](projector.tensorflow.org). 
I can download the bookmark file but I can't upload it.

**Comment by MarkDaoust** [comment] 2018-04-10 17:02
This is a duplicate of #835

**Comment by nfelt** [comment] 2018-04-11 05:26
Duplicate of #835

**Comment by nfelt** [comment] 2018-04-11 05:26
Thanks @MarkDaoust for pointing that out!  There is some further discussion on #835.

**Closed by nfelt** 2018-04-11 05:26 UTC
Labels: plugin:projector
