### ISSUE TITLE
Lines outside plot's window with smoothing

### ISSUE THREAD

**Issue by lcswillems** [tensorflow/tensorboard#1227] opened 2018-06-05 14:19 UTC
![image](https://user-images.githubusercontent.com/5437552/40981815-e3bcfacc-68a9-11e8-986f-c0886a3e6aae.png)

With smoothing 0.999, one of the line is not in the plot window.

**Comment by nfelt** [comment] 2018-06-22 02:08
If you still have access to this plot, could you provide screenshots of it without smoothing (a setting of 0) and also confirm whether you have the "ignore outliers" option checked?  If you did have the outlier ignoring enabled, this might be a duplicate of #651.

**Comment by lcswillems** [comment] 2018-06-22 02:54
It is a duplicate of #651, thank you for the help!

**Comment by nfelt** [comment] 2018-06-22 17:50
Duplicate of #651

**Closed by nfelt** 2018-06-22 17:51 UTC
Labels: plugin:scalars, type:bug/performance
