### ISSUE TITLE
tensorboard 2.0.0 doesn't build with bazel 0.29.1

### ISSUE THREAD

**Issue by svenstaro** [tensorflow/tensorboard#2709] opened 2019-10-01 07:48 UTC
I can't build tensorboard 2.0.0 with bazel 0.29.1:

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from https://mirror.bazel.build/nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: target //tensorboard:tensorboard (1 packages loaded)
Analyzing: target //tensorboard:tensorboard (1 packages loaded, 0 targets configured)
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at /build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl:124:19):
 - /build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/tensorflow/workspace.bzl:429:5
 - /build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/tensorflow/workspace.bzl:58:5
 - /build/tensorboard/src/tensorboard-2.0.0/WORKSPACE:96:1
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
	File "/build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl", line 104
		_apply_patch(ctx, ctx.attr.patch_file)
	File "/build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl", line 71, in _apply_patch
		_execute_and_check_ret_code(ctx, cmd)
	File "/build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
		fail("Non-zero return code({1}) when ...))
	File "/build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl", line 52, in fail
		"Non-zero return code({1}) when executing '{0}':\nStdout: {2}\nStderr: {3}".format(" ".join(cmd_and_args), result.ret..., <2 more arguments>)
	File "/build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl", line 54, in "Non-zero return code
		" ".join(cmd_and_args)
sequence element must be a string (got 'path'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
ERROR: /build/tensorboard/src/tensorboard-2.0.0/tensorboard/BUILD:215:1: //tensorboard:dynamic_plugins depends on //tensorboard/plugins/projector:projector_plugin in repository @ which failed to fetch. no such package '@com_google_protobuf//': Traceback (most recent call last):
	File "/build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl", line 104
		_apply_patch(ctx, ctx.attr.patch_file)
	File "/build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl", line 71, in _apply_patch
		_execute_and_check_ret_code(ctx, cmd)
	File "/build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
		fail("Non-zero return code({1}) when ...))
	File "/build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl", line 52, in fail
		"Non-zero return code({1}) when executing '{0}':\nStdout: {2}\nStderr: {3}".format(" ".join(cmd_and_args), result.ret..., <2 more arguments>)
	File "/build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/third_party/repo.bzl", line 54, in "Non-zero return code
		" ".join(cmd_and_args)
sequence element must be a string (got 'path'). See https://github.com/bazelbuild/bazel/issues/7802 for information about --incompatible_string_join_requires_strings.
ERROR: Analysis of target '//tensorboard:tensorboard' failed; build aborted: Analysis failed
INFO: Elapsed time: 77.813s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (30 packages loaded, 128 targets configured)
FAILED: Build did NOT complete successfully (30 packages loaded, 128 targets configured)
```

**Comment by rmothukuru** [comment] 2019-10-01 09:08
Please provide details about what platform you are using (operating system, architecture). 

Make sure you also include the exact command to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by svenstaro** [comment] 2019-10-01 14:54
Sorry, for some reason I didn't see that particular template.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.0.0
- Python version: 3.7.4
- Installed using virtualenv? pip? conda?: Neither
- Bazel version (if compiling from source): 0.29.1
- GCC/Compiler version (if compiling from source): 9.1.0
- CUDA/cuDNN version: 10.1.243/7.6.3.30
- GPU model and memory: None



**Describe the problem**

Building tensorboard fails.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
  bazel build tensorboard:tensorboard
  bazel build //tensorboard/pip_package:build_pip_package
```

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Log posted in primary issue.

**Comment by wchargin** [comment] 2019-10-01 15:32
Hi @svenstaro! This looks like a problem in the dependent TensorFlow
workspace. Unfortunately, the error handling appears to be a bit broken.
Please clone TensorFlow and check out `v2.0.0-rc0` (`c75bb66a99ad`),
then apply the following patch:

```diff
diff --git a/third_party/repo.bzl b/third_party/repo.bzl
index 4fc91afb36..72529f12f2 100644
--- a/third_party/repo.bzl
+++ b/third_party/repo.bzl
@@ -51,7 +51,7 @@ def _execute_and_check_ret_code(repo_ctx, cmd_and_args):
     if result.return_code != 0:
         fail(("Non-zero return code({1}) when executing '{0}':\n" + "Stdout: {2}\n" +
               "Stderr: {3}").format(
-            " ".join(cmd_and_args),
+            " ".join([str(x) for x in cmd_and_args]),
             result.return_code,
             result.stdout,
             result.stderr,
```

Then, run `bazel build @com_google_protobuf//:protobuf_headers` and see
what error it prints out (which should now be properly reported)?

It may be that the manual `_apply_patch` logic can be replaced with
Bazel’s built-in patching mechanism (TensorFlow’s was added in 2017,
which [predates Bazel’s built-in support][1]).

[1]: https://github.com/bazelbuild/bazel/commit/7831d8c9be23d419a64dfbc48e09fa175e1f1536

**Comment by svenstaro** [comment] 2019-10-02 01:56
I did as you asked but the output is a bit weird:

```
bazel build @com_google_protobuf//:protobuf_headers    
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=102
INFO: Reading rc options for 'build' from /home/svenstaro/src/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone --strategy=Genrule=standalone -c opt --announce_rc --define=grpc_no_ares=true --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --config=v2
INFO: Reading rc options for 'build' from /home/svenstaro/src/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python --action_env PYTHON_LIB_PATH=/usr/lib/python3.7/site-packages --python_path=/usr/bin/python --config=xla --action_env TF_NEED_OPENCL_SYCL=0 --action_env TF_NEED_ROCM=0 --action_env TF_NEED_CUDA=1 --action_env CUDA_TOOLKIT_PATH=/opt/cuda --action_env TF_CUDA_VERSION=10.0 --action_env CUDNN_INSTALL_PATH=/usr/lib --action_env TF_CUDNN_VERSION=7 --action_env NCCL_INSTALL_PATH=/usr/lib --action_env NCCL_HDR_PATH=/usr/lib/../include --action_env TF_NCCL_VERSION=2 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.0,3.5,5.2,6.1,6.2,7.0,7.2,7.5 --action_env TF_CUDA_CLANG=0 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/gcc-7 --config=cuda
INFO: Found applicable config definition build:v2 in file /home/svenstaro/src/tensorflow/.bazelrc: --define=tf_api_version=2
INFO: Found applicable config definition build:v2 in file /home/svenstaro/src/tensorflow/.tf_configure.bazelrc: --define=tf_api_version=2
INFO: Found applicable config definition build:xla in file /home/svenstaro/src/tensorflow/.tf_configure.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:cuda in file /home/svenstaro/src/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/svenstaro/src/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain
INFO: Call stack for the definition of repository 'local_config_cuda' which is a cuda_configure (rule definition at /home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl:1268:18):
 - /home/svenstaro/src/tensorflow/tensorflow/workspace.bzl:68:5
 - /home/svenstaro/src/tensorflow/WORKSPACE:19:1
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 988, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 714, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 694, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cuda.h matching version '10.0' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/opt/cuda'

ERROR: /home/svenstaro/.cache/bazel/_bazel_svenstaro/711cb9f951a09cc976ed3f555206ed79/external/com_google_protobuf/BUILD:219:1: @com_google_protobuf//:protobuf_headers depends on @local_config_cuda//crosstool:toolchain in repository @local_config_cuda which failed to fetch. no such package '@local_config_cuda//crosstool': Traceback (most recent call last):
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 988, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 714, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 694, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cuda.h matching version '10.0' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/opt/cuda'

ERROR: Analysis of target '@com_google_protobuf//:protobuf_headers' failed; build aborted: no such package '@local_config_cuda//crosstool': Traceback (most recent call last):
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 1266
		_create_local_cuda_repository(repository_ctx)
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 988, in _create_local_cuda_repository
		_get_cuda_config(repository_ctx)
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 714, in _get_cuda_config
		find_cuda_config(repository_ctx, ["cuda", "cudnn"])
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 694, in find_cuda_config
		auto_configure_fail(("Failed to run find_cuda_config...))
	File "/home/svenstaro/src/tensorflow/third_party/gpus/cuda_configure.bzl", line 325, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Failed to run find_cuda_config.py: Could not find any cuda.h matching version '10.0' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/opt/cuda'

INFO: Elapsed time: 0.240s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    Fetching @local_config_cc; fetching
```
This is probably not the error you want to see. This is weird, too, because:
```
ls -lha /opt/cuda/include/cuda.h
-rw-r--r-- 1 root root 574K Aug 20 00:49 /opt/cuda/include/cuda.h
```

**Comment by svenstaro** [comment] 2019-10-02 01:58
Also, could you explain why we're doing this in the tensorflow repo and not tensorboard?

**Comment by wchargin** [comment] 2019-10-02 02:23
Hmm; that is indeed not what I expected. I would go so far as to say
that this appears to be an entirely different error, though that itself
is strange.

Is your `/opt/cuda/include/cuda.h` maybe for a version other than 10.0,
judging from the error message?

> Also, could you explain why we're doing this in the tensorflow repo
> and not tensorboard?

Only because we needed to apply that patch to TensorFlow’s `repo.bzl`
for the errors to be printed correctly; otherwise this could have been
done just within TensorBoard. (Well, it still could’ve, but applying the
patch would have been trickier.)

TensorBoard’s build system depends on TensorFlow’s—you can see how we
get here from the build target stack trace (most recent call first):

```
 - /build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/tensorflow/workspace.bzl:429:5
 - /build/.cache/bazel/_bazel_builduser/16a9d96650c79965c8c2ccb42c1699ae/external/org_tensorflow/tensorflow/workspace.bzl:58:5
 - /build/tensorboard/src/tensorboard-2.0.0/WORKSPACE:96:1
```

That is: TensorBoard’s `WORKSPACE` calls into TensorFlow, and it goes
from there.

Given that you’re hitting errors with CUDA and protobuf, both of which
are defined in TensorFlow and used only transitively by TensorBoard,
you’ll probably want to file an issue against TensorFlow (maybe
searching around for open Arch issues first?). If this is resolved
upstream, we should be able to fast-forward our TensorFlow build
dependency to pull in the fix.

TF bug tracker link:
<https://github.com/tensorflow/tensorflow/issues/new/choose>

**Comment by svenstaro** [comment] 2019-10-02 02:32
Just FYI I'm actually the Arch downstream maintainer for tensorboard and tensorflow. tensorflow 2.0.0 compiles just fine on Arch: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/tensorflow

I used the exact same set of env vars to run your command and expected it to keep working.

**Comment by wchargin** [comment] 2019-10-02 02:53
Is there perhaps a discrepancy between the `v2.0.0-rc0` ref that we
depend on and the `v2.0.0` ref that your `PKGBUILD` uses? You could try
fast-forwarding our TensorFlow dep—

```diff
diff --git a/WORKSPACE b/WORKSPACE
index a1b7b48b..1e460fdd 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -84,11 +84,11 @@ http_archive(
     name = "org_tensorflow",
     # NOTE: when updating this, MAKE SURE to also update the protobuf_js runtime version
     # in third_party/workspace.bzl to >= the protobuf/protoc version provided by TF.
-    sha256 = "48ddba718da76df56fd4c48b4bbf4f97f254ba269ec4be67f783684c75563ef8",
-    strip_prefix = "tensorflow-2.0.0-rc0",
+    sha256 = "49b5f0495cd681cbcb5296a4476853d4aea19a43bdd9f179c928a977308a0617",
+    strip_prefix = "tensorflow-2.0.0",
     urls = [
-        "http://mirror.tensorflow.org/github.com/tensorflow/tensorflow/archive/v2.0.0-rc0.tar.gz",  # 2019-08-23
-        "https://github.com/tensorflow/tensorflow/archive/v2.0.0-rc0.tar.gz",
+        "http://mirror.tensorflow.org/github.com/tensorflow/tensorflow/archive/v2.0.0.tar.gz",  # 2019-09-27
+        "https://github.com/tensorflow/tensorflow/archive/v2.0.0.tar.gz",
     ],
 )
 
```

—to use the same version, and see if that resolves the problem?
(Conversely, you could try running your `PKGBUILD` against `v2.0.0-rc0`,
but that would probably take longer.)

**Comment by svenstaro** [comment] 2019-10-08 17:30
Building it against 2.0.0 didn't work but against 364fecb68c48dd4c4fc89fdaede51f29550b612e0c70be33c8ff880e3d535128 it built so I dunno. Probably solved.

**Comment by svenstaro** [comment] 2019-10-08 17:34
I'll leave this open. Close this if you like. It's not really solved in the current repo state and needs a more modern version of tensorflow apparently.

**Comment by wchargin** [comment] 2019-10-08 17:54
Okay; I’ll leave this open until we upgrade our workspace dep past
a6ba397. Thanks for looking into this, and glad that you found a working
version!

**Comment by hnhoangphuong** [comment] 2019-12-16 04:34
Check patch in  C:\msys64\var\lib\pacman\local\
run pacman -S patch to unzip the patch package to path above

**Comment by wchargin** [comment] 2020-01-23 02:27
@svenstaro: As of #3156, we’ve updated our TensorFlow dep to `v2.1.0`,
which is past a6ba397ac0bb. I’m going to tentatively close this since
our last conclusion was that we expect this to solve the issue. If
you’re still seeing issues, please feel free to post back here and we
can reopen it.

Thanks for all your work on Arch! :D

**Closed by wchargin** 2020-01-23 02:27 UTC
Labels: type:build/install

**Comment by akdeepak** [comment] 2020-02-28 18:05
Dear Team  - We are building the stand alone version of the embedding projector to launch it in standalone mode:
We face an issue when we try to build the 
**System information**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)
TensorFlow version: 2.0.0
Python version: 3.6.7
Installed using virtualenv? pip? conda?: created virtualenv for build process
Bazel version (if compiling from source): bazel 2.1.0-
( installed the bazel through the conda version )
GCC/Compiler version (if compiling from source): gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
CUDA/cuDNN version: 10.0.13.0 / 7.6.5
GPU model and memory:  Tesla K80 (inside virtual machine via Nvidia Virtual GPU), 8GB memory
**Describe the problem**
We wanted to run the embedding projector in the stand alone mode .

During the build/run process of the " bazel run tensorboard/plugins/projector/vz_projector:devserver "
build failes with the below issues 

or/vz_projector:devserver
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/repo.bzl:121:19):
 - /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/tensorflow/workspace.bzl:434:5
 - /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/tensorflow/workspace.bzl:434:5
 - /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/tensorflow/workspace.bzl:61:5
 - /opt/karunde1/tensorboard/WORKSPACE:94:1
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, <1 more arguments>)
        File "/root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "/root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(1) when executing 'patch -p1 -d /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/com_google_protobuf -i /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/protobuf/protobuf.patch':
Stdout:
Stderr: src/main/tools/process-wrapper-legacy.cc:58: "execvp(patch, ...)": No such file or directory
INFO: Call stack for the definition of repository 'remote_java_tools_linux' which is a http_archive (rule definition at /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:260:1
INFO: Call stack for the definition of repository 'com_microsoft_typescript' which is a filegroup_external (rule definition at /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/io_bazel_rules_closure/closure/filegroup_external.bzl:186:22):
 - /opt/karunde1/tensorboard/third_party/js.bzl:81:3
 - /opt/karunde1/tensorboard/third_party/js.bzl:81:3
 - /opt/karunde1/tensorboard/third_party/workspace.bzl:35:3
 - /opt/karunde1/tensorboard/WORKSPACE:98:1
INFO: Call stack for the definition of repository 'remotejdk11_linux' which is a http_archive (rule definition at /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/bazel_tools/tools/build_defs/repo/http.bzl:292:16):
 - /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/bazel_tools/tools/build_defs/repo/utils.bzl:205:9
 - /DEFAULT.WORKSPACE.SUFFIX:216:1
ERROR: /opt/karunde1/tensorboard/tensorboard/java/org/tensorflow/tensorboard/vulcanize/BUILD:5:1: //tensorboard/java/org/tensorflow/tensorboard/vulcanize:Vulcanize depends on @com_google_protobuf//:protobuf_java in repository @com_google_protobuf which failed to fetch. no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, <1 more arguments>)
        File "/root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "/root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(1) when executing 'patch -p1 -d /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/com_google_protobuf -i /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/protobuf/protobuf.patch':
Stdout:
Stderr: src/main/tools/process-wrapper-legacy.cc:58: "execvp(patch, ...)": No such file or directory
ERROR: Analysis of target '//tensorboard/plugins/projector/vz_projector:devserver' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, <1 more arguments>)
        File "/root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "/root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(1) when executing 'patch -p1 -d /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/com_google_protobuf -i /root/.cache/bazel/_bazel_root/6dc585ed86201643ce7bf85806089361/external/org_tensorflow/third_party/protobuf/protobuf.patch':
Stdout:
Stderr: src/main/tools/process-wrapper-legacy.cc:58: "execvp(patch, ...)": No such file or directory
INFO: Elapsed time: 65.152s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (40 packages loaded, 65 targets co\
FAILED: Build did NOT complete successfully (40 packages loaded, 65 targets co\
nfigured)

Kindly request to help here to solve the problem to the earliest
Thanks in advance
Many thanks & Kind regards
Deepak

**Comment by wchargin** [comment] 2020-02-28 18:16
Hi @akdeepak—at a glance, this looks like a different (unrelated) issue
with TensorFlow’s repo patching mechanism. Could you try cloning the
TensorFlow repo and running

```
bazel build @com_google_protobuf//:protobuf_java
```

? If this also fails, then the problem is in TensorFlow and will need to
be resolved there. I suspect that there’s a problem with your execution
environment (`patch` not on path?) rather than a problem with TF itself.

If the TensorFlow build works but TensorBoard build fails, please open a
new issue in this repo and let us know which commit of TensorBoard
you’re building from.

**Comment by akdeepak** [comment] 2020-02-28 18:55
Hi @wchargin - Thank you for the kind response.

As suggested by you - I have cloned the tensorflow version from git hub_(https://github.com/tensorflow/tensorflow/tree/r2.0)_  and i face the same error - for your reference please

ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "/opt/tensorflow/third_party/repo.bzl", line 110
                _apply_patch(ctx, <1 more arguments>)
        File "/opt/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "/opt/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(1) when executing 'patch -p1 -d /root/.cache/bazel/_bazel_root/ea717b869aa15cb393fe56d1dfe1f187/external/com_google_protobuf -i /opt/tensorflow/third_party/protobuf/protobuf.patch':
Stdout:

Could you please suggest on how could i overcome the error.
which stable version of tensorflow should i use ?

Our need in a glance - To Run the Standalone embedding projector 
can we run the docker tensorflow ? does the docker tensorflow has the tensorboard and embedding projector ? can we build the source from the docker tensorflow  ?

Thanks in advance

**Comment by aaur0** [comment] 2020-06-18 22:22
For me, the patch command was missing
`yum install patch`
fixed the issue

**Comment by a540611121** [comment] 2020-09-17 09:18
> For me, the patch command was missing
> `yum install patch`
> fixed the issue

Thanks! It helps me solve the problem.
