### ISSUE TITLE
CSV data download stopped working

### ISSUE THREAD

**Issue by bstemper** [tensorflow/tensorboard#690] opened 2017-11-02 11:23 UTC
_My configuration_
- Mac OSSierra 10.12.6 (16G29)
- Python version 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 12:15:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
- Tensorflow version 1.3.0
- Chrome Version 61.0.3163.100

_Problem_
Tensorboard does display individual plots of tracked scalars but it won't let me download the data in either .csv or .json.  I have 'activated' the hyperlinks for the data to be downloaded but Chrome says in my download bar: "Failed - server problem". I have restarted my Macbook but to no avail. 

Edit: My filename contains '[' and ']'. Taking them away fixes the problem.

**Comment by nfelt** [comment] 2017-12-09 00:40
Could you clarify what you meant by your filename containing brackets?  What was the actual filename?  Since brackets are illegal characters for tensorflow scopes and node names, I'm not quite clear on how you'd arrive at a download filename with brackets in it.

If it's possible for you to provide a short snippet of TensorFlow code that generates the event data that reproduces the issue, that would be even better.

**Comment by bileschi** [comment] 2019-12-20 16:51
Closing as this appears to be a support issue with 2 years of inaction.  Please re-open if this is still an ongoing issue.

**Closed by bileschi** 2019-12-20 16:51 UTC
Labels: plugin:scalars, stat:awaiting response, type:bug
