### ISSUE TITLE
Ignore outliers setting can hide entire series

### ISSUE THREAD

**Issue by talesa** [tensorflow/tensorboard#150] opened 2017-06-23 21:39 UTC
y axis is not automatically adjusted (and cannot be manually adjusted either) to fit multiple runs data series on one plot.

Example: 
[[files to reproduce](https://s3-eu-west-1.amazonaws.com/adamg-files/logdir.zip)]
There are 2 runs (`train` and `validation`) and both contain the same variable `tower_0/costs/error`.

Till step ~2.5k, when both runs are selected, you can only see `train` run data. 
<img src="https://s3-eu-west-1.amazonaws.com/adamg-files/4.png" width="300">
It seems to me this is a bug, I would expect the y axis to be automatically adjusted to see both runs data series. The tooltip also doesn't show `validation` run data when I inspect the graph. However the `validation` run data is there and shows up once I deselect the 'train' run. (Pay attention to the y axis values between plots.)
<img src="https://s3-eu-west-1.amazonaws.com/adamg-files/3.png" width="300">
Only later once the `validation` error drops below initial `train` error you can see both runs at the same time, but you still cannot zoom out to see both data series in the entire range of x axis. That is certainly a missing feature. 
<img src="https://s3-eu-west-1.amazonaws.com/adamg-files/2.png" width="300">

Information which may be relevant:
-run `train` starts logging first in terms of steps and time
-run `validation` starts running and logging at arbitrary step, i.e. step count doesn't start at 0
I think this may be relevant to how tensorboard decides what axis limits to plot.

All in all it's an annoying bug, because I thought that the `validation` summaries are just not saved since I could not see them, and it took a while to realize they actually are saved, just not plotted. 

I'm using Tensorflow 1.2.0-rc0

**Comment by talesa** [comment] 2017-06-24 14:01
I've tried to reproduce errors again and this time I could not.
Also, running Tensorboard 54 on a different environment (machine different than the one I've reported from yesterday) I've noticed an option 'Ignore outliers in chart scaling' which probably deals with the issue I've described above. 
What is odd when running Tensorboard 54 on the machine I've used yesterday does not have an option 'Ignore outliers in chart scaling'.

**Comment by dandelionmane** [comment] 2017-06-26 18:56
I think this is caused by the "ignore outliers in chart scaling" aggregating all series together to compute outliers, rather than doing it on a per-series basis.

Your "train" dataset contains orders of magnitude more data than your validation dataset, so if you look at the entire dataset in aggregate, every validation point is an outlier.

We should fix this by computing outliers on a per-series basis, to ensure that every data series is included in the plot.

The issue you describe where you see/don't see the option is likely a result of caching, where your browser was keeping a copy of an older version of TensorBoard source - so you were launching TensorBoard 54 but actually seeing TensorBoard (x<54)'s frontend. When you launched it on a new machine, it had a new address so you didn't hit the stale cache. [Should I blame caching?](shouldiblamecaching.com)

We should also put the TensorBoard version into the UI, so that it'll be clearer to the user when they are hitting a stale cache. (Maybe we should also decrease the cache time down to like a day.) I'll make another issue for that.

**Comment by dandelionmane** [comment] 2017-06-26 19:04
Update: It looks like the caching expires after 1 hour (https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/core/core_plugin.py#L86) which seems pretty reasonable, so probably no need to change that. Although I'm still surprised you were getting served an old TB, unless you upgraded immediately before using it? Also, I'm confused how you would get a bug caused by the ignore outlier logic without having a UI that has the ignore outlier setting. So, something is going on that I don't understand.

**Comment by talesa** [comment] 2017-07-06 11:39
I have not upgraded TF on purpose at any point when that was happening and I reckon upgrading is not happening automatically/spontaneously either.

**Comment by dandelionmane** [comment] 2017-07-06 17:52
Glad you liked it :)
Since we can't reproduce this, and it looks like it may be related to old versions of TB, I'm going to close this for now. Please feel free to re-open if you find a repro and we'll dig into it.

**Closed by dandelionmane** 2017-07-06 17:52 UTC
Labels: core:frontend, type:bug/performance
