### ISSUE TITLE
Profiler in colab does not work with rustboard.

### ISSUE THREAD

**Issue by AdityaKane2001** [tensorflow/tensorboard#5088] opened 2021-06-23 04:31 UTC
Environment info
### Diagnostics

<details>
<summary>Diagnostics output</summary>

``````
--- check: autoidentify
INFO: diagnose_tensorboard.py version e43767ef2b648d0d5d57c00f38ccbd38390e38da

--- check: general
INFO: sys.version_info: sys.version_info(major=3, minor=7, micro=10, releaselevel='final', serial=0)
INFO: os.name: posix
INFO: os.uname(): posix.uname_result(sysname='Linux', nodename='bdf1a5820a21', release='5.4.104+', version='#1 SMP Sat Jun 5 09:50:34 PDT 2021', machine='x86_64')
INFO: sys.getwindowsversion(): N/A

--- check: package_management
INFO: has conda-meta: False
INFO: $VIRTUAL_ENV: None

--- check: installed_packages
INFO: installed: tensorboard==2.5.0
INFO: installed: tensorflow==2.5.0
INFO: installed: tensorflow-estimator==2.5.0
INFO: installed: tensorboard-data-server==0.6.1

--- check: tensorboard_python_version
INFO: tensorboard.version.VERSION: '2.5.0'

--- check: tensorflow_python_version
INFO: tensorflow.__version__: '2.5.0'
INFO: tensorflow.__git_version__: 'v2.5.0-0-ga4dfb8d1a71'

--- check: tensorboard_data_server_version
INFO: data server binary: '/usr/local/lib/python3.7/dist-packages/tensorboard_data_server/bin/server'
INFO: data server binary version: b'rustboard 0.6.1'

--- check: tensorboard_binary_path
INFO: which tensorboard: b'/usr/local/bin/tensorboard\n'

--- check: addrinfos
socket.has_ipv6 = True
socket.AF_UNSPEC = <AddressFamily.AF_UNSPEC: 0>
socket.SOCK_STREAM = <SocketKind.SOCK_STREAM: 1>
socket.AI_ADDRCONFIG = <AddressInfo.AI_ADDRCONFIG: 32>
socket.AI_PASSIVE = <AddressInfo.AI_PASSIVE: 1>
Loopback flags: <AddressInfo.AI_ADDRCONFIG: 32>
Loopback infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
Wildcard flags: <AddressInfo.AI_PASSIVE: 1>
Wildcard infos: [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('0.0.0.0', 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::', 0, 0, 0))]

--- check: readable_fqdn
INFO: socket.getfqdn(): 'bdf1a5820a21'

--- check: stat_tensorboardinfo
INFO: directory: /tmp/.tensorboard-info
INFO: os.stat(...): os.stat_result(st_mode=16895, st_ino=4989851, st_dev=50, st_nlink=2, st_uid=0, st_gid=0, st_size=4096, st_atime=1624420466, st_mtime=1624420465, st_ctime=1624420465)
INFO: mode: 0o40777

--- check: source_trees_without_genfiles
INFO: tensorboard_roots (1): ['/usr/local/lib/python3.7/dist-packages']; bad_roots (0): []

--- check: full_pip_freeze
INFO: pip freeze --all:
absl-py==0.12.0
alabaster==0.7.12
albumentations==0.1.12
altair==4.1.0
appdirs==1.4.4
argon2-cffi==20.1.0
arviz==0.11.2
astor==0.8.1
astropy==4.2.1
astunparse==1.6.3
async-generator==1.10
atari-py==0.2.9
atomicwrites==1.4.0
attrs==21.2.0
audioread==2.1.9
autograd==1.3
Babel==2.9.1
backcall==0.2.0
beautifulsoup4==4.6.3
bleach==3.3.0
blis==0.4.1
bokeh==2.3.2
Bottleneck==1.3.2
branca==0.4.2
bs4==0.0.1
CacheControl==0.12.6
cached-property==1.5.2
cachetools==4.2.2
catalogue==1.0.0
certifi==2021.5.30
cffi==1.14.5
cftime==1.5.0
chardet==3.0.4
click==7.1.2
cloudpickle==1.3.0
cmake==3.12.0
cmdstanpy==0.9.5
colorcet==2.0.6
colorlover==0.3.0
community==1.0.0b1
contextlib2==0.5.5
convertdate==2.3.2
coverage==3.7.1
coveralls==0.5
crcmod==1.7
cufflinks==0.17.3
cvxopt==1.2.6
cvxpy==1.0.31
cycler==0.10.0
cymem==2.0.5
Cython==0.29.23
daft==0.0.4
dask==2.12.0
datascience==0.10.6
debugpy==1.0.0
decorator==4.4.2
defusedxml==0.7.1
descartes==1.1.0
dill==0.3.4
distributed==1.25.3
dlib==19.18.0
dm-tree==0.1.6
docopt==0.6.2
docutils==0.17.1
dopamine-rl==1.0.5
earthengine-api==0.1.269
easydict==1.9
ecos==2.0.7.post1
editdistance==0.5.3
en-core-web-sm==2.2.5
entrypoints==0.3
ephem==4.0.0.2
et-xmlfile==1.1.0
fa2==0.3.5
fastai==1.0.61
fastdtw==0.3.4
fastprogress==1.0.0
fastrlock==0.6
fbprophet==0.7.1
feather-format==0.4.1
filelock==3.0.12
firebase-admin==4.4.0
fix-yahoo-finance==0.0.22
Flask==1.1.4
flatbuffers==1.12
folium==0.8.3
future==0.16.0
gast==0.4.0
GDAL==2.2.2
gdown==3.6.4
gensim==3.6.0
geographiclib==1.50
geopy==1.17.0
gin-config==0.4.0
gitdb==4.0.7
GitPython==3.1.18
glob2==0.7
google==2.0.3
google-api-core==1.26.3
google-api-python-client==1.12.8
google-auth==1.31.0
google-auth-httplib2==0.0.4
google-auth-oauthlib==0.4.4
google-cloud-bigquery==1.21.0
google-cloud-bigquery-storage==1.1.0
google-cloud-core==1.0.3
google-cloud-datastore==1.8.0
google-cloud-firestore==1.7.0
google-cloud-language==1.2.0
google-cloud-storage==1.18.1
google-cloud-translate==1.5.0
google-colab==1.0.0
google-pasta==0.2.0
google-resumable-media==0.4.1
googleapis-common-protos==1.53.0
googledrivedownloader==0.4
graphviz==0.10.1
greenlet==1.1.0
grpcio==1.34.1
gspread==3.0.1
gspread-dataframe==3.0.8
gviz-api==1.9.0
gym==0.17.3
h5py==3.1.0
HeapDict==1.0.1
hijri-converter==2.1.2
holidays==0.10.5.2
holoviews==1.14.4
html5lib==1.0.1
httpimport==0.5.18
httplib2==0.17.4
httplib2shim==0.0.3
humanize==0.5.1
hyperopt==0.1.2
ideep4py==2.0.0.post3
idna==2.10
imageio==2.4.1
imagesize==1.2.0
imbalanced-learn==0.4.3
imblearn==0.0
imgaug==0.2.9
importlib-metadata==4.5.0
importlib-resources==5.1.4
imutils==0.5.4
inflect==2.1.0
iniconfig==1.1.1
install==1.3.4
intel-openmp==2021.2.0
intervaltree==2.1.0
ipykernel==4.10.1
ipython==5.5.0
ipython-genutils==0.2.0
ipython-sql==0.3.9
ipywidgets==7.6.3
itsdangerous==1.1.0
jax==0.2.13
jaxlib==0.1.66+cuda110
jdcal==1.4.1
jedi==0.18.0
jieba==0.42.1
Jinja2==2.11.3
joblib==1.0.1
jpeg4py==0.1.4
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.3.5
jupyter-console==5.2.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
kaggle==1.5.12
kapre==0.3.5
Keras==2.4.3
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
keras-vis==0.4.1
kiwisolver==1.3.1
korean-lunar-calendar==0.2.1
librosa==0.8.1
lightgbm==2.2.3
llvmlite==0.34.0
lmdb==0.99
LunarCalendar==0.0.9
lxml==4.2.6
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.2.2
matplotlib-inline==0.1.2
matplotlib-venn==0.11.6
missingno==0.4.2
mistune==0.8.4
mizani==0.6.0
mkl==2019.0
mlxtend==0.14.0
more-itertools==8.8.0
moviepy==0.2.3.5
mpmath==1.2.1
msgpack==1.0.2
multiprocess==0.70.12.2
multitasking==0.0.9
murmurhash==1.0.5
music21==5.5.0
natsort==5.5.0
nbclient==0.5.3
nbconvert==5.6.1
nbformat==5.1.3
nest-asyncio==1.5.1
netCDF4==1.5.6
networkx==2.5.1
nibabel==3.0.2
nltk==3.2.5
notebook==5.3.1
numba==0.51.2
numexpr==2.7.3
numpy==1.19.5
nvidia-ml-py3==7.352.0
oauth2client==4.1.3
oauthlib==3.1.1
okgrade==0.4.3
opencv-contrib-python==4.1.2.30
opencv-python==4.1.2.30
opencv-python-headless==4.5.2.54
openpyxl==2.5.9
opt-einsum==3.3.0
osqp==0.6.2.post0
packaging==20.9
palettable==3.3.0
pandas==1.1.5
pandas-datareader==0.9.0
pandas-gbq==0.13.3
pandas-profiling==1.4.1
pandocfilters==1.4.3
panel==0.11.3
param==1.10.1
parso==0.8.2
pathlib==1.0.1
patsy==0.5.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.2
pip==19.3.1
pip-tools==4.5.1
plac==1.1.3
plotly==4.4.1
plotnine==0.6.0
pluggy==0.7.1
pooch==1.4.0
portalocker==2.0.0
portpicker==1.3.9
prefetch-generator==1.0.1
preshed==3.0.5
prettytable==2.1.0
progressbar2==3.38.0
prometheus-client==0.11.0
promise==2.3
prompt-toolkit==1.0.18
protobuf==3.12.4
psutil==5.4.8
psycopg2==2.7.6.1
ptyprocess==0.7.0
py==1.10.0
py-cpuinfo==8.0.0
pyarrow==3.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycocotools==2.0.2
pycparser==2.20
pyct==0.4.8
pydata-google-auth==1.2.0
pydot==1.3.0
pydot-ng==2.0.0
pydotplus==2.0.2
PyDrive==1.3.1
pyemd==0.5.1
pyerfa==2.0.0
pyglet==1.5.0
Pygments==2.6.1
pygobject==3.26.1
pymc3==3.11.2
PyMeeus==0.5.11
pymongo==3.11.4
pymystem3==0.2.0
PyOpenGL==3.1.5
pyparsing==2.4.7
pyrsistent==0.17.3
pysndfile==1.3.8
PySocks==1.7.1
pystan==2.19.1.1
pytest==3.6.4
python-apt==0.0.0
python-chess==0.23.11
python-dateutil==2.8.1
python-louvain==0.15
python-slugify==5.0.2
python-utils==2.5.6
pytz==2018.9
pyviz-comms==2.0.2
PyWavelets==1.1.1
PyYAML==5.4.1
pyzmq==22.1.0
qdldl==0.1.5.post0
qtconsole==5.1.0
QtPy==1.9.0
regex==2019.12.20
# Editable install with no version control (regnety==0.0.0)
-e /content
requests==2.23.0
requests-oauthlib==1.3.0
resampy==0.2.2
retrying==1.3.3
rpy2==3.4.5
rsa==4.7.2
sacrebleu==1.5.1
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.4.1
screen-resolution-extra==0.0.0
scs==2.1.4
seaborn==0.11.1
semver==2.13.0
Send2Trash==1.5.0
sentencepiece==0.1.96
seqeval==1.2.2
setuptools==57.0.0
setuptools-git==1.2
Shapely==1.7.1
simplegeneric==0.8.1
six==1.15.0
sklearn==0.0
sklearn-pandas==1.8.0
smart-open==5.1.0
smmap==4.0.0
snowballstemmer==2.1.0
sortedcontainers==2.4.0
SoundFile==0.10.3.post1
spacy==2.2.4
Sphinx==1.8.5
sphinxcontrib-serializinghtml==1.1.5
sphinxcontrib-websupport==1.2.4
SQLAlchemy==1.4.18
sqlparse==0.4.1
srsly==1.0.5
statsmodels==0.10.2
sympy==1.7.1
tables==3.4.4
tabulate==0.8.9
tblib==1.7.0
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-profile==2.4.0
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.0
tensorflow-addons==0.13.0
tensorflow-datasets==4.0.1
tensorflow-estimator==2.5.0
tensorflow-gcs-config==2.5.0
tensorflow-hub==0.12.0
tensorflow-metadata==1.0.0
tensorflow-model-optimization==0.6.0
tensorflow-probability==0.12.1
termcolor==1.1.0
terminado==0.10.1
testpath==0.5.0
text-unidecode==1.3
textblob==0.15.3
tf-models-official==2.5.0
tf-slim==1.1.0
Theano-PyMC==1.1.2
thinc==7.4.0
tifffile==2021.6.14
toml==0.10.2
toolz==0.11.1
torch==1.9.0+cu102
torchsummary==1.5.1
torchtext==0.10.0
torchvision==0.10.0+cu102
tornado==5.1.1
tqdm==4.41.1
traitlets==5.0.5
tweepy==3.10.0
typeguard==2.7.1
typing-extensions==3.7.4.3
tzlocal==1.5.1
uritemplate==3.0.1
urllib3==1.24.3
vega-datasets==0.9.0
wasabi==0.8.2
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==1.0.1
wheel==0.36.2
widgetsnbextension==3.5.1
wordcloud==1.5.0
wrapt==1.12.1
xarray==0.18.2
xgboost==0.90
xkit==0.0.0
xlrd==1.1.0
xlwt==1.3.0
yellowbrick==0.9.1
zict==2.0.0
zipp==3.4.1

``````

</details>

### Next steps

No action items identified. Please copy ALL of the above output,
including the lines containing only backticks, into your GitHub issue
or comment. Be sure to redact any sensitive information.

## Issue description

I trained a small model using a custom dataloader which returns 
```
<BatchDataset shapes: ((None, None, None, None), (None, 10)), types: (tf.float32, tf.float32)> # Basically (image, label)
```
I want to profile the dataloader, and thus I installed tensorboard plugin and fired up tensorboard and went to the profile tab.
However, the profile tab is stuck at "Loading data" as shown in the image below.
![tboard](https://user-images.githubusercontent.com/64411306/123035715-6c32e100-d409-11eb-826d-50f57b23138e.png)

I tried running the [tutorial notebook](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_profiling_keras.ipynb#scrollTo=Q2rhYXT2WAyt) for profiler, end to end, but it results in the exact same issue. 
Following is the code that resulted in this behaviour: (all of this is done in colab)
```python

!pip install -U tensorboard-plugin-profile
model = tf.keras.Sequential(
    [
     tf.keras.layers.InputLayer(input_shape = (224,224,3)),
     tf.keras.layers.experimental.preprocessing.Normalization(mean = 0, variance = 1),
     tf.keras.layers.Conv2D(10, 5),
     tf.keras.layers.Conv2D(10, 5),
     tf.keras.layers.Conv2D(10, 5),
     tf.keras.layers.GlobalAveragePooling2D(),
     tf.keras.layers.Dense(10, activation = 'sigmoid')
    ]
)
model.compile(
    loss='categorical_crossentropy',
    optimizer=tf.keras.optimizers.Adam(0.001),
    metrics=['accuracy']
)
logs = "logs/" + '2'

tboard_callback = tf.keras.callbacks.TensorBoard(log_dir = logs,
                                                 histogram_freq = 1,
                                                 profile_batch = '2,8')

model.fit(ds,
          epochs=2,
          steps_per_epoch = 10,
          #validation_data=ds_test,
          callbacks = [tboard_callback])
%load_ext tensorboard
%tensorboard  --logdir=/content/logs

**Comment by soto-13** [comment] 2021-06-24 10:35
I have the same issue (not running on collab). Launching TensorBoard from vsCode or simply terminal will show me this spinning arrow forever...

**Comment by yisitu** [comment] 2021-06-24 20:33
This does not seem to be unique to the profiler. Cycling through the other tools at the top left (scalars, histogram etc), there seems to be no data available, or the data could not be loaded.

**Comment by hrishikeshps94** [comment] 2021-06-25 11:32
I'm also having the same issue. First tried with my custom code it was stuck at loading data. Then tried with the profiler tutorial it also shows the same loading data. Both the codes were tried in google colab.

**Comment by hrishikeshps94** [comment] 2021-06-25 12:03
Issue can be resolved by updating the command from %tensorboard  --logdir=/content/logs to %tensorboard  --logdir=/content/logs --load_fast=false.

**Comment by AdityaKane2001** [comment] 2021-06-25 12:35
@hrishikeshps94 
>%tensorboard --logdir=/content/logs --load_fast=false.

Worked like a charm! Thanks a lot!

**Comment by bmd3k** [comment] 2021-06-25 13:50
Will reopen for now. I'd like to understand if profiler is supposed to work with load_fast=true. Will chat with the team internally.

What I did and observed:
* I followed the instructions in the colab.
* Tabs 'scalars', 'graphs', 'distributions', 'histograms', and 'time series' worked fine given the instructions.
* Profiler was stuck at "Loading Data...", as reported in the bug.
* As per hrishikeshps94's suggestion, I modified the tensorboard command to use '--load_fast=false'... and the Profiler plugin worked.

**Comment by bmd3k** [comment] 2021-06-25 15:30
@yisitu

Support for --load_fast was added to profiler in https://github.com/tensorflow/profiler/pull/307/files. Has that change made it into the profiler being run in the colab? Should it work in colab?

More context:
https://github.com/tensorflow/tensorboard/issues/4784#issuecomment-815974912
https://github.com/tensorflow/profiler/issues/298

**Comment by yisitu** [comment] 2021-06-25 17:24
@jimicy PTAL

**Comment by soto-13** [comment] 2021-06-26 09:09
For me the %--load_fast=false did not fix it, just from running on a terminal locally (not collab). Tensorboard 2.5.0, Tensorflow 2.5.0, OSX
Did this fix work for people on local too?

![Screen Shot 2021-06-26 at 11 05 30](https://user-images.githubusercontent.com/63561955/123508255-8faa9580-d66e-11eb-8b23-9510e1cd24e7.png)

**Comment by hrishikeshps94** [comment] 2021-06-26 09:11
@soto-13 For me it worked in the local too.

**Comment by soto-13** [comment] 2021-06-26 13:03
Hmm right Ubuntu though, it still doesn't work here but with tensorboard dev it does.

**Comment by tsonic** [comment] 2021-06-28 02:01
> For me the %--load_fast=false did not fix it, just from running on a terminal locally (not collab). Tensorboard 2.5.0, Tensorflow 2.5.0, OSX
> Did this fix work for people on local too?
> 
> ![Screen Shot 2021-06-26 at 11 05 30](https://user-images.githubusercontent.com/63561955/123508255-8faa9580-d66e-11eb-8b23-9510e1cd24e7.png)

I have the same issue as in this screenshot. No tabs show up and spinner is spinning for ever. I used --inspect command and confirmed event files found in the logdir.

**Comment by silvanmurre** [comment] 2021-06-28 10:36
> > For me the %--load_fast=false did not fix it, just from running on a terminal locally (not collab). Tensorboard 2.5.0, Tensorflow 2.5.0, OSX
> > Did this fix work for people on local too?
> > ![Screen Shot 2021-06-26 at 11 05 30](https://user-images.githubusercontent.com/63561955/123508255-8faa9580-d66e-11eb-8b23-9510e1cd24e7.png)
> 
> I have the same issue as in this screenshot. No tabs show up and spinner is spinning for ever. I used --inspect command and confirmed event files found in the logdir. I am using ubuntu 20.04, python 3.7 and tensorboard 2.5.

Same here, I am totally lost here.. Using ubuntu 20.04, python 3.8.5, pytorch 1.9.0, torchvision 0.10.0, tensorboard 2.5 and tensorboardX=2.2

**Comment by bmd3k** [comment] 2021-06-28 11:12
@soto-13 , @tsonic , @silvanmurre 

Thanks for your reports. They don't appear related to the original issue reported. To help troubleshoot your problems, have you tried reading our [FAQ](https://github.com/tensorflow/tensorboard#frequently-asked-questions), or checked out our [GitHub issues](https://github.com/tensorflow/tensorboard/issues) and [StackOverflow](https://stackoverflow.com/questions/tagged/tensorboard)?

If you think you have found a bug in tensorboard, could you create a new GitHub issue and provide the information necessary to reproduce the problem?

**Comment by silvanmurre** [comment] 2021-06-28 11:49
> @soto-13 , @tsonic , @silvanmurre
> 
> Thanks for your reports. They don't appear related to the original issue reported. To help troubleshoot your problems, have you tried reading our [FAQ](https://github.com/tensorflow/tensorboard#frequently-asked-questions), or checked out our [GitHub issues](https://github.com/tensorflow/tensorboard/issues) and [StackOverflow](https://stackoverflow.com/questions/tagged/tensorboard)?
> 
> If you think you have found a bug in tensorboard, could you create a new GitHub issue and provide the information necessary to reproduce the problem?

Apologies for not searching through the other issues, issue #270 mentions that it can be fixed by uninstalling 'torch-tb-profiler'. If it is installed and there is no profile data it will hang forever.

**Comment by tsonic** [comment] 2021-06-28 17:09
> @soto-13 , @tsonic , @silvanmurre
> 
> Thanks for your reports. They don't appear related to the original issue reported. To help troubleshoot your problems, have you tried reading our [FAQ](https://github.com/tensorflow/tensorboard#frequently-asked-questions), or checked out our [GitHub issues](https://github.com/tensorflow/tensorboard/issues) and [StackOverflow](https://stackoverflow.com/questions/tagged/tensorboard)?
> 
> If you think you have found a bug in tensorboard, could you create a new GitHub issue and provide the information necessary to reproduce the problem?



> > @soto-13 , @tsonic , @silvanmurre
> > Thanks for your reports. They don't appear related to the original issue reported. To help troubleshoot your problems, have you tried reading our [FAQ](https://github.com/tensorflow/tensorboard#frequently-asked-questions), or checked out our [GitHub issues](https://github.com/tensorflow/tensorboard/issues) and [StackOverflow](https://stackoverflow.com/questions/tagged/tensorboard)?
> > If you think you have found a bug in tensorboard, could you create a new GitHub issue and provide the information necessary to reproduce the problem?
> 
> Apologies for not searching through the other issues, issue [pytorch/kineto#270](https://github.com/pytorch/kineto/issues/270) mentions that it can be fixed by uninstalling 'torch-tb-profiler', which works for me. If it is installed and there is no profile data it will hang forever.

Apologies for diverging the thread. I thought the problem is related. I have also searched this issue on Github issue and StackOverflow for a while but still struggle to find a report of similar symptoms. Thanks @silvanmurre  for finding the fix! It worked for me as well. Did not realize that this could be an issue related to tensorboard plugin which cause tensorboard to hang.

**Comment by 8bitmp3** [comment] 2021-08-02 20:10
Hi eveyerone, if you're still experiencing any issues, try installing the latest Profiler plugin with `pip install tensorboard_plugin_profile` (or `tensorboard_plugin_profile==2.5.0`). Thanks @yisitu 👍

**Comment by yisitu** [comment] 2021-08-02 21:58
You are welcome!

**Comment by bmd3k** [comment] 2021-08-05 20:40
Profiler also works for me in colab now.
@AdityaKane2001, do you mind confirming and reopening if you still have this issue?

**Closed by bmd3k** 2021-08-05 20:40 UTC
Labels: type:bug, core:frontend, plugin:profile, stat:awaiting response, theme:performance, core:rustboard

**Comment by AdityaKane2001** [comment] 2021-08-06 02:00
@bmd3k 
Yup, not an issue for me anymore
