### ISSUE TITLE
Smoothing produces weird plots

### ISSUE THREAD

**Issue by lcswillems** [tensorflow/tensorboard#1224] opened 2018-06-04 18:14 UTC
When `smoothing` is not 0, this kind of wierd graphs appear:

![image](https://user-images.githubusercontent.com/5437552/40934025-6f9565ec-6801-11e8-918d-f8c03f0317b5.png)

**Comment by nfelt** [comment] 2018-06-04 18:47
What kind of plot are you expecting?  Is the plot supposed to be a constant, i.e. a horizontal line?  If so, this is a duplicate of #786.

In general, a screenshot of what you expect / what it looks like when smoothing is 0 would be useful.

**Comment by lcswillems** [comment] 2018-06-04 19:55
When smoothing is 0, the line is horizontal what is right. And yes, it is a duplicate. Sorry!

**Comment by nfelt** [comment] 2018-06-04 20:05
Duplicate of #786 

No worries, thanks for reporting anyway.

**Closed by nfelt** 2018-06-04 20:05 UTC
Labels: plugin:scalars, type:bug/performance
