### ISSUE TITLE
Scalars tutorial is missing a TF import

### ISSUE THREAD

**Issue by GalOshri** [tensorflow/tensorboard#2926] opened 2019-11-12 22:57 UTC
Hello! I think the [Scalars tutorial](https://www.tensorflow.org/tensorboard/scalars_and_keras) is missing a TF import.

Repro steps:
1. Go to the [Scalars tutorial](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/scalars_and_keras.ipynb) in Colab
2. Run the first two code cells

![image](https://user-images.githubusercontent.com/2601900/68717740-681bbd80-055c-11ea-9ac2-6662e9319fc5.png)

This is solved by adding `import tensorflow as tf`. 

Additional stylistic issue: `%tensorflow_version 2.x` appears twice. I believe this will break outside of Colab (as the second one is not in a `try` `except`.

**Comment by psybuzz** [comment] 2019-11-12 23:29
Thanks for the report.  This is really unfortunate, it looks like the tutorials "Scalars and metrics", "Image data", and "TensorBoard in Notebooks" all lack this import, giving the same error when running the notebook.

**Comment by ymodak** [comment] 2021-02-26 17:51
Closing this issue since the associated PR has been merged and the issue is fixed. Thanks!

**Closed by ymodak** 2021-02-26 17:51 UTC
Labels: stat:awaiting tensorflower, type:docs
