### ISSUE TITLE
export to .csv or .json with more than 1000 steps

### ISSUE THREAD

**Issue by jpainam** [tensorflow/tensorboard#4047] opened 2020-08-18 14:40 UTC
Hi, as you can see in this picture, i have more than 1000 steps
![image](https://user-images.githubusercontent.com/1701705/90527020-a7d69c00-e1a3-11ea-9eec-6119d3c9a688.png)
But when i export to json or csv, it only exports 1000 steps. How to export all the `14k` steps that i have
Thank you

**Comment by wchargin** [comment] 2020-08-18 15:35
Hi @jpainam! Thanks for the question. We discuss this a bit [in the
README][1]:

> TensorBoard uses [reservoir
> sampling](https://en.wikipedia.org/wiki/Reservoir_sampling) to downsample your
> data so that it can be loaded into RAM. You can modify the number of elements it
> will keep per tag by using the `--samples_per_plugin` command line argument (ex:
> `--samples_per_plugin=scalars=500,images=20`).

So, if you pass `--samples_per_plugin=scalars=15000`, then you’ll be
able to download 15,000 points per time series. There’s not currently a
way to specify unlimited downsampling (i.e., to disable it).

I’m going to close this since it’s discussed in the FAQ and in other
similar issues, but please feel free to comment if you have any
follow-up questions. thanks!

[1]: https://github.com/tensorflow/tensorboard#is-my-data-being-downsampled-am-i-really-seeing-all-the-data

**Closed by wchargin** 2020-08-18 15:35 UTC

**Comment by nfelt** [comment] 2020-08-18 21:08
FWIW, you can specify unlimited samples by setting the value to `0`.

https://github.com/tensorflow/tensorboard/blob/5ba8e33c367077b4af718ed0535898e16d6ecde7/tensorboard/plugins/core/core_plugin.py#L525-L527

**Comment by wchargin** [comment] 2020-08-18 21:26
@nfelt: That doesn’t work in the generic data read paths, since we
forward the downsampling to the data provider. It was also never
documented as working in the flag text or user documentation, which is
why I don’t consider it a regression.

**Comment by nfelt** [comment] 2020-08-18 21:48
Ack, good point about not working in generic data read paths - so the workaround to avoid sampling would just be to set a very large number.
