### ISSUE TITLE
Feature request: making window wider

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorboard#1322] opened 2018-07-27 18:44 UTC
Here's what it looks like on my screen, it would be nice to make it wider so that "full screen" button for a graph can make a bigger graph
![screenshot 2018-07-27 11 43 03](https://user-images.githubusercontent.com/23068/43340778-49cf4188-9192-11e8-895c-0d984c3a1e6a.png)

**Comment by stephanwlee** [comment] 2018-07-27 18:48
Hi @yaroslavvb, which version are you using? If you are using nightly or based on HEAD, you might have witnessed a recent regression on this.

**Comment by yaroslavvb** [comment] 2018-07-27 18:59
I'm using TensorBoard 1.9.0

**Comment by yaroslavvb** [comment] 2018-07-31 22:16
I just opened same server on friend's computer, and his TB looks fine. Same version of MacOS and Chrome. Updated Chrome, still narrow. Checked in Firefox, looks fine. So there's some local setting on my Chrome that makes window narrow, with only 1 plot per column

**Comment by stephanwlee** [comment] 2018-07-31 22:25
Right, I was wondering if we ever had a UI like that and it seems unlikely that we did. Looking at the pretty rounded corners and what not (which we definitely didn't do), it looks like some kind of extension is causing this. Do you suspect any extension or anything that can influence the looks? 
Thanks

**Comment by yaroslavvb** [comment] 2018-07-31 22:43
Bingo!
It was this extension
https://chrome.google.com/webstore/detail/play/gklfcaofjmilchcphdgbhjeoopdaejje

**Comment by stephanwlee** [comment] 2018-07-31 23:01
Yup, in the source code of the plugin, I found the CSS selector that matches ours: gklfcaofjmilchcphdgbhjeoopdaejje/1.5.0_0/assets/styles/authors/dropdown-style.css#L326

```
.dashboard-container{
  width: 950px;
  height: 630px;
  padding: 15px 30px;
  margin: 2% auto 0;
  background: #fff;
 ...
```

Technically speaking, the Extension should take effect to _whitelist_ of urls but it seems to apply to all URLs (gklfcaofjmilchcphdgbhjeoopdaejje/1.5.0_0/manifest.json#L13). If this were a GitHub project, I would file an issue against them but it doesn't look like an open source project.

Anyways, I will close the issue :)

**Closed by stephanwlee** 2018-07-31 23:01 UTC
Labels: core:frontend
